### ISSUE TITLE
about powershell on windows，set up wrong

### ISSUE THREAD

**Issue by chengkai2022** [Schniz/fnm#1011]
![image](https://github.com/Schniz/fnm/assets/70818246/3172eb86-033d-4a4d-8073-6a428b2efa69)

![image](https://github.com/Schniz/fnm/assets/70818246/91f4feee-1820-49e7-8563-0dd260863630)
i get java-jdk8 on my computer，it is Affected？
but in cmd it success

**Comment by chengkai2022** [comment]
i have set that file in right position。here，i only show the error

**Comment by saitonakamura** [comment]
Can post the output of `fnm env --use-on-cd | Out-String`?

**Comment by chengkai2022** [comment]
> 
![image](https://github.com/Schniz/fnm/assets/70818246/47511ad2-667c-4aa0-89a3-5ea88d18d6d5)

**Comment by chengkai2022** [comment]
> Can post the output of `fnm env --use-on-cd | Out-String`?

have some idea？

**Comment by alumni** [comment]
@chengkai2022 your path contains `"` characters, which are not escaped by `fnm`.

However, `"` is not a valid path character, so probably you should check why you have it.

**Comment by saitonakamura** [comment]
Yeah, I think if you'll remove double quotes around tomcat paths it'll be resolved. https://www.wikihow.com/Change-the-PATH-Environment-Variable-on-Windows

**Comment by chengkai2022** [comment]
on windows,when set two paths as one splice width` ;`,it works but get` "..."`
such as `%PATHEXT%;.RB;.RBW`
set it as `%PATHEXT%`,`.RBW` twice .my error remove,thanks
