### ISSUE TITLE
Disable fnm message `Using Node vX.X.X` at startup

### ISSUE THREAD

**Issue by thatanjan** [Schniz/fnm#1015]
I have a `.nvmrc` file in my project. Everytime I open up the directory or I restart fish then I get the message. 
Is there any way to disable this?
![image](https://github.com/Schniz/fnm/assets/71136371/64bf46af-254c-436b-b946-6750f91f62ed)

Fish version: 3.6.1
Fnm: 1.34.0
Distro: Arco Linux

Thanks in advance

**Comment by sambauers** [comment]
Add `--log-level quiet` to the initialisation command in your shell profile (`.zshrc` or similar).

**Comment by thatanjan** [comment]
> Add --log-level quiet to the initialisation command in your shell profile (.zshrc or similar).

@sambauers It doesn't work. If I pass `--log-level <value>` it just gives the output as if I am running `fnm` without any option.
![image](https://github.com/Schniz/fnm/assets/71136371/6554b168-333e-4152-b434-543fc615723e)

**Comment by sambauers** [comment]
In your fish config, which should be somewhere like `~/.config/fish/conf.d/fnm.fish`, you should have a line like the following already:

```sh
fnm env --use-on-cd | source
```

Add the log level option there, something like:

```sh
fnm env --use-on-cd --log-level quiet | source
```

**Comment by thatanjan** [comment]
Thanks @sambauers for the help.
