### ISSUE TITLE
How do you start fnm binaries as a systemd service?

### ISSUE THREAD

**Issue by cmdruid** [Schniz/fnm#1023]
Hello. I am having trouble figuring out how to start fnm binaries in the multishell path as a systemd service.

When I run `which npx` for example, I will get the following bin path:

`/run/user/1000/fnm_multishells/1233_1691082334072/bin/npx`

However when I run `sudo -u user which npx` (let's say 'user' is id 1000), the bin path does not exist.

If I set my PATH to something like:

`/home/user/.local/state/fnm_multishells/1233_1691082334072/bin`

then I will see the path for npx, however this path fails to be reachable by a systemd service (even when I set the service to login as 'user').

I'm sort of at a loss for how one is supposed to setup a systemd service to work with fnm and its multishells. Any help or guidance would be appreciated.

**Comment by Schniz** [comment]
Maybe fnm exec can help? https://github.com/Schniz/fnm/blob/master/docs/commands.md#fnm-exec

**Comment by cmdruid** [comment]
Thank you. Yes, fnm exec is what I was looking for!

For future reference, here is my example `nodeapp.service` file. Replace `user` with the user running fnm, and replace `yarn start` with whatever command you want fnm to run:

```service
[Unit]
Description=Node App Service
After=network.target

[Service]
Restart=on-failure
User=user
Group=user
Environment=NODE_ENV=production
WorkingDirectory=/home/user/node-app
ExecStart=/home/user/.local/share/fnm/fnm exec yarn start

[Install]
WantedBy=multi-user.target
```
