### ISSUE TITLE
How to upgrade the current node version to the latest?

### ISSUE THREAD

**Issue by gwsbhqt** [Schniz/fnm#1041]
How to upgrade the current node version to the latest? As shown in the figure below, v16.20.1 should be upgraded to v16.20.2, v18.17.0 should be upgraded to v18.17.1. May need to provide a command "fnm update" or "fnm upgrade"

<img width="335" alt="image" src="https://github.com/Schniz/fnm/assets/16471930/f2abb64a-6314-42e3-9aa4-1743d612b4b8">

**Comment by ivandotv** [comment]
if you do `fnm install 16` it will update to latest V16
