### ISSUE TITLE
Version error occurs when installing node

### ISSUE THREAD

**Issue by MrZhuA00** [Schniz/fnm#1045]
I want to install node14.16.1 but 14.23.3 is installed instead . 
I think this should be a bug

![image](https://github.com/Schniz/fnm/assets/102725920/021d1fa1-c7bb-43bc-92c1-42f28a192254)

![image](https://github.com/Schniz/fnm/assets/102725920/9f4a0edb-ee7d-4a0c-9d4f-8d0a07d19e01)

**Comment by MrZhuA00** [comment]
sorry I found an error symbol in the command

**Comment by Schniz** [comment]
@MrZhuA00  an error symbol? What do you mean?
