### ISSUE TITLE
keep up the good work!

### ISSUE THREAD

**Issue by MuhAssar** [Schniz/fnm#1069]
Hi, thanks for this tool much appreciated.

I just noticed that the following image in the readme
https://github.com/Schniz/fnm/raw/master/docs/fnm.svg

contains a symbol commonly associated with the Apartheid State of Israel, according to the united nations[0], the human rights watch[1] and amnesty[2][3].

this state is currently also commiting a genocide against 2 million people.

so I think it is better -for the sake of the project- to remove this hatred symbol from the readme. 

keep up the good work!

------
[0] https://news.un.org/en/story/2022/03/1114702
[1] https://www.hrw.org/report/2021/04/27/threshold-crossed/israeli-authorities-and-crimes-apartheid-and-persecution
[2] https://www.amnesty.org/en/latest/campaigns/2022/02/israels-system-of-apartheid/
[3] https://www.amnesty.org/en/latest/news/2022/02/israels-apartheid-against-palestinians-a-cruel-system-of-domination-and-a-crime-against-humanity/

**Comment by Schniz** [comment]
No

**Comment by Schniz** [comment]
And that’s a very rude request.

**Comment by AbdoZDGaia** [comment]
> And that’s a very rude request.

That's a very rude gesture to include such a shocking and emotionally provoking symbol (one that's not remotely needed to be included) in your project.

What's the difference between you and someone else using the Nazi Swastika now?

**Comment by Schniz** [comment]
Star of David is a Jewish symbol. The Israeli flag used it as its a state of the Jewish people. Claiming it is provoking as the swastika shows nothing but ignorance ant best and antisemitism at worst. I am not provoked by any Muslim or Christian symbols. We are all people. If you think my symbol choices in the README are not good, you can take back the money you spent on fnm, chief. Anyone that is provoked by Judaism isn’t welcomed here and can get the fuck out of this repo.

**Comment by AbdoZDGaia** [comment]
> Star of David is a Jewish symbol. The Israeli flag used it as its a state of the Jewish people. Claiming it is provoking as the swastika shows nothing but ignorance ant best and antisemitism at worst. I am not provoked by any Muslim or Christian symbols. We are all people. If you think my symbol choices in the README are not good, you can take back the money you spent on fnm, chief. Anyone that is provoked by Judaism isn’t welcomed here and can get the fuck out of this repo.

What a great word play.
Zionism is NOT judaism, just as Isis is not Islam.
You cant hate on islam just as much as I cant and don't hate on judaism.
You waving the symbol of Israel in our faces just as soon as it has committed such atrocities is nothing short of being senseless and is quite frankly inhuman.
Has nothing to do with your religion or mine, it has to do with basic human decency, compassion and professionalism.
Especially when you're literally waving that symbol in our faces while it adds absolutely zero value to ur project and quite frankly pushes ppl away, all kinds of people btw not just arabs or muslims.
As for your project, don't make me laugh please, I would rather flush my money down the toilet than spend it on you with this mentality of yours.
Off you go son.

**Comment by aviramha** [comment]
I don't think you really care but Star of David doesn't imply Israel just as a ☪️ doesn't imply Turkey just as  ✝️ doesn't imply Denmark or Finland etc.

**Comment by ranyitz** [comment]
> What's the difference between you and someone else using the Nazi Swastika now?

@AbdoZDGaia There is a big difference.

The Star of David is a symbol commonly associated with Judaism. Historically, it has been a symbol of Jewish identity and heritage, with no inherently negative connotations.

The Swastika was adopted by Adolf Hitler and the Nazi Party as their symbol in Germany. It is strongly associated with the atrocities of the Holocaust and the genocide committed during World War II. It is a symbol of hatred, racism, and anti-Semitism.

**Comment by AbdoZDGaia** [comment]
The black flag with "محمد رسول الله" written on it used to represent the islamic nation back when prophet Mohammad PBUH was preaching Islam.
Right now, the only thing that comes to mind when you flash it into some1s face is "ISIS" not the old Islamic nation, since it has been used by the terrorist group to terrorize and spread fear into their enemies hearts and minds.
Likewise, the star of David PBUH doesnt even remotely signify anything, and I mean ANYTHING but the state of Isreal and their Zion protocols.
Just like ISIS doesn't represent Islam, Zionists and Isrealis don't represent Judaism or the moderate non-extremist Jewish community.
Stop trying to make Isreali and Jew the same, cuz they're not.
Currently the star of David is the world-wide known Isreali symbol, and wrongfully too since many orthodox jews stand firmly against Zionism.
Putting that symbol promotes the acts of the Isreali forces against Human freaking beings let alone civilians and peaceful bystanders.
You might as well put up the Swastika and start burning them, cuz there's virtually no difference between you and them right now.

**Comment by Schniz** [comment]
Sorry to be this blunt: no one asked you.

I am Jewish. I am Israeli. Always has been. The Star of David was here from the initial commits. It wasn’t a problem until Hamas massacred and kidnapped my people and now you come here and claiming genocide? GTFO.

I spend my time to give away a product for free. Feel free to feel provoked that jews exist and have a country. I don’t really care. If you want to express your hatred just don’t use it. And if you use it, then swallow the hard pill that an Israeli Jewish person is happy to give you something you enjoy using. Maybe it’ll get your priorities straight.

Salamat!
