### ISSUE TITLE
Installing from fish via Homebrew

### ISSUE THREAD

**Issue by deepfriedmind** [Schniz/fnm#107]
When I ran `brew install Schniz/tap/fnm` I got the following "caveat":

```
Skipped the installation of fnm to ~/.config/fish/config.fish because I found `# fnm`.
In case you want to do it manually, add the following to the file:

  # fnm
  eval "$(fnm env --multi)"
```

I did not have that in my `config.fish` previously, so it was definitely added during installation. However, this isn't the correct syntax for fish and will break the config. It should be `fnm env --multi | source`, right?

**Comment by Schniz** [comment]
You are correct! This is weird, I thought it would work:
https://github.com/Schniz/homebrew-tap/blob/0b3b01af9ff34e1132ae8d7c13af3dda7b6a14ca/Formula/fnm.rb#L33-L39

Do you want to try to debug it, or you want me to do that? 😄 

I consider adding the "setup script" to fnm as well, but that would probably be super weird

**Comment by deepfriedmind** [comment]
Where does the `preferred` variable come from?

**Comment by jorenvanhee** [comment]
This works for me, thanks 👍 

```
# fnm
fnm env --multi | source
```

**Comment by Schniz** [comment]
The installation script now support MacOS again, so I'm closing this. Feel free to reopen if it is still an issue. I don't use Fish but we do support it. A simple test can be filed against https://github.com/Schniz/homebrew-tap/blob/master/Formula/fnm.rb in the tap repo.
