### ISSUE TITLE
FREE PALESTINE...BOYCOTT ISRAEL AND SUPPORTERS

### ISSUE THREAD

**Issue by AbdoZDGaia** [Schniz/fnm#1070]
This issue is a continuance to the other one you so rudely interrupted and so cowardly banned me from replying to.
Since you so bluntly support Israel's recent actions and justify them as self-defence, I call you out to practice the most fitting self-defence mechanism and leave Palestine altogether since you've taken it by force to begin with and practiced the most inhumane shit there.
Don't claim innocence when you have done nothing but terrorize people and take their rightful lands.
Also, stop being a coward and reply without shutting others up.
It's a free world we live in rn.

**Comment by Bukati** [comment]
You should be banned from GitHub altogether for spamming. There is no place for politics and propaganda here.

**Comment by AbdoZDGaia** [comment]
> You should be banned from GitHub altogether for spamming. There is no place for politics and propaganda here.

Only if you're willing to get banned for using the Israeli logo in fnm.
That's politics and propoganda, no?

**Comment by AbdoZDGaia** [comment]
https://github.com/Schniz/fnm/issues/1069#issue-1986367662

**Is this not politics and propoganda???**
https://raw.githubusercontent.com/Schniz/fnm/master/docs/fnm.svg

**Comment by ljharb** [comment]
No, it's not, it's a religious symbol that's not necessarily associated with any particular country.

If you're assuming all uses of the religious symbol are associated with a specific country whose actions you don't like, then you may want to re-evaluate whether it's the country, or the religion, you have a problem with.

**Comment by AbdoZDGaia** [comment]
> No, it's not, it's a religious symbol that's not necessarily associated with any particular country.
> 
> If you're assuming all uses of the religious symbol are associated with a specific country whose actions you don't like, then you may want to re-evaluate whether it's the country, or the religion, you have a problem with.

This reply should be enough to answer your question.
https://github.com/Schniz/fnm/issues/1069#issuecomment-1805918034
