### ISSUE TITLE
Usage in a monorepo

### ISSUE THREAD

**Issue by quantizor** [Schniz/fnm#1079]
I have a yarn workspaces setup like:

```
/package.json
/.nvmrc
/packages
  /project1
    /package.json
  /project2
    /package.json
```

`fnm` works fine at the root but if I try to invoke `fnm use` in one of the deeper workspace folders it errors with:

> error: Can't find version in dotfiles. Please provide a version manually to the command.

Can the tool be made to traverse the file tree upwards and look for an applicable file, or is there some package.json flag I can set etc?

**Comment by alexeyten** [comment]
https://github.com/Schniz/fnm/blob/master/docs/commands.md#fnm-use

See  --version-file-strategy

**Comment by quantizor** [comment]
Ahhh thank you!

**Comment by rdsedmundo** [comment]
It'd be nice if there was a config file that could be set in the monorepo/shell level so this would be read and used by default always.

I mean, once I'm switching between folders it's not convenient to have to recall myself that I need to do `--version-file-strategy recursive`, I'd like that to work automatically when I do `node --version`. 

@Schniz

**Comment by q2-kkendall** [comment]
This seems to have a regression -- #1464.
