### ISSUE TITLE
fnm: unknown option `--multi' logged on every new shell opened

### ISSUE THREAD

**Issue by nikitavoloboev** [Schniz/fnm#108]
As says in readme I added  `eval "`fnm env --multi`"` to my .zshrc

But I get this error every time I open new shell:

```
fnm: unknown option `--multi'.
Usage: fnm env [OPTION]...
Try `fnm env --help' or `fnm --help' for more information.
```

How can I solve this?

**Comment by johnletey** [comment]
@nikitavoloboev That’s a fairly new feature I believe ... what version do you currently have?

**Comment by nikitavoloboev** [comment]
1.0.0

**Comment by johnletey** [comment]
Try updating

**Comment by nikitavoloboev** [comment]
I removed that line for now as I believe I don't need it.

`brew install Schniz/tap/fnm` gets me 1.0.0. I'll try manual install.

**Comment by johnletey** [comment]
Try rm ~/.fnm/fnm && brew install Schniz/tap/fnm

**Comment by nikitavoloboev** [comment]
```
❯ rm ~/.fnm/fnm && brew install Schniz/tap/fnm
rm: /Users/nikivi/.fnm/fnm: No such file or directory
```

**Comment by johnletey** [comment]
Is it installed?

**Comment by nikitavoloboev** [comment]
yes with brew so

`❯ which fnm
/usr/local/bin/fnm`

**Comment by nikitavoloboev** [comment]
brew's package is outdated

**Comment by Schniz** [comment]
Hmmm, weird. Can you uninstall using Homebrew and reinstall using `brew install Schniz/tap/fnm`?
I have never published fnm v1.0.0 using brew ([here's the commit history](https://github.com/Schniz/homebrew-tap/commits/master/Formula/fnm.rb)) so maybe it wasn't installed using my formula?

Sorry for the problems though, I'd be happy to help in any way possible

**Comment by nikitavoloboev** [comment]
`eval "`fnm env --multi`"` command works too now

**Comment by Schniz** [comment]
Thanks! happy to help in any way possible 😄 👏
