### ISSUE TITLE
Not able to import globally installed packages

### ISSUE THREAD

**Issue by sagarpanchal** [Schniz/fnm#1098]
**Am I missing something?**

<img width="857" alt="image" src="https://github.com/Schniz/fnm/assets/6555461/d9ea54ae-ffc8-45fd-b573-10a07aa53788">
<img width="723" alt="image" src="https://github.com/Schniz/fnm/assets/6555461/fd6741db-b447-4774-9e07-140c98a86d1f">

**Comment by sagarpanchal** [comment]
Set node path and it started working.

```
export NODE_PATH="$(npm root ---quiet --global)"
```

**Comment by ljharb** [comment]
Be aware NODE_PATH is deprecated, a bad practice, and won't work for ESM - if you require/import something, it's a dependency, and it must be installed locally.

**Comment by sagarpanchal** [comment]
@ljharb 
Thanks. I am going to create a new project to run REPL.

[NODE_PATH was originally created to support loading modules from varying paths before the current module resolution algorithm was defined.](https://nodejs.org/api/modules.html#:~:text=NODE_PATH%20was%20originally%20created)

[NODE_PATH is still supported, but is less necessary now that the Node.js ecosystem has settled on a convention for locating dependent modules. Sometimes deployments that rely on NODE_PATH show surprising behavior when people are unaware that NODE_PATH must be set. Sometimes a module's dependencies change, causing a different version (or even a different module) to be loaded as the NODE_PATH is searched.](https://nodejs.org/api/modules.html#all-together:~:text=NODE_PATH%20is%20still%20supported%2C%20but%20is%20less%20necessary)

**Comment by ljharb** [comment]
There's no valid use case to use NODE_PATH at this point.
