### ISSUE TITLE
fnm use system , i got "command not found: node"

### ISSUE THREAD

**Issue by masterjiyuhang** [Schniz/fnm#1107]
When i use command `fnm use system`, node is not found.
I found related questions #847. 
I'm not sure if I don't have this configuration ，FNM_MUTLISHELL_PATH。
I want to know how to set this configuration to make my system effective.

<img width="725" alt="image" src="https://github.com/Schniz/fnm/assets/52491970/0fc8bc70-0f38-4a93-8336-6e0e74d2ba67">
<img width="1058" alt="image" src="https://github.com/Schniz/fnm/assets/52491970/2dddaa3a-a61b-47d7-a252-6fea1844b87c">

**Comment by Schniz** [comment]
when you use `fnm use system` you bypass fnm. that means that node is not installed on your machine. we use the `/dev/null/installation` as a hack to make sure we link to nothing so the matches of `node` in your `$PATH` will try `/dev/null/installation/node` which is obviously missing, and then look for the next entires in `$PATH`.

so tldr, you probably don't have node installed in your system outside of fnm. that's cool, fnm is more than enough! so just don't use `fnm use system` if that's the case.

**Comment by masterjiyuhang** [comment]
Thank you very much, solved my confusion.
