### ISSUE TITLE
How can I set an installed version to system version?

### ISSUE THREAD

**Issue by fadeaway1680** [Schniz/fnm#1108]
### How did you install `fnm`?
- Manually using a release binary (Windows)

### What happened?
1. I didn't have any node versions before. 
2. After installing `fnm` and installing some versions of node, I run `node -v` and it works.
3. But when I run `fnm use system`, `node -v` didn't works. 

It seems like it's because I didn't install node beside `fnm`. Should I have to?

### What did you expect to happen?
- I was wondering if it's possible to set the node version that installed by `fnm` to the `system`node version.
- Better through the command line.

**Comment by Schniz** [comment]
`fnm use system` is not "an fnm-installed version as the system version", but it is basically "bypass fnm so I use whatever is already installed on the system". I personally never use it. The "main installation" is the default fnm version: `fnm default 20` for instance.
