### ISSUE TITLE
Fatal error: exception (Failure "Unsupported level: info")

### ISSUE THREAD

**Issue by ivanoats** [Schniz/fnm#111]
I'm getting `Fatal error: exception (Failure "Unsupported level: info")`

Mac OS 10.14.5
Zsh 5.3

Maybe related to this recent change? https://github.com/Schniz/fnm/pull/104

**Comment by ivanoats** [comment]
I am not getting this error anymore. I noticed I was loading fnm twice in my .zshrc. Not sure how that's related but I a going to close this issue.

**Comment by Schniz** [comment]
Hey @ivanoats, sorry that it happened!
Did it also loaded an older version of fnm? Do you use the homebrew installation?
