### ISSUE TITLE
Support lts/<name> style declarations

### ISSUE THREAD

**Issue by blimmer** [Schniz/fnm#112]
I would love to switch over to this from `nvm`, but my org uses the LTS version strings with `nvm`: https://github.com/nvm-sh/nvm#long-term-support

e.g. our `.nvmrc` files look like this:

```console
lts/dubnium
```

Would it be possible to add support for those version declaration styles?

**Comment by Schniz** [comment]
We can parse them to make it installable, and it won't be that hard, but I think that in order to `use` them, we need to set up aliases too if the version doesn't look like `v{NUM}-{NUM}-{NUM}`. What do you think?

**Comment by Schniz** [comment]
This also means that `fnm install latest` will create an alias named `latest` that will link to the version you have just installed

**Comment by ljharb** [comment]
Don’t forget that `lts/*` also always points to the latest lts.

**Comment by ljharb** [comment]
You don’t have to make changes for “latest” either; i assume aliases aren’t currently allowed to have a slash in them - that’s how nvm was able to use the `lts/` namespace without disrupting anybody.

**Comment by Schniz** [comment]
> Don’t forget that `lts/*` also always points to the latest lts.

That's not a problem when installing: `lts/dubnium` maps to `latest-dubnium` in https://npmjs.org/dist. Would anyone who try to `use lts/dubinum` assume that it's the latest _available upstream_ or _available locally_? (I would assume the latter)

**Comment by Schniz** [comment]
which makes it work like an alias

**Comment by ljharb** [comment]
nvm updates the local lts aliases on every remote contact; however i do have an open issue because people do expect it to apply locally, so I’m not sure how to resolve that.

**Comment by blimmer** [comment]
My experience using `nvm` is that every once and a while it'll consider my local `lts` version too out of date and ask me to install a newer one. I don't know what the pattern or implementation details are, necessarily, of when they prompt me.

**Comment by ljharb** [comment]
@blimmer any contact with nodejs.org updates nvm's LTS aliases; ie, any `nvm ls-remote` or `nvm install`. However, nvm doesn't prompt to update anything at all, so maybe you're using nvm-windows?

**Comment by blimmer** [comment]
Huh, nope I'm on macos. For the refresh, that makes sense, it is probably when I install a new node version. Not sure about the prompt, suddenly when I `nvm use` at some point it tells me that I don't have `lts/dubnium` installed, but I do have an older version (e.g. 10.13.0 installed).

Either way, the usage of `lts/dubnium` has been really useful for us since it allows some drift within the lts range. If there's a project that can't allow drift, they'll specify a more specific version number.

**Comment by blimmer** [comment]
Ah, yep, that's definitely the behavior. I just did a `nvm ls-remote`

```console
<truncated output>
       v10.13.0   (LTS: Dubnium)
       v10.14.0   (LTS: Dubnium)
       v10.14.1   (LTS: Dubnium)
       v10.14.2   (LTS: Dubnium)
       v10.15.0   (LTS: Dubnium)
       v10.15.1   (LTS: Dubnium)
       v10.15.2   (LTS: Dubnium)
->     v10.15.3   (LTS: Dubnium)
       v10.16.0   (Latest LTS: Dubnium)
<truncated output>
```

and now when I `nvm use`, I get this:

```console
nvm use
Found '/Users/blimmer/code/browser-extension-gateway-service/.nvmrc' with version <lts/dubnium>
N/A: version "lts/dubnium -> N/A" is not yet installed.

You need to run "nvm install lts/dubnium" to install it before using it.
```

**Comment by pavelloz** [comment]
^ I think thats where planned [`use --install`](https://github.com/Schniz/fnm#future-plans) 

`use` -> use from local
`use --install` -> use from local, install if not found, use local

I personally like docker approach - which is: use local, install if not found.
Since removal is very easy, this might be also a sensible approach in this case.

**Comment by ljharb** [comment]
@pavelloz nvm already has that behavior - `nvm install` installs iff missing, and then uses.

**Comment by Schniz** [comment]
On shoulders of giants we stand :)
