### ISSUE TITLE
Can't infer shell in shim call in v1.37.0

### ISSUE THREAD

**Issue by sky96111** [Schniz/fnm#1153]
``fnm env --use-on-cd | Out-String | Invoke-Expression`` and ``fnm completions | Out-String | Invoke-Expression`` shows
````text
❯ fnm env --use-on-cd | Out-String | Invoke-Expression
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
* cmd
Invoke-Expression: Cannot bind argument to parameter 'Command' because it is an empty string.
````

environment:
fnm version: v1.37.0
OS: Windows 11 x86_64
OS Version: 23H2 22631.3672
Shell: PowerShell 7.4.2

**Comment by Schniz** [comment]
please re-run `fnm env --use-on-cd` with the following env var: `RUST_LOG=fnm=debug` and post the output 🙏

**Comment by sky96111** [comment]
sure!
````shell
~
❯ $env:RUST_LOG="fnm=debug"

~
❯ fnm env --use-on-cd
[2024-05-30T14:18:21Z DEBUG fnm::shell::infer] binary is not a supported shell: "fnm"
[2024-05-30T14:18:21Z DEBUG fnm::shell::infer] binary is not a supported shell: "fnm"
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
* cmd
````
Maybe it is a problem caused by shim? I installed fnm by scoop

**Comment by sky96111** [comment]
Confirm absolute path call without shim works.
And [1.35.1](https://github.com/Schniz/fnm/releases/tag/v1.35.1) works with shim

**Comment by Schniz** [comment]
what "shim"?

**Comment by Schniz** [comment]
I'm not a Windows user, can you please explain the terms you use? 😅

**Comment by sky96111** [comment]
https://github.com/ScoopInstaller/Shim
shim is a small wrapper in scoop installation. it avoids the need to add the program bin directory to the system path.

In scoop, fnm in path is shim wrapper which actually call fnm installed in ``C:\Users\sky96111\scoop\apps\fnm\current\fnm.exe``
````
~
❯ where.exe fnm
C:\Users\sky96111\scoop\shims\fnm.exe

~
❯ cat C:\Users\sky96111\scoop\shims\fnm.shim
path = "C:\Users\sky96111\scoop\apps\fnm\current\fnm.exe"
````

**Comment by bjohnso5** [comment]
you can work around this issue by using the following setup in your powershell profile:
```powershell
fnm env --use-on-cd --shell power-shell | Out-String | Invoke-Expression
```

**Comment by sky96111** [comment]
Yes, this fixes the bug. 
While since 1.36.0 doesn't have this problem, I think it might be a regression error.

> you can work around this issue by using the following setup in your powershell profile:
> 
> ```powershell
> fnm env --use-on-cd --shell power-shell | Out-String | Invoke-Expression
> ```

**Comment by sky96111** [comment]
I think it might be caused by https://github.com/Schniz/fnm/commit/a1afe8436afb29960b71e14e221441398f6a48ca#diff-c42cf7f1bff071dab6b57a73c8718054d07376e6f8a417621a85a2d297f12439

**Comment by alexewsv** [comment]
same issue

**Comment by Schniz** [comment]
I’ll try to revert the changes for this module asap

**Comment by Schniz** [comment]
Feel free to debug this though instead of reverting to an older dependency version, I have no windows machine to test it on right now

**Comment by alexewsv** [comment]
> you can work around this issue by using the following setup in your powershell profile:
> 
> ```powershell
> fnm env --use-on-cd --shell power-shell | Out-String | Invoke-Expression
> ```

thank you, it works

**Comment by ekarious** [comment]
Got the same problem.
I use `cmder` mostly so here the workaround for the `fnm_init.cmd` file.
```
:: %CMDER_ROOT%\bin\fnm_init.cmd
@echo off
FOR /f "tokens=*" %%z IN ('fnm env --use-on-cd --shell cmd') DO CALL %%z
```
Just need to specify the shell.

**Comment by Schniz** [comment]
specifying a shell is always a good idea, it also boots up faster <picture data-single-emoji=":sweat-smile-tg:" title=":sweat-smile-tg:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/sweat-smile-tg/0808cf3034a0337a.png" alt=":sweat-smile-tg:" align="absmiddle"></picture>
