### ISSUE TITLE
`fnm default` - unknown command

### ISSUE THREAD

**Issue by pavelloz** [Schniz/fnm#117]
Hey, pretty self explanatory issue :)

```

nearme-documentation|master ⇒ fnm --version
1.9.1

nearme-documentation|master ⇒ fnm default 12.5.0
fnm: unknown command `default'.
Usage: fnm COMMAND ...
Try `fnm --help' for more information.
```

It might be because i have just old version, but i didnt find any quick/simple way of upgrading in readme - so maybe this issue will evolve into: "Provide onliner to update package" (as this might be the root cause :) )

**Comment by pavelloz** [comment]
It was old version issue.

**Comment by Schniz** [comment]
Thanks for updating!
