### ISSUE TITLE
Too many issues on Windows - NVM for Windows is still beter

### ISSUE THREAD

**Issue by Remzi1993** [Schniz/fnm#1175]
I'm sorry but there are too many issues on Windows to consider this a successor to NVM for Windows.

First of all to activate and configure it on Windows 11 and the Terminal with PowerShell 7 was too many manual steps.
Second the env variable was not automatically added so my IDE didn't recognize Node.js.

Uninstalling this and going back to NVM for Windows.

**Comment by Schniz** [comment]
Feel free to open PRs that fix the issues

Thanks for your time
