### ISSUE TITLE
Is it nornal for it to revert back to the default node version when you close the terminal?

### ISSUE THREAD

**Issue by trymeouteh** [Schniz/fnm#1197]
Is it nornal for it to revert back to the default node version when you close the terminal? Or did not do something wrong when installing fnm?

For example if I installed node 19 and 20 and node 20 is the default node version. I Change the node version to 19 and then close the terminal and open the terminal again, the node version is back to version 20, not version 19.

**Comment by Schniz** [comment]
Yes, each shell session has its own node version attached. You can use `--use-on-cd` to automatically switch versions based on a project
