### ISSUE TITLE
fnm doesn't swap out the correct version of node

### ISSUE THREAD

**Issue by wgottschalk** [Schniz/fnm#12]
I'm a little confused by the result. I'm expecting for node 8 to show up but it doesn't look like that's the case.
```
C02V51K4HTD7:client william.gottschalk$ fnm --version
1.0.0

C02V51K4HTD7:client william.gottschalk$ fnm install 8.11.2
Looking for node v8.11.2 for darwin x64
Downloading https://nodejs.org/dist/v8.11.2/node-v8.11.2-darwin-x64.tar.gz to /Users/william.gottschalk/.fnm/downloads/v8.11.2.tar.gz
Extracting /Users/william.gottschalk/.fnm/downloads/v8.11.2.tar.gz to /Users/william.gottschalk/.fnm/node-versions/v8.11.2

C02V51K4HTD7:client william.gottschalk$ fnm use 8.11.2
Linking /Users/william.gottschalk/.fnm/current to /Users/william.gottschalk/.fnm/node-versions/v8.11.2/installation
Using v8.11.2

C02V51K4HTD7:client william.gottschalk$ node -v
v11.2.0

C02V51K4HTD7:client william.gottschalk$ which node
/Users/william.gottschalk/.fnm/current/bin/node
```
I have nvm installed on my machine but I'm not executing any of the start up scripts to activate it.

**Comment by Schniz** [comment]
does `/Users/william.gottschalk/.fnm/current/bin/node -v` prints `v11.2.0` as well?

I know that for some reason `nvm` hijacks the PATH when `node` is being run

**Comment by ljharb** [comment]
`nvm`'s entire mode of operation is to "hijack the PATH", but it does not do it when node is being run, it only does it when you run `nvm use` (or when you source `nvm.sh` with a `default` set). If `which node` doesn't return an nvm-managed node, then nvm is not part of the equation.

**Comment by Schniz** [comment]
> but it does not do it when node is being run, it only does it when you run `nvm use`

Sorry @ljharb! didn't meant to say something false. For some (weird) reason, I had a problem locally (which I can't reproduce now), that although `nvm` wasn't on my `$PATH`, the node binary was still `nvm`'s.

@wgottschalk, can you please tell me what is the output of `~/.fnm/current/bin/node -v`?

**Comment by wgottschalk** [comment]
Yeah. That gets me the correct output
![image](https://user-images.githubusercontent.com/11728959/51861348-cf7bc000-22f0-11e9-9d81-cbad6569dfba.png)

**Comment by wgottschalk** [comment]
So as a follow up, I ran `rm -rf ~/.nvm` and `source ~/.bash_profile` to remove nvm and restart me terminal. Everything works now. Also a benefit that I noticed is that I always get the correct version of node when I open a separate tab.

Great tool!
