### ISSUE TITLE
`uninstall` bug

### ISSUE THREAD

**Issue by pavelloz** [Schniz/fnm#122]
For some reason I can't uninstall some of the node versions I have on my machine.

```
marketplace-nearme-example|master⚡ ⇒ fnm ls
The following versions are installed:
* system
* v10.15.3
* v12.2.0
* v12.3.0
* v12.5.0
* v12.6.0 (default)
marketplace-nearme-example|master⚡ ⇒ fnm uninstall v10.15.3
fnm: internal error, uncaught exception:
     Unix.Unix_error(Unix.ENOENT, "stat", "/Users/pavel/.fnm/node-versions/v10.15.3/installation/lib/node_modules/serverless/node_modules/.bin/flat")
marketplace-nearme-example|master⚡ ⇒ fnm ls
The following versions are installed:
* system
* v10.15.3
* v12.2.0
* v12.3.0
* v12.5.0
* v12.6.0 (default)
```

Fail with globally installed package reference:
```
marketplace-nearme-example|master⚡ ⇒ fnm uninstall v12.2.0
fnm: internal error, uncaught exception:
     Unix.Unix_error(Unix.ENOENT, "stat", "/Users/pavel/.fnm/node-versions/v12.2.0/installation/lib/node_modules/@platform-os/marketplace-kit/node_modules/.bin/jest-runtime")
```

Another fail with global package mentioned in the error:
```
marketplace-nearme-example|master⚡ ⇒ fnm uninstall v12.5.0
fnm: internal error, uncaught exception:
     Unix.Unix_error(Unix.ENOENT, "stat", "/Users/pavel/.fnm/node-versions/v12.5.0/installation/lib/node_modules/babel-eslint/node_modules/.bin/jsesc")
    
````

Success:
```
marketplace-nearme-example|master⚡ ⇒ fnm uninstall v12.3.0 
Node version v12.3.0 has correctly been removed.
marketplace-nearme-example|master⚡ ⇒ fnm ls
The following versions are installed:
* system
* v10.15.3
* v12.2.0
* v12.5.0
* v12.6.0 (default)
```

Because of the error I received while trying to uninstall `12.2.0` i suspect that it might be caused by installed global packages or some symlinks not allowing to delete the directory (just guessing).

---

Env info:

* Node: v12.6.0
* System: Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64
* fnm: 1.12.0

**Comment by jebeck** [comment]
I don't think this is actually fixed. Have the latest version (1.14.0) and still can't uninstall some of my node versions:
```
>> fnm --version
1.14.0
>> fnm uninstall v10.16.1
fnm: internal error, uncaught exception:
     Unix.Unix_error(Unix.ENOENT, "stat", "/Users/janabeck/.fnm/node-versions/v10.16.1/installation/lib/node_modules/npm-check/node_modules/.bin/babylon")
```

Also a globally installed package mentioned in the error trace.

**Comment by Schniz** [comment]
You’re right. I’ll check it when I have some time. Sorry. 
IIRC, @tatchi implemented uninstalling versions with recursive file removal. Anyway, this is something worth checking out. I’d be glad to get some help debugging it if you’re into that!

**Comment by jebeck** [comment]
Thanks for reopening! I can certainly help test new releases if you need it, but I'm not familiar with Reason at all so probably not too helpful re: bug-hunting 😞
