### ISSUE TITLE
Install script should check for ~/.bash_profile and ~/.bash_login on macOS

### ISSUE THREAD

**Issue by aramgre** [Schniz/fnm#124]
The install script adds Bash shell initialization to `~/.profile`, but on macOS Bash will not load the `~/.profile` if `~/.bash_profile` or `~/.bash_login` is present. Ideally should check for each config file in order of precedence:

https://stackoverflow.com/questions/18773051/how-to-make-os-x-to-read-bash-profile-not-profile-file

**Comment by SpectralKH** [comment]
Had this issue as well, then I reinstalled and for some reason it added fnm to `.bash_profile` that time (though it broke the whole file because it added `#fmt` to a line that already had code in it). Weird

**Comment by Schniz** [comment]
I think about throwing an error when installing on OSX using the installation script since we have Homebrew support now. WDYT?

**Comment by aramgre** [comment]
That seems fine I guess? I'm new to fnm and thought the install script was the preferred method, since Homebrew support was not "official" yet according to the README. 

FWIW I think Homebrew will expand `shell_profile` in https://github.com/Schniz/homebrew-tap/blob/master/Formula/fnm.rb#L31 to `.bash_profile`: https://github.com/Homebrew/brew/blob/7b67ac5e3c888080ab6c85052c3f4937f52108da/Library/Homebrew/utils/shell.rb#L68

So it would probably also be OK to just use `.bash_profile` in the install script if you wanted to continue to support it.

**Comment by SgtPooki** [comment]
I am installing on a fresh macbook and getting the `Could not infer shell type. Please set up manually.` message.

In the install script, the [`$CURRENT_SHELL` is set to `$(basename $SHELL)` which is `false` for me.](https://github.com/Schniz/fnm/blame/master/.ci/install.sh#L80)
