### ISSUE TITLE
Setting up npm?

### ISSUE THREAD

**Issue by idkjs** [Schniz/fnm#127]
I have node installed through fnm but i keep getting this message:

 │       New minor version of npm available! 6.7.0 → 6.10.1       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.10.1   │
   │               Run npm install -g npm to update!

<img width="526" alt="Screen Shot 2019-07-13 at 10 52 13 AM" src="https://user-images.githubusercontent.com/2370391/61169349-88128480-a55c-11e9-8edf-f1ba6c264240.png">

What is the setup for getting these setting to read from the same place?
`npm install -g npm` doesnt seem to update npm with fnm.

Thank you.

**Comment by Schniz** [comment]
Hey! this is weird - I constantly upgrade `npm`. One thing worth noting is that every Node version comes with a different `npm` version, so you might need to upgrade npm lots of times 😄 

Can you show what does `which npm` outputs?

**Comment by idkjs** [comment]
```
Last login: Sun Jul 14 07:37:59 on ttys004
➜  $ which npm
/var/folders/dz/xzttny_14gs2lgxcvl5lm5680000gn/T/fnm-shell-1415625/bin/npm
➜  $
```

**Comment by Schniz** [comment]
Oh, okay. and `npm install -g npm@latest` doesn't work? What does it do?

**Comment by idkjs** [comment]
maybe it has something to do with `npm-global` setting...

```
➜  $ npm -g ls npm
/Users/prisc_000/.npm-global/lib
├─┬ @aws-amplify/cli@1.6.9
│ ├─┬ amplify-category-function@1.4.5
│ │ └─┬ grunt-aws-lambda@0.13.0
│ │   └── npm@2.15.12
│ └─┬ amplify-codegen@1.5.1
│   └─┬ aws-appsync-codegen@0.17.5
│     └── npm@6.9.0
└── npm@6.10.1
```

**Comment by Schniz** [comment]
Oh, interesting. Maybe you can append the following to your `.{ba,z}shrc` file after the call to `fnm env`:

```bash
export PATH=$HOME/.npm-global/bin:$PATH
```

I don't know what is `~/.npm-global`, but maybe it'll work? The downside is that you share installations across node versions which can cause troubles.

Maybe you can also ignore the [global (prefix) directory config](https://docs.npmjs.com/misc/config#prefix) when you update npm itself, and remove it from the `.npm-global` direcotry

**Comment by idkjs** [comment]
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by Schniz** [comment]
Yeah, reasoable 😄 
with fnm it is not a problem anymore 😄

**Comment by idkjs** [comment]
Cant get rid of it though. Keeps reconstruction the `.npm-global` folder even after i delete it.

```
➜  read-write-cache-test [master*]npm -g ls npm
/Users/prisc_000/.npm-global/lib
└── (empty)

➜  read-write-cache-test [master*]reload
➜  read-write-cache-test [master*]npm -v
6.7.0
➜  read-write-cache-test [master*]npm uninstall -g npm
up to date in 0.047s
➜  read-write-cache-test [master*]which npm
/var/folders/dz/xzttny_14gs2lgxcvl5lm5680000gn/T/fnm-shell-9016424/bin/npm
➜  read-write-cache-test [master*]npm -v
6.7.0
➜  read-write-cache-test [master*]npm install -g npm@latest
/Users/prisc_000/.npm-global/bin/npm -> /Users/prisc_000/.npm-global/lib/node_modules/npm/bin/npm-cli.js
/Users/prisc_000/.npm-global/bin/npx -> /Users/prisc_000/.npm-global/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.10.1
added 433 packages from 823 contributors in 10.326s
➜  read-write-cache-test [master*]npm -g ls npm
/Users/prisc_000/.npm-global/lib
└── npm@6.10.1

➜  read-write-cache-test [master*]
```

**Comment by Schniz** [comment]
Can you try deleting the `prefix` config?

```
npm config delete prefix
```

**Comment by idkjs** [comment]
magic words. forgot about that. I deleted the .nvmrc and figured that would do it but didnt.

```
➜  read-write-cache-test [master*]npm config delete prefix
➜  read-write-cache-test [master*]npm -g ls npm
/Users/prisc_000/.fnm/node-versions/v11.14.0/installation/lib
└── npm@6.7.0

➜  read-write-cache-test [master*]
```

**Comment by idkjs** [comment]
Thanks for the guidance, brother

```
  read-write-cache-test [master*]npm install -g npm@latest
/Users/prisc_000/.fnm/node-versions/v11.14.0/installation/bin/npm -> /Users/prisc_000/.fnm/node-versions/v11.14.0/installation/lib/node_modules/npm/bin/npm-cli.js
/Users/prisc_000/.fnm/node-versions/v11.14.0/installation/bin/npx -> /Users/prisc_000/.fnm/node-versions/v11.14.0/installation/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.10.1
added 21 packages from 15 contributors, removed 14 packages and updated 37 packages in 13.269s
➜  read-write-cache-test [master*]npm -g ls npm
/Users/prisc_000/.fnm/node-versions/v11.14.0/installation/lib
└── npm@6.10.1

➜  read-write-cache-test [master*]
```

**Comment by Schniz** [comment]
Happy to help! 😸

**Comment by Schniz** [comment]
And thanks for using fnm 😎

**Comment by ljharb** [comment]
Note that that prefix shouldn’t exist with nvm either; prefix should never be set.

**Comment by idkjs** [comment]
@ljharb why is that?

**Comment by ljharb** [comment]
It changes the location of `npm root -g`, which allows you to share global modules across node versions, which should never be done because installed node modules aren’t reliably compatible across node versions (the act of installing, on a given node version, is required)

**Comment by idkjs** [comment]
Thank you for sharing the knowledge @ljharb!
