### ISSUE TITLE
hello   , god blessing you  ,   I  have a  question ,

### ISSUE THREAD

**Issue by Super1Windcloud** [Schniz/fnm#1270]
#  C:\Users\superuse\AppData\Local\fnm_multishells , it's  all symbolic  link ,  and I could open  the  every folder for  corresponding Node version,  but  I  didn't download  so many  Node version ,  this is why ?      
![image](https://github.com/user-attachments/assets/46c6d41f-f1cc-4b38-a2dd-e06073c49c9e)

**Comment by Schniz** [comment]
multishells are the mechanism of how we can support a different Node.js version per shell session (so every Terminal tab you run can run a different version). They're practically free in terms of storage and they're an implementation detail.

See this comment for more information: https://github.com/Schniz/fnm/issues/1157#issuecomment-2143788670

also this issue for cleaning them up #696
