### ISSUE TITLE
What does the fnm_multishells file do?

### ISSUE THREAD

**Issue by MickeyCho630** [Schniz/fnm#1276]
A new folder is generated in fnm_multishells after each use. Is the folder directly in the C disk, or is it a shortcut generated after each run?

**Comment by Schniz** [comment]
yes
i explained it many times in the issues, please search it here <picture data-single-emoji=":meow_pensive-pray:" title=":meow_pensive-pray:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/meow_pensive-pray/736c0708413e0add.png" alt=":meow_pensive-pray:" align="absmiddle"></picture> 
the tl;dr that it's a symlink created for "the current shell session"
