### ISSUE TITLE
`fnm use latest` does not detect the currently-installed version correctly

### ISSUE THREAD

**Issue by Calinou** [Schniz/fnm#128]
**OS:** Fedora 30
**Shell:** zsh 5.7.1
**fnm version:** fnm 1.12.0

After installing the latest Node.js version using `fnm install 12.6.0` and switching to the system version using `fnm use system`, attempting to switch  back to the latest version will result in fnm asking to install 12.6.0 indefinitely:

```text
❯ fnm use latest
The following version is not installed: latest
Do you want to install it? [y/n] y
Version v12.6.0 is already installed.
The following version is not installed: latest
Do you want to install it? [y/n]
```

The program will only exit after answering "n". Thankfully, `fnm use 12.6.0` works as expected.

**Comment by Schniz** [comment]
Oh yeah, th is is true, and I'm sorry about that!

I think I have a good way to fix that. It will also fix `latest-dubnium` and `lts/dubnium`, so I hope I'd get it out soon!
