### ISSUE TITLE
How to ignore nvmrc files

### ISSUE THREAD

**Issue by lvzhenbo** [Schniz/fnm#1300]
I just want to manually switch node versions instead of automatically switching based on the content of nvmrc. What should I do

**Comment by lvzhenbo** [comment]
No, I just want to use fnm as a node multi-version switching tool, and want to manually control the node version I'm using myself

**Comment by Schniz** [comment]
Ahh. So just omit —use-on-cd from initialization. It’s a feature.

**Comment by lvzhenbo** [comment]
Ok, that solved my problem, thanks for the answer!
