### ISSUE TITLE
Silence "Can't find version in dotfiles" when using --resolve-engines

### ISSUE THREAD

**Issue by tekumara** [Schniz/fnm#1308]
Given `eval "$(fnm env --use-on-cd --resolve-engines)"` when I switch to a directory that has a `package.json` but no node version specified I get:
```
error: Can't find version in dotfiles. Please provide a version manually to the command.
```

Could an option be added to disable this? Otherwise I have to specify a node version in every directory/repo.

**Comment by sammcj** [comment]
Came to log this as a bug as well.

I updated fnm and now every time I open a shell I get this error, it's made more annoying by the error not stating which application it's coming from.

<img width="3840" alt="image" src="https://github.com/user-attachments/assets/6c176429-1acc-4c7f-b4eb-58f687bb6163">

**Comment by Schniz** [comment]
Will check this tomorrow morning. Sorry about that.

**Comment by carlosflorencio** [comment]
Thanks @Schniz!
