### ISSUE TITLE
macOS Catalina - brew install Schniz/tap/fnm fails

### ISSUE THREAD

**Issue by AndrewEQ** [Schniz/fnm#135]
The error I get is:
```
Error: No such file or directory @ rb_sysopen - /Users/andrewq/.bash_profile
```

**Comment by Schniz** [comment]
I don't have macOS Catalina. I wonder if we should change the following line:
https://github.com/Schniz/homebrew-tap/blob/master/Formula/fnm.rb#L21
into a method that returns `false` if `shell_profile` doesn't exist. Which shell do you currently use? Was it Bash on a branch new machine?

**Comment by AndrewEQ** [comment]
Yeah, sounds like you gotta detect which shell is in use, I'm just using the new default shell of Catalina's terminal which is zsh on a brand new machine.

**Comment by Schniz** [comment]
Alright. very odd behavior but it can be fixed 😄

**Comment by cwahlfeldt** [comment]
This is also happening to me on mojave `10.14.6`. I have the catalina profile and i was gonna upgrade in the future... so maybe its related.

**Comment by myktra** [comment]
I'm getting this on a *brand new* Mojave machine as well, as my `.bash_profile` file doesn't exist. A workaround that seemed to help, FWIW:

```sh
brew remove Schniz/tap/fnm
touch ~/.bash_profile
brew install  Schniz/tap/fnm
```

You'll see what seems to be an innocuous *Skipped the installation of fnm to ~/.bash_profile because I found `# fnm`* message.

**Comment by Schniz** [comment]
@myktra @cwahlfeldt @AndrewEQ 
Can you try the following and let me know if it works?

```
cd $(brew --repository Schniz/tap)
git fetch origin
git checkout fix-missing-file

brew install Schniz/tap/fnm
```

It should test the following PR: https://github.com/Schniz/homebrew-tap/pull/2

**Comment by jrock2004** [comment]
I also just got this. I am on catalina as well

**Comment by Schniz** [comment]
The Homebrew formula doesn't alter the profile for you anymore, so I'm closing this.
