### ISSUE TITLE
What is the point of this tool if I have to paste a bunch of boilerplate into PowerShell every time!

### ISSUE THREAD

**Issue by babakfp** [Schniz/fnm#1358]
I can't use this:

```
fnm use v18.20.5
```

Because every damn time I need to do:

```
fnm env --use-on-cd --shell powershell | Out-String | Invoke-Expression
```

This is stupid.

**Comment by shirshak55** [comment]
Edit (Or create if file doesn't exist) this file  %userprofile%\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1 

and add that command fnm env --use-on-cd --shell powershell | Out-String | Invoke-Expression

Once you do it you don't have to execute command every **damn** time.

Btw it is mentioned in docs.
