### ISSUE TITLE
Unix.Unix_error

### ISSUE THREAD

**Issue by sant123** [Schniz/fnm#140]
Hi, always when I try to uninstall a node version I get the following message:

![image](https://user-images.githubusercontent.com/7959437/65290890-aaa1ba80-db16-11e9-9cb1-9857a30069aa.png)

Any idea what's going on here?

Thanks for this cool and useful version manager.

**Comment by Schniz** [comment]
I will release a new version today that’ll hopefully fix that issue. Sorry!

**Comment by sant123** [comment]
Glad to hear that, thank you!

**Comment by Schniz** [comment]
Hi, I have released `v1.15.0` (0ec2da0)

can you please try it again? :)

**Comment by sant123** [comment]
![image](https://user-images.githubusercontent.com/7959437/65433162-23886700-dde2-11e9-8d98-7d4a3b87fb42.png)

It works really good, thanks a lot @Schniz !!!

**Comment by Schniz** [comment]
No problems :) thanks for reporting!
