### ISSUE TITLE
zsh: parse error near `()' with --use-on-cd

### ISSUE THREAD

**Issue by CWSpear** [Schniz/fnm#145]
If I try to use the `--use-on-cd` flag (with or without `--multi` flag), I get an error that it doesn't like something in the syntax:

```
eval $(fnm env --use-on-cd)
zsh: parse error near `()'
```

If I add the script it prints out:

```zsh
      autoload -U add-zsh-hook
      _fnm_autoload_hook () {
        if [[ -f .node-version && -r .node-version ]]; then
          echo "fnm: Found .node-version"
          fnm use
        elif [[ -f .nvmrc && -r .nvmrc ]]; then
          echo "fnm: Found .nvmrc"
          fnm use
        fi
      }

      add-zsh-hook chpwd _fnm_autoload_hook \
        && _fnm_autoload_hook
```

directly to my `.zshrc`, it works as expected.

```
$ fnm --version
1.15.0

$ zsh --version
zsh 5.7.1 (x86_64-apple-darwin18.2.0)
```

**Comment by Schniz** [comment]
Hi! I think that it'll be fixed if you'll wrap it with double quotes everything will be okay: `eval "$(fnm env --use-on-cd)"`

**Comment by CWSpear** [comment]
Yep, that worked. Thanks!

So this maybe should turn into a document request issue, haha.

**Comment by CWSpear** [comment]
I guess the docs do have the quotes... I was just using what was installed into my .zsh, which may have been from an older version.

**Comment by Schniz** [comment]
Yeah, it started to fail when `--use-on-cd` was added and I changed it to have the quotes. I would much rather have it like Fish's syntax: `fnm env --use-on-cd | source` but it doesn't work this way in shells other than fish :(

**Comment by Schniz** [comment]
`source <(fnm env --use-on-cd --multi)` is an option
