### ISSUE TITLE
installing stable

### ISSUE THREAD

**Issue by idkjs** [Schniz/fnm#147]
Is there a command to install the latest stable version of node?

**Comment by ljharb** [comment]
Every version is stable.

**Comment by idkjs** [comment]
I guess I should have said LTS. I came up against this, https://github.com/kelektiv/node.bcrypt.js#version-compatibility, and had to change versions for a second.

**Comment by Schniz** [comment]
#146 will provide a way to install latest lts

**Comment by Schniz** [comment]
Therefore this is duplicate of #137 😇

**Comment by idkjs** [comment]
Always check the issues!!! I figured it a shot in the dark so I would just mention it as an idea...thanks.
