### ISSUE TITLE
Is `--fish` option of `env` (going to be) deprecated?

### ISSUE THREAD

**Issue by thomsj** [Schniz/fnm#155]
There is no mention of the `--fish` option in the README and its functionality is encapsulated by the `--shell` option, but `--fish` is still documented in the manpage and still works.

**Comment by Schniz** [comment]
You're right. We probably need to add a warning when people use it 😄

**Comment by Schniz** [comment]
I haven't deprecated it but I removed it. Hopefully won't make any issues. Sorry!
