### ISSUE TITLE
Should an esy script be added for running feature tests?

### ISSUE THREAD

**Issue by thomsj** [Schniz/fnm#156]
Instead of having to supply the path to the binary, I would prefer to have an esy script added. An esy script could also be added to run the current `test` script followed by the feature test script.

**Comment by Schniz** [comment]
It'd make sense that `esy test` will run these. The other (rely) tests are mostly smoke tests

**Comment by Schniz** [comment]
Since we have migrated to Rust, Esy isn't relevant anymore. But this issue actually resolves into `cargo test`, which runs everything. Thanks for this!
