### ISSUE TITLE
Install from .tar.xz

### ISSUE THREAD

**Issue by sant123** [Schniz/fnm#161]
Hi, I'm having some issues when I try to install a version of node by:

`fnm install 13.0.1`

It takes a long time but is not an issue by the application itself, it's by https://nodejs.org/dist servers. However I could download the tar file with Google Chrome but have no way to tell fnm. "Hey, install it from this file and not from URL". 

Is there something that can be added here? Maybe the same or another command? 

`fnm install -f ./node-v13.0.1-linux-x64.tar.xz`? And maybe if version is not present in the filename add it in a `-v` flag?

Thank you for reading all this stuff :smile:

**Comment by ljharb** [comment]
It’s taking a long time because of a current issue on the node servers. This is almost never a problem, and will certainly be fixed shortly.

**Comment by Schniz** [comment]
@sant123 is it still happening? let's close this issue if it was resolved

**Comment by sant123** [comment]
It's not happening anymore, thank you guys!
