### ISSUE TITLE
fnm install --lts

### ISSUE THREAD

**Issue by jrock2004** [Schniz/fnm#162]
Would love to see an option to run `fnm install --lts` which would install the current lts version. Maybe this is possible right now?

**Comment by jrock2004** [comment]
Sorry, realized that this is an upcoming feature request

**Comment by Schniz** [comment]
No worries my friend! I’ll release the binaries tomorrow. It won’t be `fnm install —lts` but it’ll work. We’ll make the nicer `—lts` flag work in a future release too

**Comment by Linutux** [comment]
Are there any news regarding this issue? An option to install the current LTS version is vital for me.

**Comment by Graborg** [comment]
@Linutux Hi! You can do this with `fnm install --lts` then `fnm use lts/latest`
