### ISSUE TITLE
Skip shell with Brew

### ISSUE THREAD

**Issue by jrock2004** [Schniz/fnm#165]
So I have an install script that I use to setup my boxes. So I do not need brew to set my paths in my zshrc file. Is there a way to skip shell when install via brew or so I have to use

`curl -fsSL https://github.com/Schniz/fnm/raw/master/.ci/install.sh | bash -s -- --install-dir "./.fnm" --skip-shell --force-install`

**Comment by Schniz** [comment]
Sounds reasonable but I have no idea how to do that. Maybe to check for env vars? Is there a way to consume arguments?

**Comment by waldyrious** [comment]
Wasn't this fixed by https://github.com/Schniz/homebrew-tap/pull/4?

**Comment by Schniz** [comment]
Yes! thanks. Closing this!
