### ISSUE TITLE
Could --log-level=quiet be quieter?

### ISSUE THREAD

**Issue by maxjacobson** [Schniz/fnm#166]
Hi there.

I'm using fnm with zsh and I'm very happy with it. Very fast and good.

I have the following in my `~/.zshrc`:

```shell
eval "$(fnm env --multi --use-on-cd --log-level=quiet)"
```

When I `cd` into a directory which has a `.node-version` file, fnm will notice and switch node version. At this point, it prints out:

```
fnm: Found .node-version
```

I would love if it didn't print out anything. That's my read on what "quiet" means. Apologies if I'm missing something.

**Comment by Schniz** [comment]
You’re right. That’s something I was willing to do. But I’m afk for some time. We can open a PR for that :)

**Comment by maxjacobson** [comment]
I would be grateful!
