### ISSUE TITLE
Ubuntu 19.10 fnm command not found

### ISSUE THREAD

**Issue by jrock2004** [Schniz/fnm#167]
So I ran `curl -fsSL https://github.com/Schniz/fnm/raw/master/.ci/install.sh | bash -s -- --install-dir "./.fnm" --skip-shell` and it goes through with no errors. When I close out the terminal and re-open it and I type fnm, I get command not found. Any ideas that I can do to troubleshoot?

Maybe brew install on the mac does something to add fnm to the path where as in linux it does not?

**Comment by Schniz** [comment]
> So I ran `curl -fsSL https://github.com/Schniz/fnm/raw/master/.ci/install.sh | bash -s -- --install-dir "./.fnm" --skip-shell`

The `skip-shell` argument won’t change your shell conf file. That means it doesn’t add the installation directory to the `$PATH`. 

Try running it with `./.fnm/fnm`

**Comment by jrock2004** [comment]
I already have the following in my zshrc file so that is why I set to skip shell https://github.com/jrock2004/dotfiles/blob/master/zsh/zshrc.symlink#L82

**Comment by thomsj** [comment]
Have you tried using the [`--fnm-dir`](https://github.com/Schniz/fnm#fnm-env---multi---shellfishbashzsh---node-dist-mirroruri---use-on-cd---fnm-dirdir---log-levelquieterrorall) option? You can find out more about it by running `fnm env --help`.

**Comment by thomsj** [comment]
I confused myself.

What I should have said is, have you added the install directory to the `$PATH`?

https://github.com/Schniz/fnm/blob/2ec304504600f5e82c34db24c48ae3f79f15de9e/.ci/install.sh#L103

Is `$FNM_DIR` always `$HOME/.fnm`, unless set with `--fnm-dir`, or does fnm detect where it was installed, @Schniz?

**Comment by jrock2004** [comment]
@thomsj Oh this helps out alot. So I just have to manually add `$HOME/.fnm` to my path and now it works.

**Comment by Schniz** [comment]
Alright! so let's close it. Sorry for not responding :) I've been away

Thanks @thomsj for the help!
