### ISSUE TITLE
use-on-cd breaks bash cd with escaped spaces

### ISSUE THREAD

**Issue by aramgre** [Schniz/fnm#168]
With fnm config like 
```
eval "$(fnm env --multi --use-on-cd)"
```
cd with escaped spaces gives an error:
```
$ cd Library/Application\ Support/
-bash: cd: too many arguments
```
fnm 1.16.0
GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0)
macOS 10.14.6

**Comment by Schniz** [comment]
I have a fix for that. Sorry about that.
While you're there, do you think that there's a nicer hack to do that instead of hijacking "cd" on bash using an alias?

**Comment by aramgre** [comment]
Wow, thanks for the quick fix!

>do you think that there's a nicer hack to do that instead of hijacking "cd" on bash using an alias?
The other common approach is having some shim command first in path, like https://github.com/rbenv/rbenv

The cd hijack maybe has the advantage of no other directory of shims to keep track of, but personally I have used tools with both approaches and either one seems fine
