### ISSUE TITLE
macos ls-remote SSL connection error 

### ISSUE THREAD

**Issue by PhilippeDorchies** [Schniz/fnm#170]
Hi,

I installed `fnm` on my macbook pro (macOS High Sierra 10.13.6) with `brew install Schniz/tap/fnm` but it doesn't work...
I've got a SSL connection error:

```
~$ fnm --version
1.16.0
 ~$ fnm ls-remote
Looking for some node versions upstream...
fnm: internal error, uncaught exception:
     SSL connection() error: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

 ~$ fnm ls
No versions installed!
 ~$ fnm env
export PATH=/Users/user/.fnm/current/bin:$PATH
export FNM_MULTISHELL_PATH=/Users/user/.fnm/current
export FNM_DIR=/Users/user/.fnm/
export FNM_NODE_DIST_MIRROR=https://nodejs.org/dist
export FNM_LOGLEVEL=info
 ~$
```
Any idea?

**Comment by CodeSigils** [comment]
Same here - Fedora Workstation 30 on /bin/bash:
`
$ fnm ls-remote
Looking for some node versions upstream...
fnm: internal error, uncaught exception:
     SSL connection() error: error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed

$ fnm --version
1.16.0

$ fnm ls
No versions installed!

$ fnm env
export PATH=/home/seven/.fnm/current/bin:$PATH
export FNM_MULTISHELL_PATH=/home/seven/.fnm/current
export FNM_DIR=/home/seven/.fnm/
export FNM_NODE_DIST_MIRROR=https://nodejs.org/dist
export FNM_LOGLEVEL=info

$ fnm env --multi
export PATH=/tmp/fnm-shell-4282195/bin:$PATH
export FNM_MULTISHELL_PATH=/tmp/fnm-shell-4282195
export FNM_DIR=/home/seven/.fnm/
export FNM_NODE_DIST_MIRROR=https://nodejs.org/dist
export FNM_LOGLEVEL=info

$...
`
Maybe its conflict with system's Node, or cache problem ?

**Comment by Schniz** [comment]
What happens when you `curl https://nodejs.org/dist`? seems that openssl can't validate https://nodejs.org certificates

**Comment by Schniz** [comment]
Also, are you on a new machine?

**Comment by CodeSigils** [comment]
curl returns 301
```sh
$ curl https://nodejs.org/dist
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by PhilippeDorchies** [comment]
Same curl returns on macos... no ssl certificate error.

On a new machine ? 
No, it's a MacBook Pro (Retina, 13-inch, Early 2015) on macOS High Sierra version 10.13.6

**Comment by Schniz** [comment]
[fnm-macos - ocaml-tls.zip](https://github.com/Schniz/fnm/files/3883323/fnm-macos.-.ocaml-tls.zip)

Can you try unzipping this version of `fnm` and trying `./fnm ls-remote`? This is the binary from #172 and I'm not quite sure this will be the process we're going to go for, but it worth trying. I'll explain more in the PR itself

**Comment by Schniz** [comment]
oh it happens on Fedora as well 🤔

**Comment by Schniz** [comment]
[fnm-linux - ocaml-tls.zip](https://github.com/Schniz/fnm/files/3883347/fnm-linux.-.ocaml-tls.zip)

Linux build works on a fedora docker container. @CodeSigils do you want to try that build too?

**Comment by CodeSigils** [comment]
@Schniz yes I already used it in a container but I wanted to install it on my laptop. Strange !

**Comment by Schniz** [comment]
Cool. I'm going to probably merge #172 and use `ocaml-tls` instead of `ocaml-ssl`. The only problem is that it doesn't compile on Windows. I already discussed that with @ulrikstrid, because a Windows program might be a different beast and work entirely different than fnm. I don't use Windows and therefore I don't have an incentive of implementing that, but we can have a monorepo with a shared suite of feature tests so we can run the tests on all of the platforms.

I wonder if it also fixes @PhilippeDorchies's issue — can you let us know?

**Comment by PhilippeDorchies** [comment]
> [fnm-macos - ocaml-tls.zip](https://github.com/Schniz/fnm/files/3883323/fnm-macos.-.ocaml-tls.zip)
> 
> Can you try unzipping this version of `fnm` and trying `./fnm ls-remote`? This is the binary from #172 and I'm not quite sure this will be the process we're going to go for, but it worth trying. I'll explain more in the PR itself

Great! That's work for me on macos ;)
