### ISSUE TITLE
zsh & bash completions

### ISSUE THREAD

**Issue by gillchristian** [Schniz/fnm#171]
I see there's already some work in progress for adding fish completions (#105).

Would you be interested to add bash and zsh ones?

A friend of mine is working on a way to generate completions ([completely](https://github.com/fvictorio/completely)). At the moment it only supports a JSON declaration as the input. Eventually there will be a DSL to write them and/or some way to generate completions from the `--help` command.

I can write the JSON declaration and then generate them and open a PR or the other option is to have the JSON declarations in the repo and run it in a build step.

Also, great project! Thanks for working on this! 🎉

**Comment by Schniz** [comment]
The new version (implemented in Rust) is shipped with completions:
```
fnm completions --shell {bash,zsh,fish,powershell}
```
will produce shell completions

**Comment by anan44** [comment]
I have a problem with the zsh completions. There is no instructions what to do with the output provided by fnm. Apparently for fish it works out of the box, but this does not seem to be the case with zsh.

**Comment by Schniz** [comment]
Hi @anan44! What's up 😄 

I'm not entirely sure how to do with zsh completions, but I know that homebrew installs them (verified that) and I know that it works for me on my machine, and this is how I did it locally:

```zsh
fnm completions --shell=zsh > ~/.zfunc/_fnm
```

because I have the following in my `.zshrc`:

```zsh
fpath+=~/.zfunc
compinit
```

I guess it says:

* add the ~/.zfunc dir to the functions dir
* initialize completions

Can you try that to install completions?

**Comment by anan44** [comment]
Hi @Schniz!

First of all huge hats off for faster that speed of light response!

I tried your instructions and it works like a charm! Thanks mate!

**Comment by batbrain9392** [comment]
I'm using [antigen](https://github.com/zsh-users/antigen) and followed these steps:

1. Added [zsh-completions](https://github.com/zsh-users/zsh-completions) antigen plugin in `~/.zshrc`
2. Then ran `fnm completions --shell=zsh > ~/.antigen/bundles/zsh-users/zsh-completions/src/_Debmallya Bhattacharya`

Works for me.

**Comment by alexilyaev** [comment]
Installing latest `fnm` (using `zsh`) adds the completions automatically to `/opt/homebrew/share/zsh/site-functions` (mentioned in the setup notes).

So adding this to `.zshrc` is enough:
```zsh
fpath+="/opt/homebrew/share/zsh/site-functions"

autoload -Uz compinit
compinit
```

I wish this was in the README.

**Comment by Michael-1** [comment]
To install it with **Bash,** run:
```bash
eval "$(fnm completions)"
```
