### ISSUE TITLE
`fnm env` opens PHPStorm 😅

### ISSUE THREAD

**Issue by sebastiaanluca** [Schniz/fnm#175]
```bash
$ fnm env
Traceback (most recent call last):
  File "/usr/local/bin/ps", line 136, in <module>
    if not try_activate_instance(ide_args):
  File "/usr/local/bin/ps", line 112, in try_activate_instance
    response = read_sequence_from_sock(s)
  File "/usr/local/bin/ps", line 42, in read_sequence_from_sock
    data = read_from_sock(sock)
  File "/usr/local/bin/ps", line 34, in read_from_sock
    length = struct.unpack('>h', sock.recv(2))[0]
struct.error: unpack requires a string argument of length 2
export PATH=.../.fnm/current/bin:$PATH
export FNM_MULTISHELL_PATH=.../.fnm/current
export FNM_DIR=.../.fnm
export FNM_NODE_DIST_MIRROR=https://nodejs.org/dist
export FNM_LOGLEVEL=info
```

Fresh install via homebrew. Not sure why this is, but probably related to https://github.com/Schniz/fnm/issues/108. It tries to open PHPStorm via the `ps` command with the `-o` parameter on every new shell unless I remove the fnm line from my bash profile.

**Comment by ljharb** [comment]
ps is a Linux command http://man7.org/linux/man-pages/man1/ps.1.html

Are you sure you didn’t shadow it with your own custom alias?

**Comment by sebastiaanluca** [comment]
Yeah, you're right. I've deleted the PHPStorm `ps` command from `/usr/local/bin` and now it works. Seems like it prioritized the custom command instead of the system's default. Cheers!

**Comment by Schniz** [comment]
I'm glad to hear! thanks for using fnm :)
