### ISSUE TITLE
fnm is in a bad state after failed installation

### ISSUE THREAD

**Issue by gilly3** [Schniz/fnm#178]
I'm finding that I receive a lot of errors in WSL in general during file write operations, particularly rename.  These errors seem to be unrelated fnm directly, and retrying the operation seems to correct the issue.  However, when fnm encounters one of these errors, it gets into a bad state.

Here's an example of the output I see when an install fails:

```bash
$ fnm install v6
Version v6.17.1 was successfully downloaded
fnm: internal error, uncaught exception:
     Unix.Unix_error(Unix.EACCES, "rename", "/home/ivan/.fnm/node-versions/v6.17.1/node-v6.17.1-linux-x64")
```

fnm reports the version is installed, and even lets me use the version:
```bash
$ fnm ls
The following versions are installed:
* system
* v6.17.1
* v8.17.0
* v10.18.0
* v12.13.1 (default, latest-erbium)
$ fnm use v6
Using v6.17.1
```

But, when I try to actually use the version, it fails:
```bash
$ node -v
-bash: /tmp/fnm-shell-6733151/bin/node: No such file or directory
```

If I attempt to reinstall, fnm reports it's already installed, but if I attempt to uninstall, fnm reports it's _not_ installed:
```
$ fnm install v6
Version v6.17.1 is already installed.
$ fnm uninstall v6
The version v6 is not installed.
```

I can uninstall by specifying the full version:
```bash
$ fnm uninstall v6.17.1
Node version v6.17.1 has correctly been removed.
$ fnm ls
The following versions are installed:
* system
* v8.17.0
* v10.18.0
* v12.13.1 (default, latest-erbium)
```

Perhaps uninstall by alias isn't supported at all, since I see the same behavior from successfully installed versions.  I didn't notice anything in the documentation about requiring an exact version for uninstall.

This isn't super critical as I'm able to work around the issue, but more error handling would be make the tool more robust.

**Comment by Schniz** [comment]
> ```
> $ fnm uninstall v6
> The version v6 is not installed.
> ```

This is the right behavior for now, relates to #121 



> Perhaps uninstall by alias isn't supported at all

Currently not, uninstall is a simple `rm -rf $FNM_DIR/node-versions/<PROVIDED_VERSION>`



> but more error handling would be make the tool more robust.

This is very true. A good way of doing it will be to create the directory and install everything inside a temp directory. If it crashes, the temp directory will be cleaned. If it won't crash, we can do `mv THE_TEMP_DIR THE_DISTINATION`

**Comment by Schniz** [comment]
This is fixed using the [DirectoryPortal](https://github.com/Schniz/fnm/blob/master/src/directory_portal.rs) struct in the new Rust implementation, which installs to a temp directory and moves its contents when all the critical work is finished. 😄

**Comment by Schniz** [comment]
Thanks for filing it @gilly3!
