### ISSUE TITLE
Replace `curl`

### ISSUE THREAD

**Issue by Schniz** [Schniz/fnm#18]
Use an OCaml replacement or a statically linkable library, instead of spawning a subprocess. Need to verify that it works on a plain Mac (there is no static link process for MacOS, AFAIK)

* `cohttp{,-lwt}` with `ssl_lwt`?
* `ocurl`?
* `httpkit`? (cc @thangngoc89)

**Comment by thangngoc89** [comment]
@Schniz I almost finish with that. Could you please make the CI public? I can send a PR with CI check

**Comment by Schniz** [comment]
@thangngoc89 whoops! made it public now. Sorry 😸

**Comment by Schniz** [comment]
Implemented in #57 😄
