### ISSUE TITLE
Brew installation messages are confusing

### ISSUE THREAD

**Issue by waldyrious** [Schniz/fnm#184]
I just tried installing `fnm` via the brew tap, and got the following output:

```
❯ brew install Schniz/tap/fnm
==> Tapping schniz/tap
Cloning into '/usr/local/Homebrew/Library/Taps/schniz/homebrew-tap'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 10 (delta 0), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), done.
Tapped 1 formula (39 files, 30.8KB).
==> Installing fnm from schniz/tap
==> Downloading https://github.com/Schniz/fnm/releases/download/v1.18.1/fnm-macos.zip
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/166045424/0b1e9b80-2af9-11ea-97a4-df5c6a1259fe?X-Amz-Algorithm=AWS4
######################################################################## 100.0%
Can't read shell profile!
==> Caveats
No `# fnm` in ~/.zshrc, so fnm was installed to it.
```

There are three issues here:
- I'm not sure what I'm supposed to do about `Can't read shell profile!`
- There's a message ``No `# fnm` in ~/.zshrc, so fnm was installed to it.``, but I can't find any reference to `fnm` in `~/.zshrc`
- I'd have preferred a prompt before my `~/.zshrc` was edited. In particular, my setup uses a common `~/.zshrc` file that is shared with my team, and a `~/.zshrc.local` file that contains individual customizations.

What would you suggest for each of these issues, @Schniz?

**Comment by Schniz** [comment]
I'll be honest and I'll say that I don't really know what's going on with Homebrew formulas. It used to work, and now, for some reason, `shell_profile` refers to a temp directory.

We have two options here from what I can see:
* We can do what `nvm` does and print in `caveats` what are the steps necessary for installing fnm in your shell file.
* We can also add a `fnm install-shell [--shell=] [--path=]` subcommand that'll have the installation logic inside fnm itself. This can be also shared with the Linux installation script! Then, as a caveat, we can mention "Cool! now run `fnm install-shell` and you're good to go"

**Comment by waldyrious** [comment]
The second option sounds great (as long as it's pre-filled with the best-guess parameter values so that users can just copy and run the command). That gives me a single command to run and I'll be all set, plus it assures me that no configurations have been automatically changed without my consent. 👍

**Comment by Schniz** [comment]
Yeah. shouldn't be hard because we already have `System.Shell.infer()`

That being said, it's more error prone. I'll wait to see if Jordan responds with some insights, and I might start with making the Brew installer as easy as it can get with no shell profile manipulation.

**Comment by Schniz** [comment]
> it's more error prone
By that I mean it'll take some time and effort to test it correctly, which I don't really have. I'll accept PRs though!

**Comment by Schniz** [comment]
sorry for not being responsive lately. I had some personal things. Let me know what you think about the following PR that removes the automated installation completely: https://github.com/Schniz/homebrew-tap/pull/6

**Comment by waldyrious** [comment]
Nice! The automation would have been nice, but the manual instructions are pretty clear and helpful. I can't think of anything that would improve them (other than perhaps mention the need to source the profile file or restart the shell, for the less attentive?)

**Comment by Schniz** [comment]
That PR is merged. Please reopen if you think that we need to change something there. Or even better, submit a PR! 😄 

thanks for the kindness and help @waldyrious 😄
