### ISSUE TITLE
`fnm use` not working (fully?)

### ISSUE THREAD

**Issue by adokce** [Schniz/fnm#187]
I just formatted my mac after upgrading to Catalina. I have previously used zsh and fnm without problems.
Installed fnm via `brew install Schniz/tap/fnm`

My guess is that there is some kind of $PATH issue but I have no idea why or how to debug it.

<img width="572" alt="Screenshot 2020-01-31 at 16 33 40" src="https://user-images.githubusercontent.com/20118440/73551850-78e71b80-4447-11ea-94ec-edcc0a992ae4.png">

**Comment by kkostepski** [comment]
Hi! Apparently you need to fix your .zshrc config manually. You need to add the following line:
```
eval "`fnm env --multi`"
```
(source: https://github.com/Schniz/fnm#manually)

For example, my $PATH is:
```
echo $PATH
/var/folders/ds/72_xfgfd3xzdzpvrv3tsc7k00000gn/T/fnm-shell-9593214/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```

**Comment by adokce** [comment]
Thank you, that worked.

Does that mean the brew install needs to be updated? I don't remember having to do any manual steps before.

**Comment by f0cus10** [comment]
I've had the exact same experience with my fresh install. It does seem like there is [conversation](https://github.com/Schniz/fnm/issues/184#issuecomment-575094588) in the repo about it.

**Comment by Schniz** [comment]
Yeah. Sorry for not being responsive lately. I need to make the installer print the steps needed in order to install fnm because unfortunately it doesn’t work automatically anymore

**Comment by Schniz** [comment]
I have opened a PR for the homebrew formula. It makes it less fun to install, but won't show weird errors.

https://github.com/Schniz/homebrew-tap/pull/6
