### ISSUE TITLE
Support arguments to ls-remote

### ISSUE THREAD

**Issue by mgol** [Schniz/fnm#188]
Basically, having an equivalent of `nvm ls-remote [parameter]` would be cool. In particular, I often invoke `nvm ls-remote 12` which only shows `12.x.y` versions; with fnm I can only list all versions from which I then need to grep as the list is quite long.

**Comment by Schniz** [comment]
I agree! it would be nice.
It would also be very simple change to do if you want to get into Reason, so let's wait for people who want to try coding in Reason 😄 
I do `fnm ls-remote | grep "^10"` these days
