### ISSUE TITLE
`fnm default` doesn't work with alias

### ISSUE THREAD

**Issue by TuurDutoit** [Schniz/fnm#189]
I can use `fnm install latest`, `fnm use latest`, etc. but `fnm default latest` fails with the following error: `Can't find a version installed in /Users/tuur/.fnm/node-versions/latest/installation`

**Comment by thomsj** [comment]
Also mentioned in [#159 (comment)](https://github.com/Schniz/fnm/issues/159#issuecomment-567274444).

**Comment by Schniz** [comment]
Yes, I think we should consolidate both of them in one issue. Thanks for reporting @TuurDutoit!

**Comment by Schniz** [comment]
This works in latest fnm. `fnm default lts-latest` works. 😄 
Thanks for filing the issue!
