### ISSUE TITLE
Cannot uninstall based on alias

### ISSUE THREAD

**Issue by f0cus10** [Schniz/fnm#195]
When a version is aliased, I should be able to uninstall by doing `fnm uninstall [alias]`. However, this doesn't work.

Check screenshot below:

<img width="857" alt="Screen Shot 2020-02-25 at 3 11 23 PM" src="https://user-images.githubusercontent.com/27834486/75283766-732fec00-57e1-11ea-9702-5efc326a6c80.png">

**Comment by Schniz** [comment]
Yeah, and even with the latest uninstall PR that got merged (#191) it won't work.

What do you expect it to do? "unalias" or just remove the node installation? I kinda dislike the idea of removing based on an alias. It's like `rm -rf /path/to/some/symlink`. AFAIK, it won't remove the target of the symlink.

_That being said_, even if I don't believe so, we might need to output a different error, like `Did you mean to uninstall the version aliased as latest-argon, v4.9.1? here's how to do that: ...`

In #194 I will try to normalize how we "parse" versions, making `uninstall` work the same as `use` and `install` _(which is not the case right now)_, and maybe it'll be possible and easy to do afterwards. All the version handling code is a mess. I think I need to do a serious refactor there.

**Comment by f0cus10** [comment]
My expectations -- which may be unreasonable -- stem from using `nvm uninstall alias` to uninstall versions. In the end, it's about reducing how much I have to type when I want to upgrade aliases. (e.g. changing `latest-erbium` from `v12.14.1` to `v12.16.1`). Again, this may not be common behavior. 

Regardless, thanks for your attention to the matter and all that you do. My shell prompt has saved sooo much time because of `fnm`

**Comment by Schniz** [comment]
#292 just added a test that does `fnm alias VER hello && fnm uninstall hello` which removes the installed Node version 😄
