### ISSUE TITLE
README fnm.svg request

### ISSUE THREAD

**Issue by a2902793** [Schniz/fnm#198]
Irrelevant issue here, just wanted to know if you could tell me how you made the fnm.svg in README.md...Some questions here, if you don't mind :
1. I believe the shell must be **zsh**? 
2. If so, what **theme** and **font** is it?
3. How is the **hexagram** in the front achieved?
4. Is this recorded using **terminalizer**?

I think the animation you made is <ins>THE coolest</ins> one I've ever seen so far, way to go 🎉  !

**Comment by Schniz** [comment]
Hi! thanks for the kind words 😄 

1. This is not a real shell, and it is recorded on every version I create using [this script](https://github.com/Schniz/fnm/blob/master/docs/record_screen.sh). I copied most of it from [`create-react-app`](https://github.com/facebook/create-react-app/blob/4562ab6fd80c3e18858b3a9a3828810944c35e36/tasks/screencast.js) 😄 
2. This is the default theme by [svg-term-cli](https://github.com/marionebl/svg-term-cli). The SVG source says the font is `font-family="Monaco,Consolas,Menlo,'Bitstream Vera Sans Mono','Powerline Symbols',monospace"`. I personally use `base16-eighties` theme and Fira Code patched for powerline
3. The hexagram (Magen David in Hebrew) is in the following file https://github.com/Schniz/fnm/blob/83e9168e8a8512e172eb55cf1df5325eeb8ec5b7/docs/recorded_screen_script.sh#L5
   but I also have it on my shell as well: 
   ![shell image](https://user-images.githubusercontent.com/2054772/75359252-cf1b7300-58bc-11ea-814f-6cb24d1c2833.png)
4. I use `asciinema`. I'm not sure if terminalizer is better or not, asciinema seems to work 😄 

thanks for opening the issue and your kind words again 😄 
have a great day

**Comment by dalisoft** [comment]
Thanks a lot for guide. You can make somewhere tutorial how you achieved this, i sure you will get a lot of watcher and users.
