### ISSUE TITLE
Include additional completions

### ISSUE THREAD

**Issue by james2doyle** [Schniz/fnm#205]
I made some fish shell completions for your project and tried to post them to OMF: https://github.com/oh-my-fish/packages-main/pull/108

Seems like they want them to be included in the original projects. Maybe you could consider including my project as a submodule? https://github.com/james2doyle/omf-plugin-fnm

**Comment by Schniz** [comment]
Next version will have Fish completions baked in, autogenerated by [clap](https://crates.io/crates/clap):

```
fnm completions --shell fish
```

😄
