### ISSUE TITLE
fnm: internal error, uncaught exception:  "resolution failed: unknown scheme"

### ISSUE THREAD

**Issue by Rush** [Schniz/fnm#208]
```
rush@rushbox: ~ 125 » fnm install 13
fnm: internal error, uncaught exception:
     (Failure "resolution failed: unknown scheme")
     
rush@rushbox: ~ 125 
```

Issue started happening by itself. I have tried reinstalling but to no avail

**Comment by Schniz** [comment]
Hi, maybe this will help:
https://github.com/Schniz/fnm/issues/141#issuecomment-533857727

let me know

**Comment by Schniz** [comment]
I'm closing in the meantime.
