### ISSUE TITLE
libssl

### ISSUE THREAD

**Issue by pavelloz** [Schniz/fnm#212]
I have upgraded brew packages and it looks like it upgraded some libs that are required in specific version by fnm:

```
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/pavel/.fnm/fnm
  Reason: image not found
```

Im using macos `10.14.6`.

I tried installing openssl 1.0.0, but there is no tap for that anymore (brew wanted to do --unshallow to find it but that would take far too long), is there any way of bringing it back to life?

**Comment by Schniz** [comment]
What version of `fnm` are you running?

**Comment by pavelloz** [comment]
```
|⇒ brew info fnm
schniz/tap/fnm: stable 1.20.0
Fast and simple Node.js version manager
https://github.com/Schniz/fnm
/usr/local/Cellar/fnm/1.20.0 (3 files, 6.4MB) *
```

**Comment by Schniz** [comment]
> I have upgraded brew packages and it looks like it upgraded some libs that are required in specific version by fnm:
> 
> ```
> dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
>   Referenced from: /Users/pavel/.fnm/fnm
>   Reason: image not found
> ```
> 
> Im using macos `10.14.6`.

Can you try to remove or at least rename `~/.fnm/fnm`? I think you once installed it from the installation link and then never really migrated to the Homebrew installation

**Comment by Schniz** [comment]
The `Referenced from: /Users/pavel/.fnm/fnm` makes me think that

**Comment by pavelloz** [comment]
That fixed it! Conflict solved :)

Apparently i didnt remove older fnm after i read that its recommended to use brew nowadays, and just installed brew one.

Thank you :)

**Comment by Schniz** [comment]
Cheers. happy to help!
