### ISSUE TITLE
Support version aliases for installing/defaulting lts and latest

### ISSUE THREAD

**Issue by kclejeune** [Schniz/fnm#215]
Hi! I transitioned to using fnm from nvm fairly recently because of shell startup times.  It's been great so far, but one feature that I'm sorely missing the ability to use something like `fnm install lts`. Similarly, I'd love to be able to use something like `fnm default lts`. 

I realize I could add these manually with `fnm alias x.y.z lts` or something, but this still requires searching to find the actual current LTS version, which sort of defeats the purpose. Have you considered (or would you be willing to consider) adding these default aliases for the most commonly installed versions?

**Comment by Schniz** [comment]
This works right now by running `fnm install latest` and `fnm install 'lts/*'`. Can you check these out?

**Comment by kclejeune** [comment]
Exactly what I was looking for, not sure how I never managed to find that — are there similar aliases for `fnm default`?

**Comment by Schniz** [comment]
They are not documented — probably need to add examples to the docs (`fnm install --help`). Sorry about that. I'd be very happy to know if you're into adding that to the README 😄

**Comment by kclejeune** [comment]
Yeah no problem, I'll submit a PR when I get some spare time; thanks so much!

**Comment by Schniz** [comment]
Closing because we solved it 😇
