### ISSUE TITLE
Installing FNM in Zsh 

### ISSUE THREAD

**Issue by leogouveia** [Schniz/fnm#218]
Hello, 
I'm having trouble installing FNM using ZSH (Ubuntu 20.04).

When I use curl -fsSL `https://github.com/Schniz/fnm/raw/master/.ci/install.sh | bash` it sets the configuration in my .bashrc but not in my .zshrc even if I install it using ZSH.

If a change bash at the end of the command to zsh I get the error `set_filename:5: = not found`.

What am I missing?

**Comment by leogouveia** [comment]
Sorry everyone.

Just found out the answer:

> $SHELL is the environment variable that holds your preferred shell, not the currently running shell. It's initialised by login or any other application that logs you in based on the shell field in your user entry in the passwd database (your login shell).
[https://unix.stackexchange.com/a/330242](https://unix.stackexchange.com/a/330242)

As I installed FNM just after installing zsh...

**Comment by Schniz** [comment]
All is good. Thanks for the update! Hope fnm will make you happy 😃

**Comment by leogouveia** [comment]
@Schniz would be cool if the installer inserts the configuration in more than one shell config file. So if I alternate between fish/zsh/bash I'd still be able to use FNM. Maybe instead of checking for "default shell", check if the configuration file (.zshrc, .bashrc and .config/fish/config.fish) exists would be better a better option.

**Comment by Schniz** [comment]
Sounds good. We can do this. I just wonder if this is too intrusive. Do you want to make a PR? 😄
