### ISSUE TITLE
Add a prebuilt ARM binary

### ISSUE THREAD

**Issue by mbeaudru** [Schniz/fnm#222]
Steps followed:

- Install fnm through the script: https://github.com/Schniz/fnm#using-a-script
- Restart the terminal

Issue:

- `~/.zshrc:110: exec format error: fnm` prompts after opening a new terminal
- Running `fnm` prompts `sh: exec format error: fnm`

Environment:

Raspberry Pi under raspbian

**Comment by alx365** [comment]
Same here with archlinux arm on a Raspberry Pi. Please remove a arm version.

**Comment by Schniz** [comment]
Sorry that it doesn't work, fellas!

I personally don't own a Raspberry Pi. Would you mind explaining to me what's wrong? Is it because it wasn't build for an ARM processor? What are the steps necessary to do that? Running on a different Docker image?

**Comment by alx365** [comment]
So yes, the Pi uses the ARM architecture, What you will have to do, is either cross compile with whatever tool you are using, or just compile it on a arm device, such as your phone (probably a rather stupid idea), or running a arm OS in a virtual machine, that is fully emulated. 
By now i already looked in your README, and saw that you use "esy" to compile your program
I couldn't find anything online on how to cross compile with that particular compiler, in the 5 minutes i searched.

**Comment by Schniz** [comment]
It looks like Dune can cross compile, not sure about ARM though. If someone wants to jump to the native development Discord and do that research, it could be awesome!

**Comment by Schniz** [comment]
@mbeaudru do you mind if I change the title to "Allow to run on ARM devices"?

**Comment by mbeaudru** [comment]
I just did it ! Thank you for working on this project by the way 👍

**Comment by jaythomas** [comment]
9ba282a705c7a8f3d2dfbfb08d4c62720f600676 we got Rust now :eyes: ?? Is there anything I can do to help?  Not sure what's left but I have a Pinebook Pro running Arch Arm. I see `cargo build` runs without a hitch. Perhaps we can get a published crate too?

**Comment by Schniz** [comment]
Looks like we can use https://github.com/rust-embedded/cross and create binaries for ARM and probably test everything with it as well. Maybe I have a Raspberry Pi 2 somewhere to test it with but I'm not sure where it is 😜  Would you want to collaborate on this?

> > I see `cargo build` runs without a hitch.

The fact it builds is awesome! but I think we still need to make a code change. Don't really know ARM terminology but I think we need to change this:

https://github.com/Schniz/fnm/blob/1368ae6b01c3d900c6326838543d32dbb5971a92/src/system_info.rs#L11-L19

into:

```rust
#[cfg(all(target_pointer_width = "32", target_arch = "arm"))]
pub fn platform_arch() -> &'static str {
    "armv7l"
}

#[cfg(all(target_pointer_width = "32", not(target_arch = "arm")))]
pub fn platform_arch() -> &'static str {
    "x86"
}

#[cfg(all(target_pointer_width = "64", target_arch = "arm"))]
pub fn platform_arch() -> &'static str {
    "arm64"
}

#[cfg(all(target_pointer_width = "64", not(target_arch = "arm")))]
pub fn platform_arch() -> &'static str {
    "x64"
}
```

because the URLs are not `x64` and `x86` for the prebuilt ARM Node.js binaries:

* 64bit hardware will return links like https://nodejs.org/dist/v12.14.0/node-v12.14.0-linux-arm64.tar.xz
* 32bit hardware will return links like https://nodejs.org/dist/v12.14.0/node-v12.14.0-linux-armv7l.tar.xz

(based on https://nodejs.org/dist/v12.14.0/)

Is this the right call?

Once we figure out which toolchain of `cross` we need to use, I can make it automated with GH actions, but I'm going to need your help for knowing which toolchain to use 😄 

> Perhaps we can get a published crate too?

So `cargo install fnm` will work? Sure, that can work 😄

**Comment by Schniz** [comment]
Also,

> I see `cargo build` runs without a hitch.

This makes me happy 😄

**Comment by cdaringe** [comment]
You can use docker with qemu runtime to both build and execute arm on non arm hosts, which would be a win for fnm CI build/publish cycles.

**Comment by jaythomas** [comment]
@Schniz that modification does the trick for me as the tests in `cargo test` now pass node installation (although it should be `aarch64`, not `arm64`). I haven't had time yet to test much of the functionality otherwise.

**Comment by jaythomas** [comment]
Ok just now getting back around to looking at this. Also disregard my last comment about the arch as I was misreading the code and didn't realize that was just setting the {arch} variable in the download url. So, the above changes to `system_info.rs` works as expected, but I get an error with `fnm install`:

```
$ ./target/debug/fnm install v14.14.0
Installing Node v14.14.0
Going to call for https://nodejs.org/dist/v14.14.0/node-v14.14.0-linux-arm64.tar.xz
error: Can't download the requested version: IoError: Invalid cross-device link (os error 18)
```

The url is correct when I test on aarch64 and x86, however DownloadError is being returned in either case so there is a second issue in the code somewhere unrelated to the architecture. Confusingly, the snap tests don't fail on `fnm install`. I haven't figured out what all is going on yet.

**Comment by jaythomas** [comment]
I tracked down the issue to this line of code:
https://github.com/Schniz/fnm/blob/136ea0308058053b679e1bbbf85ca839e031d30b/src/directory_portal.rs#L24

But according to the docs on [fs::rename](https://doc.rust-lang.org/std/fs/fn.rename.html):
> This will not work if the new name is on a different mount point.

...Which is often the case with /tmp and /home.

I don't know a better way to move a directory other than simply copying it recursively then calling `fs::remove_dir_all`. @Schniz if you want a cleaned-up separate PR or issue+PR for this change let me know.

```diff
diff --git a/src/directory_portal.rs b/src/directory_portal.rs
index 25f1e73..59d15fd 100644
--- a/src/directory_portal.rs
+++ b/src/directory_portal.rs
@@ -1,5 +1,5 @@
 use log::*;
-use std::path::Path;
+use std::path::{Path, PathBuf};
 use tempfile::{tempdir, TempDir};
 
 pub struct DirectoryPortal<P: AsRef<Path>> {
@@ -7,6 +7,53 @@ pub struct DirectoryPortal<P: AsRef<Path>> {
     target: P,
 }
 
+pub fn copy<U: AsRef<Path>, V: AsRef<Path>>(from: U, to: V) -> Result<(), std::io::Error> {
+    let mut stack = Vec::new();
+    stack.push(PathBuf::from(from.as_ref()));
+
+    let output_root = PathBuf::from(to.as_ref());
+    let input_root = PathBuf::from(from.as_ref()).components().count();
+
+    while let Some(working_path) = stack.pop() {
+        debug!("process: {:?}", &working_path);
+
+        // Generate a relative path
+        let src: PathBuf = working_path.components().skip(input_root).collect();
+
+        // Create a destination if missing
+        let dest = if src.components().count() == 0 {
+            output_root.clone()
+        } else {
+            output_root.join(&src)
+        };
+        if std::fs::metadata(&dest).is_err() {
+            debug!(" mkdir: {:?}", dest);
+            std::fs::create_dir_all(&dest)?;
+        }
+
+        for entry in std::fs::read_dir(working_path)? {
+            let entry = entry?;
+            let path = entry.path();
+            if path.is_dir() {
+                stack.push(path);
+            } else {
+                match path.file_name() {
+                    Some(filename) => {
+                        let dest_path = dest.join(filename);
+                        debug!("  copy: {:?} -> {:?}", &path, &dest_path);
+                        std::fs::copy(&path, &dest_path)?;
+                    }
+                    None => {
+                        debug!("failed: {:?}", path);
+                    }
+                }
+            }
+        }
+    }
+
+    Ok(())
+}
+
 impl<P: AsRef<Path>> DirectoryPortal<P> {
     #[must_use]
     pub fn new(target: P) -> Self {
@@ -21,7 +68,8 @@ impl<P: AsRef<Path>> DirectoryPortal<P> {
             self.temp_dir.path(),
             self.target.as_ref()
         );
-        std::fs::rename(&self.temp_dir, &self.target)?;
+        copy(&self.temp_dir, &self.target)?;
+        std::fs::remove_dir_all(&self.temp_dir)?;
         Ok(self.target)
     }
 }
```
