### ISSUE TITLE
A problem with openssl?

### ISSUE THREAD

**Issue by moshfeu** [Schniz/fnm#228]
> dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/*/.fnm/fnm
  Reason: image not found

I'm not sure when it started..
I tried to re-install using `brew install Schniz/tap/fnm`.

My os: Mac OS Catalina 10.15.5 (19F101)

P.S. I'm not sure but maybe I first installed it using the script if it matters.

**Comment by Schniz** [comment]
Hey @moshfeu!
As you said, it seems like your shell does not use the Homebrew version, and therefore probably an old version of fnm!

Would you mind removing `~/.fnm` from your `$PATH`? (it's probably in your `.zshrc` file)

also, ensure that you have fnm installed via homebrew so it won't blow up: `brew install Schniz/tap/fnm`

**Comment by moshfeu** [comment]
I've ended up with `rm -rf /Users/moshef/.fnm` (extreme I know 🤦‍♂️) and `brew reinstall fnm`.

Thanks!

**Comment by Schniz** [comment]
haha, no problems. You could also remove `~/.fnm/fnm` because that was the faulty binary 😃 happy that everything worked out
