### ISSUE TITLE
fish shell: fnm not executable

### ISSUE THREAD

**Issue by dalisoft** [Schniz/fnm#230]
Hi @Schniz 

I found error while installing new nodejs env in Linux.
`chmod +x` did not help.

```
dalisoft@pop-os:~/Desktop/config$ fnm
bash: /home/linuxbrew/.linuxbrew/bin/fnm: cannot execute binary file: Exec format error
dalisoft@pop-os:~/Desktop/config$ 
```

It maybe Github Actions error or Homebrew as Homebrew installs macOS version.

<details>
<summary>Log</summary>

```bash
dalisoft@pop-os:~/Desktop/config$ brew tap Schniz/tap
Updating Homebrew...
dalisoft@pop-os:~/Desktop/config$ brew install fnm
Updating Homebrew...
==> Installing fnm from schniz/tap
==> Downloading https://github.com/Schniz/fnm/releases/download/v1.21.0/fnm-macos.zip
Already downloaded: /home/dalisoft/.cache/Homebrew/downloads/3924eda9cd8f648073c141e489ea87d1067df92f33a03c0ba25758169270f99c--fnm-macos.zip
==> Caveats
Thanks for installing fnm!
The last step for making fnm work is to run it on the shell startup, using the `fnm env` command.

In order to complete the installation, please add the following to your shell profile:

  # fnm
  eval "$(fnm env --multi)"

Homebrew tells us that bash is your preferred shell,
and your shell profile is at "~/.profile", if that helps 😇

> btw, if you know how to make this process automated, help us out with a PR!
> the code is here: https://github.com/Schniz/homebrew-tap/blob/master/Formula/fnm.rb
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/fnm/1.21.0: 3 files, 6.4MB, built in 0 seconds
dalisoft@pop-os:~/Desktop/config$ fnm
bash: /home/linuxbrew/.linuxbrew/bin/fnm: Permission denied
dalisoft@pop-os:~/Desktop/config$ sudo fnm
sudo: fnm: command not found
dalisoft@pop-os:~/Desktop/config$ fnm
bash: /home/linuxbrew/.linuxbrew/bin/fnm: Permission denied
dalisoft@pop-os:~/Desktop/config$ chmod +x (which fnm)
bash: syntax error near unexpected token `('
dalisoft@pop-os:~/Desktop/config$ chmod +x $(which fnm)
chmod: missing operand after ‘+x’
Try 'chmod --help' for more information.
dalisoft@pop-os:~/Desktop/config$ which fnm
dalisoft@pop-os:~/Desktop/config$ which fnm -a
dalisoft@pop-os:~/Desktop/config$ fnm
bash: /home/linuxbrew/.linuxbrew/bin/fnm: Permission denied
dalisoft@pop-os:~/Desktop/config$ chmod +x /home/linuxbrew/.linuxbrew/bin/fnm
dalisoft@pop-os:~/Desktop/config$ fnm
bash: /home/linuxbrew/.linuxbrew/bin/fnm: cannot execute binary file: Exec format error
dalisoft@pop-os:~/Desktop/config$ 
```
</details>

Thanks

**Comment by Schniz** [comment]
Woah! I didn't know Linuxbrew is a thing. The problem is that this `fnm` binary is compiled to macOS and not for Linux.

In order to support Linuxbrew, we would probably require a change in https://github.com/Schniz/homebrew-tap/blob/9f7b6aff18f48a52f7e8b0739e582580b9e5204d/Formula/fnm.rb#L10 — adding `if OS.macos?` block and provide a link to the Linux build otherwise. Then you can do `fnm use` and `fnm exec -- node -v` and it should work as expected — it won't patch the global `node` for you.

But the installation script should work for you.

**Comment by dalisoft** [comment]
It before worked, so i am do not know, why it is before worked and after update did not

**Comment by Schniz** [comment]
The logs clearly say that it downloads the macOS version so I'm not sure how it worked in the first place. 🤷‍♂️ 

Maybe it downloaded it in another way? do you have some logs of the installation in a successful build? maybe that'll help

**Comment by dalisoft** [comment]
I don't have logs but i remember i am created wrong [issue](https://github.com/Schniz/homebrew-tap/issues/10)

**Comment by Schniz** [comment]
I really don't see how it could have worked 🤔
The binaries shouldn't be compatible between Linux and MacOS 🤷‍♂️
Maybe try going to the repository directory and go back with the commits until you find the one that worked out so we'll try fix the issue?

```
cd $(brew --repository Schniz/tap)
git reset HEAD~ # ...
```

**Comment by dalisoft** [comment]
I found issue why it's did not worked and created issue in needed repo.

Thanks. Wait for their reply

**Comment by Schniz** [comment]
Thanks for updating 😄
