### ISSUE TITLE
Empty version files undefined behavior

### ISSUE THREAD

**Issue by jonohayon** [Schniz/fnm#233]
Currently, when `fnm use` is called on a folder where there is an empty version file (either `.nvmrc` or `.node-version`), an obscure error is thrown to the user:
```
fnm: internal error, uncaught exception:
     (Failure hd)
```
The exit code is obscure too somewhat (125 on my machine), but at least it's different than 0 so it can be known that a problem occurred. When a file that includes only whitespace is used though, the problem is even worse, since the output is empty and the exit code is 0 (this could cause problems when someone uses fnm in CI, for example).

fnm version: v1.21.0
OS: macOS
OS version: 10.15.4
Shell: zsh

**Comment by Schniz** [comment]
Hmm, sounds like a bug! can be reproduced pretty easily. Hope I have the time to do that. Thanks for reporting!

**Comment by Schniz** [comment]
Hey @jonohayon, Thanks for filing the issue.
This bug should be fixed in the newer version. Please reopen if the issue persists!
