### ISSUE TITLE
fnm exec cli arguments are not passed down to scripts

### ISSUE THREAD

**Issue by jonohayon** [Schniz/fnm#234]
When running a command through `fnm exec` that requires the use of cli arguments, fnm will try to use these arguments as if they were its own and not the script's. For example, when running `fnm exec node --version`, the output will be the fnm version currently installed and not the current node version (of course you could run `fnm current` to get the node version, this is just an example).

fnm version: v1.21.0
OS: macOS
OS version: 10.15.4
Shell: zsh

**Comment by jonohayon** [comment]
Nevermind, used `fnm exec node -- --version` now and it worked

**Comment by Schniz** [comment]
> Nevermind, used `fnm exec node -- --version` now and it worked

Yup! that's how we need to do that. I'll explain for more context! 👯 
Thanks for sharing 🕺 💃 

---

CLI flags can be placed anywhere. So the following execution:
```
fnm exec node --version
```

is parsed like so:

```
fnm (pos:exec) (pos:node) (flag:--version)
```

and then works just like the following:

```
fnm --version exec node
```

What we want, is to act as if `--version` is not a flag, but a positional argument. That can be done using `--`, exactly like @jonohayon mentioned:

```
fnm exec -- node --version
```

this will be parsed like:

```
fnm (pos:exec) (pos:node) (pos:--version)
```

This will be parsed like you would think: `fnm exec (node --version)`

**Comment by jonohayon** [comment]
I think this should be added to the documentation somewhere, since I couldn't find any reference of `fnm exec` other than trying to see if it was implemented in my command line.
