### ISSUE TITLE
Usage with FNM

### ISSUE THREAD

**Issue by idkjs** [Schniz/fnm#236]
Sorry, in advance, for not being able to figure this out.

Issue is that vscode seems to not be able to find global bsb.

From where should I be sourcing `fnm` installed `node_modules`?

```sh
❯ which bsb
/var/folders/rt/7lc5vcw16459dszl8djk35fh0000gn/T/fnm-shell-7073504/bin/bsb

~
❯ which opam
/usr/local/bin/opam

~
❯ which fnm
/usr/local/bin/fnm

```

Should I set a path for `bsb`?

```sh
❯ set -U fish_user_paths (which bsb) $fish_user_paths

~
❯ echo $PATH | grep bsb
/var/folders/rt/7lc5vcw16459dszl8djk35fh0000gn/T/fnm-shell-7073504/bin/bsb . /Users/mandalarian/.opam/default/bin /var/folders/rt/7lc5vcw16459dszl8djk35fh0000gn/T/fnm-shell-7073504/bin /Users/mandalarian/.asdf/shims /usr/local/opt/asdf/shims /usr/local/opt/asdf/bin . /var/folders/rt/7lc5vcw16459dszl8djk35fh0000gn/T/fnm-shell-6222251/bin /usr/local/opt/asdf/shims /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/Apple/usr/bin /usr/local/go/bin /Applications/Racket v7.6/bin . /var/folders/rt/7lc5vcw16459dszl8djk35fh0000gn/T/fnm-shell-3341699/bin /usr/local/opt/asdf/shims /var/folders/rt/7lc5vcw16459dszl8djk35fh0000gn/T/fnm-shell-390024/bin
```

I am not sure how to ask this question. The goal is for vscode to know where global bsb is, if that makes sense. 

Thank you.

**Comment by Schniz** [comment]
Hey!

Is there a chance of making `bsb` (`bs-platform`, I guess) a dev dependency of your project? Being a global package may have weird implications like the inability to use different versions of BuckleScri.... Sorry, ReScript!

You can also take @peterpme's way when installing global packages https://peterp.me/global-node-modules-the-right-way/ —  It was discussed in the issues a couple of times, but now I personally use [gpkg](https://github.com/Schniz/gpkg) which is a binary that manages global installations for me. Never really published it though.

The idea in gpkg is — you installed a global package with a specific Node version, so the installation is pinned to that specific Node version and available globally in your system.

**Comment by idkjs** [comment]
So much good stuff in this commment, brother. BRB.
