### ISSUE TITLE
Usage with pm2

### ISSUE THREAD

**Issue by takase1121** [Schniz/fnm#238]
Correct me if I'm wrong:
In order to set the correct nodejs version with fnm, users is required to add two lines to bashrc. The first line adds fnm into path. The second line eval output from a fnm command. 
The fnm command generates PATH that should be appended to the shell's PATH.

The problem arises when I use pm2. If I don't set the intepreter in my ecosystem file, it will start node. However, this does not start a shell thus is unable to source correct PATH. 

Two ways of fixing this may be:
1. use the interpreter option and point it to "~/.fnm/aliases/default/bin/node" (I currently use this) 
2. Somehow pass the environment variable to PM2. To do this, the output of the aforementioned fnm command must be static so it always work. I am not sure if this is the case. 

I am not really sure what to do in this situation. Any guidance will be appreciated.

**Comment by Schniz** [comment]
Hey
There's also `fnm exec --using=X` which runs a process with the node version in PATH. Maybe that would help?

Sorry for the late responses. I'm kinda unavailable.

**Comment by takase1121** [comment]
That's interesting. Instead of putting a long path in the ecosystem, I could make it like
```
"interpreter": "fnm"
"interpreter_args": ["--using", "latest-v12.x"]
```

Which is quite clear by just looking at it. Nice tip!

**Comment by Schniz** [comment]
Glad it was clear! hope all is good 😄

**Comment by FFdhorkin** [comment]
> That's interesting. Instead of putting a long path in the ecosystem, I could make it like
> 
> ```
> "interpreter": "fnm"
> "interpreter_args": ["--using", "latest-v12.x"]
> ```
> 
> Which is quite clear by just looking at it. Nice tip!

Just in case anyone else sees this, don't forget to put `exec` at the start of your `interpreter_args` array
