### ISSUE TITLE
Wrong filename in v1.2.0 Linux archive

### ISSUE THREAD

**Issue by drazik** [Schniz/fnm#24]
I tried to install fnm on my ubuntu, but when I executed the install command (`curl https://raw.githubusercontent.com/Schniz/fnm/master/.ci/install.sh | bash`) I had the following error:

```
mv: impossible d'évaluer '/tmp/tmp.Op2bPEFVJX/fnm-linux/fnm': Aucun fichier ou dossier de ce type
```

My system is in french, but it means that `/tmp/tmp.Op2bPEFVJX/fnm-linux/fnm` doesn't exist. It is because the bin contained in the `fnm-linux.zip` archive is not named `fnm`, but `fnm-linux`:

```
ll /tmp/tmp.Op2bPEFVJX/fnm-linux/
total 14M
-rw-r--r-- 1 drazik drazik 14M janv. 30 13:49 fnm-linux
```

Since the file in the macOS archive is named `fnm`, I assume this is just a mistake while packing the Linux archive.

I easily worked around this issue by forking the repository and updating `.ci/install.sh`

```diff
-  mv $DOWNLOAD_DIR/$FILENAME/fnm $HOME/.fnm/fnm
+  mv $DOWNLOAD_DIR/$FILENAME/$FILENAME $HOME/.fnm/fnm
```

But I just wanted to let you know that there is an issue preventing from installing fnm by just running the command in the README on Linux ;)

EDIT: actually I just looked at other release, it seems that this is like this from the beginning.

**Comment by Schniz** [comment]
whooooooops. totally right. Great catch. Unfortunately, the following won't work:

```diff
-  mv $DOWNLOAD_DIR/$FILENAME/fnm $HOME/.fnm/fnm
+  mv $DOWNLOAD_DIR/$FILENAME/$FILENAME $HOME/.fnm/fnm
```

because on Mac, `$FILENAME` is `fnm-macos`. $25 changes the CI script to publish `fnm-linux/fnm` instead of `fnm-linux/fnm-linux`. 😄

**Comment by Schniz** [comment]
Version 1.2.1 will work on Linuxes too. 
Thanks again for opening the issue! 😄
