### ISSUE TITLE
Way to Easily Check if NPM command exists in shell / bash/ zsh

### ISSUE THREAD

**Issue by codeitlikemiley** [Schniz/fnm#240]
I have my aliases
Im checking every command in my system if they exists before i add an alias

I noticed that commands in $PATH are recognize
except those installed by fnm

I can add the path to the bin of fnm but since its dynamically generated , there is no way to check
for other system if i really have the same random generated bin folder...
e.g. `/tmp/fnm-shell-5222589/bin/npm` this will not be the same in any system i re installed my Arch set up

im using archlinux

```
if [ -x "$(command -v npm)" ]; then
alias \
    lb="npm run build \
    ;
fi

if [ -x "$(command -v netlify)" ]; then
alias \
   dev="netlify dev" \
    ;
fi
```

all other check works just fine except the ones installed via npm packages eg. netlify

is there a way to fix the path to bin folder??? like based on node version /bin/npm

this is not a big deal i did create a new alias without checking if command exist

**Comment by Schniz** [comment]
Hey friend!
Glad you're using fnm and I hope you like it.

These are some great questions and I hope the following answers will answer them!

> I noticed that commands in $PATH are recognize
> except those installed by fnm

Maybe you run the code you mentioned before running `eval "$(fnm env)"`?
The `fnm env` command outputs a new `$PATH` environment variable and every `command -v` call should happen after it to make it work.

> I can add the path to the bin of fnm but since its dynamically generated , there is no way to check
> for other system if i really have the same random generated bin folder...

The path is not dynamically generated. The current Node path is, but the executable will always be in the same place. Keep in mind that when you use fnm and install packages globally, _you're basically tying yourself to a specific version_.

I suggest reading @peterpme's [blog post about solving this problem](https://peterp.me/global-node-modules-the-right-way/) or considering [trying gpkg](https://github.com/Schniz/gpkg), which I really need to make a formal release for.

> is there a way to fix the path to bin folder??? like based on node version /bin/npm

I hope that the comment was helpful, but this is a nice addition (I want to believe so, at least):

Using the [realpath](https://man7.org/linux/man-pages/man1/realpath.1.html) command you can get a path after unfurling the symlinks:

```
◦ realpath /var/folders/cs/pr19qm154hxcg8_zvbrjwy91l6v056/T/fnm_multishell_1370_1600074502248/bin/node
/Users/galsc/.fnm/node-versions/v12.6.0/installation/bin/node
```

**Comment by Schniz** [comment]
I'm closing since I have answered the questions. Please reopen if there are still more issues or questions! I'd be happy to help.

**Comment by codeitlikemiley** [comment]
Totally make sense since my aliases is define prior `eval "$(fnm env --multi)"`

actually is the last line of my .zshrc...

thanks for the great tip 👍👍👍

**Comment by codeitlikemiley** [comment]
That did the trick ive just fixed my zshrc 
re arrange my aliases to be source after it evaluates all the ENV Variable PATH

**Comment by Schniz** [comment]
👍 
Glad it helped!
Have a great one :)
