### ISSUE TITLE
fnm hangs on WSL

### ISSUE THREAD

**Issue by osyrisrblx** [Schniz/fnm#241]
```
❯ fnm ls-remote
Looking for some node versions upstream...
fnm: internal error, uncaught exception:
     Unix.Unix_error(Unix.ETIMEDOUT, "connect", "")
```

This is a fresh install on Ubuntu WSL. Tried the past several versions of fnm, but they all gave the same result.

**Comment by Schniz** [comment]
Sorry about that. I don't really know WSL — should it behave just like a plain Ubuntu?
Can you do `curl https://nodejs.org/dist/index.json`? does it work?

I'm working on https://github.com/Schniz/fnm.rs that should work on Mac, Linux and Windows. Would you want to try that on your machine?

**Comment by osyrisrblx** [comment]
> Can you do curl `https://nodejs.org/dist/index.json?` does it work?
Yep, works instantly and gives me a JSON result back as expected.

Not sure what the issue is, and I'm not familiar enough with Reason to debug locally.
I'll try out the Rust version!

**Comment by osyrisrblx** [comment]
I'm not sure what the difference is, but the Rust verison of fnm works flawlessly! I'll use that for now on, thanks!

**Comment by Schniz** [comment]
I hope to merge the repos soon. Glad it works!

**Comment by mayank-suman** [comment]
Updating to the latest version fix this for me.
