### ISSUE TITLE
fnm: illegal hardware instruction (core dumped)

### ISSUE THREAD

**Issue by ms2052001** [Schniz/fnm#273]
I think these commands describe the problem I have.
![image](https://user-images.githubusercontent.com/42011920/96347231-88bf9200-10a0-11eb-9bfa-cc658871d591.png)
------------------
When I type `sudo fnm`, some think weird happens:
```
❯ sudo fnm
sudo: fnm: command not found
```
-----------------
My `~/.bash_profile` contains these lines:
```bash
 ######### for fnm                                                                          
 export PATH=/home/ms/.fnm:$PATH                                                            
 eval "`fnm env --multi`"  
```
-----------------
I hope anyone can help me with tins.

**Comment by Schniz** [comment]
Hey, can you please upgrade to the latest version of fnm and see if it still happens? 😄
