### ISSUE TITLE
fnm no longer works on macos

### ISSUE THREAD

**Issue by folke** [Schniz/fnm#278]
Fnm v1.22 crashes on Macos.

```shell
$ fnm --version
Killed: 9
```

**Comment by Schniz** [comment]
how did you install it?

**Comment by Schniz** [comment]
...and what MacOS version are you using?

**Comment by folke** [comment]
I upgraded to the new version with `brew upgrade`, but a reinstall gives the same issue.

**Comment by folke** [comment]
Running on the latest public beta of Big Sur 11.0 Beta (20A5395g)

**Comment by Schniz** [comment]
And did fnm v1.21 worked well for you? I don't have Big Sur so I can't really test. I wonder if it's related to new permissions or code signing

Can you try downloading a binary from the releases and see if you can [download the zip from the latest release](https://github.com/Schniz/fnm/releases/download/v1.22.0/fnm-macos.zip), unzip it and try to run `./fnm --version` with this version? 🤔

**Comment by folke** [comment]
Same problem with the download.

GDB: (not all that helpful I guess 🙂)
![image](https://user-images.githubusercontent.com/292349/97102396-50045780-1662-11eb-85d9-d686ff25c858.png)

**Comment by folke** [comment]
v1.21 works fine

**Comment by folke** [comment]
I just manually downloaded the v1.21 again and that works.

**Comment by Schniz** [comment]
Probably related to a dynamic library. I'll download v1.21.0 and see the difference

**Comment by folke** [comment]
Running `otool -L`:
v1.21
```
/usr/local/bin/fnm:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
```

v1.22
```
../fnm:
```

**Comment by folke** [comment]
With `dtruss`:
```shell
$ sudo dtruss ./fnm
Password:
dtrace: failed to execute ./fnm: Bad executable (or shared library)
```

**Comment by Schniz** [comment]
I wonder if that will work. I used `upx` to compress the file sizes for download, but maybe it causes issues on Big Sur? So the following file is the decompressed binary:
[fnm.zip](https://github.com/Schniz/fnm/files/5434334/fnm.zip)

when decompressing it, these are the dependencies:

```
fnm:
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 59306.140.5)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by Schniz** [comment]
I'd be happy if you can build fnm locally, then we might see the difference

**Comment by folke** [comment]
The decompressed binary works!

**Comment by Schniz** [comment]
Okay! So I'm dropping the compression. I'll ping you in a couple of minutes to test it again 😁 
Thanks!

**Comment by folke** [comment]
Sweet, thanks!

**Comment by Schniz** [comment]
@folke can you please try to upgrade using homebrew?

**Comment by folke** [comment]
@Schniz upgraded version works as expected. Thanks again for the quick turn-around!

**Comment by Schniz** [comment]
Thank you for the quick responses 😁
