### ISSUE TITLE
Error when opening a terminal in VS Code on OS X

### ISSUE THREAD

**Issue by ujwal-setlur** [Schniz/fnm#285]
I use ```fish``` as my shell

With the latest update today, When I open a terminal in VS Code, I get this message:

```
thread 'main' panicked at 'Can't infer shell', src/shell/mod.rs:28:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The shell is usable after this, but ```node``` and ```npm``` are not found anymore. I have start a new ```fish``` session for those to be found.

This does not happen on iTerm2 or Terminal.app

**Comment by Schniz** [comment]
Thanks for reporting. I see the problem and I'm opening a PR!

**Comment by ujwal-setlur** [comment]
Thank you, this is resolved for me now!
