### ISSUE TITLE
docs: Azure Pipelines badge should be replaced

### ISSUE THREAD

**Issue by jameschensmith** [Schniz/fnm#288]
If my understanding of the most recent changes is correct Azure Pipelines is no longer being used. Given that GitHub Actions (GHA) is now being used, a suggestion would be to replace the badge with one for the main GHA workflow. I could send in a PR to address this if this is the route you would like to take :blush: 

Example badge (if you prefer something else, don't hesitate to add your recommendation :slightly_smiling_face:):
<a href="https://github.com/Schniz/fnm/actions"><img src="https://img.shields.io/github/workflow/status/Schniz/fnm/Rust/master?label=workflow" alt="GitHub Actions workflow status" /></a>

**Comment by Schniz** [comment]
Thanks! do you want to open a PR that replaces that? 😄

**Comment by jameschensmith** [comment]
Yep! I'll open up one shortly 😊 👍
