### ISSUE TITLE
Alias support

### ISSUE THREAD

**Issue by Schniz** [Schniz/fnm#29]
```bash
fnm alias v8.11.3 my-name

fnm use my-name # like `fnm alias v8.11.3`
```

After that, we can make #6 happen (by having an alias of `system` to the system's node 😄)

**Comment by CWSpear** [comment]
This is all inter-related. You can't `fnm install node` or `fnm install lts/carbon`, which is literally the only types of things I use `nvm` for. :) It appears to _only_ support explicit versions at the moment (tho looks like this is all on the roadmap on the README).

**Comment by Schniz** [comment]
@CWSpear, hey and sorry about that. Internally, `fnm` just looks at the directory listing of https://nodejs.org/dist - so if you want to keep your current workflow, just use the following names:

* `nvm install node` => `fnm install latest`
* `nvm install lts/carbon` => `fnm install latest-carbon`

both should work 😄

**Comment by CWSpear** [comment]
We use `lts/carbon` in our `.nvmrc`. So it'll only work if it's `latest-carbon`? It's not something I can change cuz it's a large project.

**Comment by Schniz** [comment]
>We use `lts/carbon` in our `.nvmrc`. So it'll only work if it's `latest-carbon`? It's not something I can change cuz it's a large project.

@CWSpear we can add a PR that formats `lts/VERSION` as `latest-VERSION` 😃 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
