### ISSUE TITLE
missing command: uninstall

### ISSUE THREAD

**Issue by christiantakle** [Schniz/fnm#291]
Updated from brew and wanted to setup my system from scratch (i.e. uninstall all current managed versions from fnm).

```
fnm uninstall v12.19.0
error: The subcommand 'uninstall' wasn't recognized
	Did you mean 'install'?

If you believe you received this message in error, try re-running with 'fnm -- uninstall'

USAGE:
    fnm [OPTIONS] <SUBCOMMAND>

For more information try --help
```
cli: Check help; nothing

github: something
https://github.com/Schniz/fnm/blob/master/README.md#fnm-uninstall-version

check src; nothing
https://github.com/Schniz/fnm/blob/master/src/cli.rs#L33

**Comment by Schniz** [comment]
I noticed it a couple of hours ago too. Thanks for filing it. a PR is on its way!
