### ISSUE TITLE
Node version scoped to current shell only

### ISSUE THREAD

**Issue by krzkaczor** [Schniz/fnm#294]
Is it possible to have two shells opened with different node versions? My use case (with cd integration enabled):

1. I enter dir X with.
2. `fnm use` recognizes .nvmrc and changes node version to 10
3. In a separate shell i open dir Y.
4. `fnm use` recognizes .nvmrc and changes node version to 14
5. In the first shell (in dir X) i run `node --version` and it's 14 instead of 10.

I would expect that any changes made by `fnm use` would be scoped to the current shell only. 

Am I missing something?

**Comment by Schniz** [comment]
Which fnm version are you using? That's exactly how fnm works. The newer version even deprecated the `--multi` flag and now this is the default.

Here's it in asciinema — https://asciinema.org/a/IS2hH7FLb8sTVRmWDQ1AgqPTr
do you get other behavior from fnm?

**Comment by krzkaczor** [comment]
I am on `1.21.0`. 

Thanks for your quick response, this has to be something on my end.

**Comment by Schniz** [comment]
in fnm 1.21.0 you still need to do `fnm env --multi`. on 1.22.0 onwards you don't need the `--multi` 😄 

thanks for using fnm!

**Comment by krzkaczor** [comment]
Oh, wow I installed `fnm` literally just a week ago :O I didn't realize that the pace of development is so fast 😆  Upgrading wasn't that smooth as I needed to manually tweak config generated into `.zshrc` but everything works now 👍 

Thanks for creating this tool! It's a great replacement for `nvm`.

**Comment by Schniz** [comment]
Happy to help!
