### ISSUE TITLE
can't infer shell in terminal (webstorm)

### ISSUE THREAD

**Issue by nikravi** [Schniz/fnm#296]
Hello,

I'm able to run the latest version 1.22.1 of fnm in the terminal with zsh bash, however webstorm doesn't play nice with it

```
➜ fnm env
thread 'main' panicked at 'Can't infer shell', src/shell/mod.rs:28:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I tried to run `fnm env`, `fnm use` and I get the same exception. Any ideas how to fix this?

Thanks!

**Comment by Schniz** [comment]
Yes, this was fixed in #290. I'm going to release today a new version that fixes that, sorry about that 😄

**Comment by perkrlsn** [comment]
@Schniz same for `vscode` btw, will the new release fix that as well? :)

**Comment by Schniz** [comment]
yes! 😄

**Comment by perkrlsn** [comment]
Sweet, thanks @Schniz 🎆

**Comment by Schniz** [comment]
Hi, this was released in https://github.com/Schniz/fnm/releases/tag/v1.22.3
Please reopen if the problem persists! I hope it fixed the issue. 😄

**Comment by perkrlsn** [comment]
@Schniz Works like a charm :)
