### ISSUE TITLE
Optional leading "v" can cause problems

### ISSUE THREAD

**Issue by bjohn465** [Schniz/fnm#298]
According to [the output of `nvm --help`](https://github.com/nvm-sh/nvm/blob/v0.36.0/nvm.sh#L2387), a "version-like string" can be:
> full or partial version numbers, starting with an optional "v" (0.10, v0.1.2, v1)

It seems that `fnm` only expects the optional "v" for full version numbers (e.g. "v14.14.0"). Partial version numbers that have a leading "v" (e.g. "v14.14", "v10", or "v14.x") will fail.

Would it be possible to support an optional leading "v" for all version patterns?

**Comment by Schniz** [comment]
IIRC, partial versions are supported with and without the `v` prefix 😃

I'm afk right now so tomorrow I will check but I'm 99% sure..

Do you have a specific issue you're facing with?

**Comment by bjohn465** [comment]
I have a project that has "v10.22" specified in the `.nvmrc` file. When I `cd` into that project (or run `fnm use` within the project directory), I get:
> error: Can't find version in dotfiles. Please provide a version manually to the command.

I have a `v10.22.1` listed in `fnm ls`, which is the version I would expect would be used.

I also tried this is a new, empty directory with various values in `.nvmrc`, but got the same result with a partial version number with a leading "v".

`fnm use v10.22` results in a slightly different error:
> error: Invalid value for '<version>': expected more input

**Comment by bjohn465** [comment]
Also, an apology as I should have included the error information in the original description. Also, this is with version 1.22.3 of `fnm`.

And don't worry about getting to it tomorrow (or next week, or whenever 🙂).
