### ISSUE TITLE
Does not work with MacOS Big Sur Beta

### ISSUE THREAD

**Issue by navxio** [Schniz/fnm#309]
Don't think the version of MacOS matters. Here's the output of `fnm env`

`export PATH="/var/folders/gk/vbr0r1914mx22rfyq7wmq9y40000gn/T/fnm_multishell_70411_1603896631979/bin":$PATH
export FNM_MULTISHELL_PATH="/var/folders/gk/vbr0r1914mx22rfyq7wmq9y40000gn/T/fnm_multishell_70411_1603896631979"
export FNM_DIR="/Users/nav/.fnm/"
export FNM_LOGLEVEL="info"
export FNM_NODE_DIST_MIRROR="https://nodejs.org/dist"`

and here's an excerpt of my .zshrc
`eval "$(fnm env --use-on-cd --shell=zsh --multi)"`

**Comment by Schniz** [comment]
What is the error?

**Comment by navxio** [comment]
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/9297865/97453122-71638d00-195b-11eb-8e6b-eeddc62e388c.png">
The node version doesn't change...

**Comment by Schniz** [comment]
Can you please write here what do you have in `$PATH`?

```
echo $PATH
```

**Comment by navxio** [comment]
`
/usr/local/opt/ansible@2.8/bin:/var/folders/gk/vbr0r1914mx22rfyq7wmq9y40000gn/T/fnm_multishell_70876_1603896776695/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/nav/.fnm/current/bin:/usr/local/sbin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby/bin:/Users/nav/.cargo/bin/
`

**Comment by Schniz** [comment]
does `/var/folders/gk/vbr0r1914mx22rfyq7wmq9y40000gn/T/fnm_multishell_70876_1603896776695/bin` exist?
```
ls -lah /var/folders/gk/vbr0r1914mx22rfyq7wmq9y40000gn/T/fnm_multishell_70876_1603896776695
```

Can you also try:

```
fnm exec --using=12 -- node --version
```
?

**Comment by navxio** [comment]
it does apparently
`lrwxr-xr-x  1 nav  staff    51B Oct 28 20:23 /var/folders/gk/vbr0r1914mx22rfyq7wmq9y40000gn/T/fnm_multishell_70876_1603896776695 -> /Users/nav/.fnm/node-versions/v12.13.0/installation`

and 
`fnm exec --using=12 -- node --version`
returns 15.0.1

**Comment by Schniz** [comment]
does `/Users/nav/.fnm/node-versions/v12.13.0/installation/bin/node` exist? 🤔

**Comment by navxio** [comment]
nope

**Comment by navxio** [comment]
`
block-plugins/faq-accordion feature/composition-dashboard ➜  fnm install
Installing Node v12.13.0
warning: Version already installed at "/Users/nav/.fnm/node-versions/v12.13.0"
block-plugins/faq-accordion feature/composition-dashboard ➜`

**Comment by Schniz** [comment]
but please tell me what you have in `/Users/nav/.fnm/node-versions/v12.13.0/installation/bin` before that!

**Comment by navxio** [comment]
there are 3 executables
`node npm npx`

**Comment by Schniz** [comment]
But you just said that `/Users/nav/.fnm/node-versions/v12.13.0/installation/bin/node` does not exist 🤔

**Comment by navxio** [comment]
@Schniz Sorry I uninstalled and installed node 12.13.0

**Comment by Schniz** [comment]
and does it work now?

**Comment by navxio** [comment]
still doesn't :(

**Comment by navxio** [comment]
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/9297865/97454940-51cd6400-195d-11eb-856e-56184361fe90.png">

**Comment by Schniz** [comment]
Do you want to chat over Discord/Telegram and try to figure this out?

**Comment by navxio** [comment]
absolutely (discord)

**Comment by Schniz** [comment]
I'm `schniz#8672` 😁

**Comment by Schniz** [comment]
Okay so we fixed it, we don't really know why it happened but we suspect it has something to do with the default alias. I highly doubt it but maybe Big Sur handles symlinks differently? who knows.

So for now, #304 is setting a default version for the first version we install using fnm. Let's hope for the best!

Thanks @navxio for opening the issue 😁

**Comment by navxio** [comment]
@Schniz the issue resurfaced after I tried to `fnm use system`. Now I can't use the project specific node version at all.
