### ISSUE TITLE
Request: Rename 'env' command as 'init'

### ISSUE THREAD

**Issue by jameschensmith** [Schniz/fnm#311]
I've been letting this bake for a little bit before requesting this, but I would like to hear your thoughts on this now :slightly_smiling_face: I'm a huge fan of the [`starship` prompt](https://github.com/starship/starship), and have been watching the development of the project for some time now. I think there would be much benefit in looking to it as a model project for `fnm`. Let's focus in on one (small but rather significant) benefit for this issue, though (I would **love** to talk more on some things we can learn from them; perhaps you can reach out to me, or I could create a separate issue to jot them down; let me know! :grin:).

I think `env` has outlived its name. With `--use-on-cd`, we are already going outside of just setting environment variables, which is the current description of the command:

> Print and setup required environment variables for fnm 

If we apply `starship` as our model, I think a better name for the command could be `init`. `init`, or initialize, sends a different message to the user that: (1) it should be called once per shell session, (2) most of the variables shouldn't be overridden (though, some are allowable; notably my favorite, pointing `FNM_DIR` to an XDG-compliant directory :wink:). With `env`, I personally tend to confuse it with checking what the current environment is set to for `fnm` (a fantastic example of this to support this confusion would be `go env`).

Okay, so, how would we do it? We could remove `env` and replace it with `init`, but this would make for very unhappy users :sweat_smile: I think we could do the following:

1. Add a deprecation notice to `env`, and remove **all** references of it to avoid new users using it (even hiding it from usage if possible)
2. Duplicate the logic for a new `init` command, providing this to users as the desired implementation
3. Remove the `env` command in either a major or minor release (since we are < 1.0.0; perhaps a minor version removal could be possible).

That's all I have for now, but I'm looking forward to any input/feature that comes out of this :blush::+1:

**Comment by Schniz** [comment]
Hi, that really makes sense, but I think the cost is pretty high. Since we're >1.0.0 (1.22.5 to be exact as I'm writing this), and I don't have any ideas what would v2 bring to the world, keeping `fnm env` deprecated for so long wouldn't be that nice - especially that it is something that every fnm user has.

I think we can rename it to `init`, and keep `env` as an alias — to match `docker-machine`, which is where the name is from, and I think there are more tools that use this name. 🤔  I wonder what other users think about this before doing this massive change 😄 

Regardless, the "print and setup required environment variables for fnm" should change to something like

```
Output the required shell commands to set up an fnm session
```

what do you think?

**Comment by jameschensmith** [comment]
> Since we're >1.0.0 (1.22.5 to be exact as I'm writing this) [...]

Oof, not sure why I forgot about the version being >1.0.0. It was pretty late when I posted this 🙈 

> I don't have any ideas what would v2 bring to the world, keeping `fnm env` deprecated for so long wouldn't be that nice - especially that it is something that every fnm user has.

That's a totally valid point. I do have some other ideas which _could_ eventually add up to a potential `v2` release, but it would still be a long time until that release would happen.

> I think we can rename it to `init`, and keep `env` as an alias [...]

Yeah, an alias would be the safest practice. Would you want to keep it as an alias long term, or would you want to mark it as deprecated and hide it from usage? Curious to know your/everyone's thoughts on this point.

> Regardless, the "print and setup required environment variables for fnm" should change to something like
> 
> ```
> Output the required shell commands to set up an fnm session
> ```
> 
> what do you think?

I think it could be as simple as:

```
Outputs the required shell commands to set up fnm
```

But if you want it to be clear that `fnm` is closely tied to shell sessions, you could do that. As you are the owner of the code, I leave that to your preference 😊

**Comment by jameschensmith** [comment]
Closing this, as I haven't heard anything on this in a while. It will also make your open issue count look better 😉  If you happen to want to reinvestigate this later, you can open it again. The offer to reach out for further discussion will still be open too! 🙂
