### ISSUE TITLE
What tool did you use to make the animated SVG gif demo on the README?

### ISSUE THREAD

**Issue by fieu** [Schniz/fnm#312]

**Comment by fieu** [comment]
You can close this right after it just looks so nice haha!

**Comment by Schniz** [comment]
Hehe, happy you liked it. It is based on create-react-app's SVG, and the tool is [svg-term-cli](https://github.com/marionebl/svg-term-cli) 😄 

the entire recording script is here: https://github.com/Schniz/fnm/blob/master/docs/record_screen.sh

if you have more questions let me know 😄
