### ISSUE TITLE
🐛fnm/windows ~ `fnm install 6` fails with "...The filename or extension is too long. (os error 206)"

### ISSUE THREAD

**Issue by rivy** [Schniz/fnm#313]
I've been able to install several later versions (4, 8, 10, 12, and 14) without incident, but trying to install v6 fails (for multiple 6.x.x versions).

```text
C:>ver
Microsoft Windows [Version 10.0.18363.1082]

C:>fnm --version
fnm 1.22.5

C:>fnm install 6.17.0
Installing Node v6.17.0
error: Can't download the requested version: Can't extract the file: The filename or extension is too long. (os error 206)
```

I can hack it into an otherwise successful operation by manually installing the version myself from the file available on "https://nodejs.org/dist". So, I've worked around it, but I thought you might want to know/fix it.

And, btw, thanks for the creating the tool!

**Comment by Schniz** [comment]
Maybe the fix we had is not good enough so I need to install the VM again 😛 
It assumes you have enabled long paths in the Windows config or something like that. Did you enable it?

**Comment by rivy** [comment]
> Maybe the fix we had is not good enough so I need to install the VM again 😛
> It assumes you have enabled long paths in the Windows config or something like that. Did you enable it?

Yep, I'm running Windows 10 in developer mode with long paths enabled. Although, I believe that if you use UNC paths, that shouldn't be needed. All non-v6 versions do install without issue (including the v4 and v8 versions which bookend the problem version).

Unzipping the v6.17.1 archive into the "%USERPROFILE%\.fnm\node-versions\v6.17.1\installation" directory works just fine as well, leaving me with a working installation.

Thanks for looking into it.

**Comment by rivy** [comment]
@Schniz , any progress?

**Comment by Schniz** [comment]
Nope. First, I do not own a Windows machine and will appreciate any help I can get here. Second, I'm in a pretty intense period at work/life so I'm genuinely sorry for being low key. 

I believe that there is another way of using long paths in windows. Can you try contributing? 🙏 

It would be also extremely helpful if I could use GH Codespaces on a Windows machine!
