### ISSUE TITLE
Use behind a corporate proxy

### ISSUE THREAD

**Issue by XiaofengXie16** [Schniz/fnm#314]
Is there an option where I could add a certificate to use this tool given that I want to use this tool behind a corporate proxy?

Currently, I am seeing this error.
HttpError: error sending request for url (https://nodejs.org/dist/index.json): error trying to connect: invalid certificate: UnknownIssuer

**Comment by Schniz** [comment]
Hi, I'm going to need to know more details. What OS are you using? what version of fnm?
Thanks

**Comment by skyrex-mark** [comment]
10.15: "Catalina"
fnm version: 1.22.6
Note: NVM works fine behind the proxy

**Comment by Schniz** [comment]
Can you try building fnm on your machine and tell me if it is working well?
I wonder if I should not use `rustls` on Mac 🤔 maybe use it only on ARM

**Comment by zicklag** [comment]
I'm getting a possibly related issue when running behind a corporate proxy with authentication and a custom certificate ( which I have trusted on my machine and which works will most other apps such as `curl` ). I'm on Pop!_OS ( Ubuntu ) 20.04 and I get the following error:

```
[2020-11-23T21:10:45Z ERROR rustls::session] TLS alert received: Message {
        typ: Alert,
        version: TLSv1_2,
        payload: Alert(
            AlertMessagePayload {
                level: Fatal,
                description: HandshakeFailure,
            },
        ),
    }
error: HttpError: error sending request for url (https://nodejs.org/dist/index.json): error trying to connect: received fatal alert: HandshakeFailure
```

**Comment by zicklag** [comment]
Ah, I was able to fix it by disabling the `rustls-tls` feature in `reqwests` and by re-enabling the default features ( which just enables the `default-tls` feature ). It's probably due to RusTLS failing to trust the system certificate.

**Comment by Schniz** [comment]
Oh cool, thanks for checking it out! 
we probably need to use `rustls-tls` only on ARM 😄

**Comment by pfiaux** [comment]
I ran into a similar issue, I'll need to retest with the latest release which has the newest `reqwests` version to make sure it still happens.

Looking at their doc tho it seems `rustls-tls` is equivalent to `rustls-tls-webpki-roots` (https://docs.rs/reqwest/0.11.3/reqwest/#optional-features). Can it be combined with `native-tls` or perhaps `rustls-tls-native-roots`? If they're not exclusive that might allow using the configured certificates on the host as well.

**Comment by pfiaux** [comment]
I've tested with `rustls-tls-native-roots` (keeping `rustls-tls` as well):
```
reqwest = { version = "0.11.3", features = ["blocking", "json", "rustls-tls", "rustls-tls-native-roots", "brotli"], default-features = false }
```
It worked without proxy and with proxy (if someone wants to try it before it lands `cargo install --path ./` worked out for me).

I didn't look at the difference between `rustls-tls-native-roots` and `native-tls`.

**Comment by michahell** [comment]
I am getting a similar error on Windows 10 20H2 while having installed via chocolatey: `choco install fnm`

`error: Can't download the requested binary: HttpError: error sending request for url (https://nodejs.org/dist/v16.13.1/node-v16.13.1-win-x64.zip): error trying to connect: invalid certificate: UnknownIssuer`

**Comment by cko-jimmy-wong** [comment]
Same issue here. @pfiaux care to submit a PR?

**Comment by zicklag** [comment]
I use fnm on Linux behind a proxy with a custom SSL certificate, but I have to use the `default-tls` feature for the `requests` crate ( which might be default in `fnm` by now, I can't remember ), and I have to trust the proxy certificate in my system certificate store.

I'm not if it works on Windows, but have you trusted your proxy certificate in your Windows network settings. If I remember correctly, it's kind of in the internet explorer settings.

**Comment by cko-jimmy-wong** [comment]
I'm on macOS and I'm getting UnknownIssuer on 1.28.2. #468 was removed but there's no equivalent replacement. How should I bypass this problem?

**Comment by zicklag** [comment]
@cko-jimmy-wong worst case scenario you can just apply [these changes](https://github.com/Schniz/fnm/pull/468/files) and build it from source to use it behind a proxy.

@Schniz will have to decide what the best way to support all platforms is being that it seems like some platforms work better with different features enabled, but if you are find building from source, then that should work for you for now.

**Comment by Schniz** [comment]
I probably forgot to apply the feature when I reverted. We can do this again

**Comment by pfiaux** [comment]
Indeed looks like https://github.com/Schniz/fnm/pull/586/files doesn't include `"rustls-tls-native-roots"`. I'll open a PR when I can to re-introduce it (and maybe then close this issue since there was no comments while it was in place =] )

The revert mentions testing, the proxy might be testable in a container given that there's a small proxy that can run in the container too. Maybe something like https://dev.to/andre/docker-restricting-in--and-outbound-network-traffic-67p could be used to drop the non proxy traffic, so that the test fails if it doesn't use the proxy. Then there would be the tls part... sounds like it would make for one big e2e test to check all that!

**Comment by Schniz** [comment]
This should be fixed already! Thanks @pfiaux! 🙌
