### ISSUE TITLE
The --using-file command line argument is no longer present

### ISSUE THREAD

**Issue by alexjeffburke** [Schniz/fnm#316]
Hi there,

At my $work there are scripts calling `fnm` with a `--using-file` argument and it seems that as of the rust rewrite that is no longer supported. On that basis, there might be some compatibility breakage in the new version.

I'm not totally sure why we were using this argument when choosing the node version because it would seem to be default behaviour - my _guess_ is that the script calling `fnm` this wanted to make sure it bailed out if it was not able to use the node version specified in (in our case) `.nvmrc` rather than continue with some other default.

Thanks!

**Comment by bjornua** [comment]
It seems like this flag is now the default behaviour? https://github.com/Schniz/fnm/blob/9ba282a705c7a8f3d2dfbfb08d4c62720f600676/src/commands/exec.rs#L23-L29

Would it make sense to add the `using-file` flag back with a deprecation warning?

**Comment by Schniz** [comment]
@alexjeffburke I'm really sorry I didn't remember it. We should have better test coverage!
Thanks for opening the issue. Keep safe

**Comment by alexjeffburke** [comment]
> @alexjeffburke I'm really sorry I didn't remember it. We should have better test coverage!
> Thanks for opening the issue. Stay safe

Oh hey no worries at all - appreciate your jumping on a solution and same to you :)
