### ISSUE TITLE
Allow downloading versions from a Node.js mirror

### ISSUE THREAD

**Issue by haishanh** [Schniz/fnm#32]
This is a feature request.

When I already have `~/.fnm/downloads/v11.9.0.tar.xz` exists on disk, if I run `fnm install 11.9.0`, I would like fnm to try to unarchive it first and starting to download the fresh package only if unarchive exits with none zero status.

I use Taobao's node dist mirror. It's faster than Nodejs's 1st party one since I'm in China.(Taobao is a Alibaba company)

As a example:

```
# I use this url
https://npm.taobao.org/dist/v11.9.0/node-v11.9.0-darwin-x64.tar.xz
# instead of
https://nodejs.org/dist/v11.9.0/node-v11.9.0-darwin-x64.tar.xz
```

**Comment by Schniz** [comment]
Interesting: there's already #27, but that's not what you're talking about.
Looking for an existing archive feels like treating the symptom and not the actual problem we have:
I guess we can also support `npm.taobao.org`, only by changing the hard-coded `https://nodejs.org` to an environment variable.

Do you think it is a better fix for the problem? 😄 

```
eval `fnm env --node-dist-url="https://npm.taobao.org/dist"`
# then everything as expected
fnm install v11.9.0
```

**Comment by haishanh** [comment]
Yes! that would be better. 😀

I use [`tj/n`](https://github.com/tj/n) before trying out fnm. You can almost do the same thing https://github.com/tj/n/blob/master/bin/n#L32

**Comment by Schniz** [comment]
Amazing. Can you please edit the title of this issue then? Something like "Allow downloading versions from a Node.js mirror" 😄

**Comment by haishanh** [comment]
Done. Thanks :)

**Comment by haishanh** [comment]
Also, to keep it simple I don't think it's worth it to implement a new option (here `--node-dist-url`) for `fnm env` command. Reading an env var with a default value directly inside fnm is enough IMHO.

**Comment by Schniz** [comment]
I generally agree about this, but I somehow liked the idea of making environment variables an internal implementation (since we already have a call that generates environment variables). It feels like a typed interface 😜 

That being said, it can always be set manually (right after/before the `fnm env`), but co-locating it with the `fnm env` command makes it clear what is it for (and how to get information about it, using `--help` 😄)

**Comment by haishanh** [comment]
Yeah, that makes sense.
