### ISSUE TITLE
`--use-on-cd` doesn't Work if Terminal Opens in Directory and doesn't Switch Back to Default

### ISSUE THREAD

**Issue by tsndr** [Schniz/fnm#320]
Some editors do have an integrated terminal which opens directly in the project folder. In that case the node version isn't selected, so I came up with my own solution, but it would be nice to support this scenario out of the box. My solution also fixes that it doesen't switch back to the default version once I leave the project directory.

## My solution `.bash_profile`
It's not the pretties but it works 😅
```bash
eval "$(fnm env)"
[ -s "/usr/local/opt/fnm/etc/bash_completion.d/fnm" ] && . "/usr/local/opt/fnm/etc/bash_completion.d/fnm"
_fnmcd() {
    cd $@
    (([ -s .node-version ] || [ -s .nvmrc ]) && fnm use || fnm use default) &> /dev/null
}
alias cd=_fnmcd
_fnmcd .
```

**Comment by Schniz** [comment]
Thanks! I'm using Zsh so it's done automatically using the shell hooks.
So the change here is the `_fnmcd .`  after declaring the bash function, right?

Regarding:

> My solution also fixes that it doesen't switch back to the default version once I leave the project directory

I don't really understand the issue. can you please elaborate?

**Comment by tsndr** [comment]
## Current Behavior
This is `fmn`'s out of the box behavior.

`.bash_profile`
```bash
eval "$(fnm env --use-on-cd)"
```

### 1. Scenario: Editor
I open my editors terminal, which starts in my project directory so the `--use-on-cd` hook never runs.

### 2. Scenario: Leaving project directory
If I leave the project directory using `cd ..` `fnm` doesen't switch back to my default nodejs version.

## Expected Behavior
The behavoir I'd expect from `fnm` and what my solution fixes.

### 1. Scenario: Editor
I open my editors terminal, therfore my `.bash_profile` is executed and `_fnmcd .` runs my function which checkes if there's a `.node-version` or `.nvmrc` file and runs `fnm use`.

### 2. Scenario: Leaving project directory
Once I leave the project directiory using `cd ..` and since I set an alias to overwrite the `cd` command, it checks again for a `.node-version` or `.nvmrc` file and since it doesn't exist in the current directory it runs `fnm use default` instead of `fnm run` so it switches me back to my default nodejs version.

**Comment by Schniz** [comment]
Regarding 1 — a fix is on its way. It has been like that for ever in Zsh (which I use), but Bash is using aliases and not hooks so it will be fixed in the next version 👍 
thanks for reporting that

Regarding 2 — I think this is error prone, so I'm not sure we want it:

```
node -v # => default: v6.0.0
fnm use 12.0.0
node -v # => v12.0.0
cd package-a
node -v # => v6.0.0
```

What we might want to do is something like #144 suggested, which will traverse the directories and look for `.node-version` or `.nvmrc` files in parent directories and automatically switch based on them.

What do you think?

---

P.S.
having a custom script that works better for you is a great choice 😄

**Comment by tsndr** [comment]
I prepared a solution to no.2 here #321 

But to check parent directories as well would be a great addition in the future :)
