### ISSUE TITLE
global option `--node-dist-mirror` is not recognized in 1.22.6

### ISSUE THREAD

**Issue by jkzing** [Schniz/fnm#325]
It seems `--node-dist-mirror` option is not working any more. See below screenshot:

![image](https://user-images.githubusercontent.com/2851517/98498958-2f9fe400-2283-11eb-8ddb-06a718807ac5.png)

fnm version: 1.22.6
system: MacOS 10.15.7
shell: zsh

**Comment by Schniz** [comment]
Hey sorry about that. It's a regression from the Rust implementation. Fixed it in #326. The issue was that these config options are configured in the root command so they had to be applied before the subcommand:

```
fnm --node-dist-mirror=... install
```

The PR in #326 fixes it, sorry again!
