### ISSUE TITLE
fnm use loudness 

### ISSUE THREAD

**Issue by pavelloz** [Schniz/fnm#33]
2 lines seems very verbose with message that looks like a debug info:

```
Linking /Users/Pavel/.fnm/current to /Users/Pavel/.fnm/node-versions/v10.15.1/installation
Using v10.15.1
``` 

Maybe something like:

`fnm using node v10.15.1` would be enough as default?

**Comment by Schniz** [comment]
Sounds good. I like verbose things (especially when building stuff), but it should not be the default. #30 adds `--quiet` to `use`. I guess logging levels are something worth implementing 😺 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
