### ISSUE TITLE
npm i -g npm is ignored

### ISSUE THREAD

**Issue by screendriver** [Schniz/fnm#332]
```sh
❯ fnm --version
fnm 1.22.8
❯ node --version
v15.2.0
❯ npm --version
7.0.10
❯ fnm use 12
Using Node v12.19.0
❯ npm --version      
7.0.10
❯ npm i -g npm@6
❯ npm --version 
7.0.10
```

So I always stick to the latest version of `npm` right now which introduces a new `package-lock.json` format `v2`

**Comment by screendriver** [comment]
I restarted my terminal and now it works 🤔

**Comment by Schniz** [comment]
very weird but sounds like it was fixed? please reopen if problem persists.
if you have a script that reproduce it, I'd be happy to try making it work 😄

**Comment by Schniz** [comment]
also, sorry for this... hope that it works well since!

**Comment by screendriver** [comment]
Yes everything good. I just left the issue open in case if you have some ideas 🤔 Pretty strange behavior that I had.

**Comment by robcresswell** [comment]
I had the same behaviour, and restarting my terminal also worked. Thanks for posting about it.
