### ISSUE TITLE
Can't make system's node the default

### ISSUE THREAD

**Issue by zimme** [Schniz/fnm#336]
```sh
➜  ~ fnm --version
fnm 1.22.8
➜  ~ fnm default system
error: Can't create symlink for alias: entity not found
➜  ~
```

**Comment by Schniz** [comment]
sounds like a bug! 🐛 
sorry about that. Hope I'll have time to tackle that soon.

**Comment by juliankrieger** [comment]
@Schniz I'd like to try. Any idea where to start?

**Comment by zimme** [comment]
I wonder if it's the function installation_path in this file that's the problem. It seems to return None for Bypassed i.e. when system node is used. As because if that the alias code can't create a symlink as it doesn't get any path for the system node.

Could be wrong as I'm not familiar with the code base and haven't programmed in rust before.

https://www.github.com/Schniz/fnm/tree/master/src%2Fversion.rs

**Comment by juliankrieger** [comment]
Yes, I agree. When passing "system" to fnm, `choose_version_for_user_input` returns `ApplicableVersion { ..., version: Version::Bypassed`.  Later on, `installation_path` returns `None`. A more correct version would return the output of `which node`, no?

**Comment by zimme** [comment]
I thought I saw ApplicableVersion containing path, does that point to the installation path for the system's node when version i bypassed? And could that be used?

**Comment by juliankrieger** [comment]
Weirdly enough, `ApplicationVersion` points to /dev/null/ for me. I kind of wonder why `create_alias` seemingly does the work twice? `ApplicableVersion`'s `path` property points to the same value ("/Users/julian.krieger/.fnm/node-versions/v8.17.0/installation") as `version_dir` in the `create_alias` function. 

Is there any reason we can't just pass ApplicableVersion to create_alias and use its path, @Schniz ?

**Comment by Schniz** [comment]
I guess we will eventually need to do a refactor for the version structs because they kinda getting out of hand. 
the secret sauce of `system` version (or, Bypassed) is that we provide a symlink that wouldn’t resolve into a Node binary path. So `FNM_SYMLINK:/bin` in `$PATH` will practically make it bypass (hence the name internally) the symlink. This way we don’t need to have dynamic links to the current node version. Just a simple hack!

I still need to read whatever else you wrote because I’m afk so I’m sorry for not helping more than that.

**Comment by juliankrieger** [comment]
So when using `node` when `fnm`'s default version points to `system`, it doesn't resolve into a node binary and the path is searched for the one installed in the system? Wouldn't the solution to this problem be just clearing the symlink then?

**Comment by Schniz** [comment]
Good idea. I guess I just didn’t think about it! My thought process was “I’m symlinking stuff so let’s make the symlink never resolve”. This flow made fnm check for a constant string. 

Your idea changes the implementation to be from a string to an Option<string>, where None => system version. Much cleaner! 🙌

**Comment by juliankrieger** [comment]
I propose the following change to alias.rs:
```
pub fn create_alias(
    config: &FnmConfig,
    common_name: &str,
    version: &Version,
) -> std::io::Result<()> {
    let aliases_dir = config.aliases_dir();
    std::fs::create_dir_all(&aliases_dir)?;

    let version_dir = version
        .installation_path(config)
        .ok_or_else(|| std::io::Error::from(std::io::ErrorKind::NotFound));
    let alias_dir = aliases_dir.join(common_name);

    if alias_dir.exists() {
        remove_symlink_dir(&alias_dir)?;
    }

    if *version != Version::Bypassed {
        let version_dir_res = version_dir?;
        // Symlink only if version should not bypass system node
        symlink_dir(&version_dir_res, &alias_dir)?;
    }

    Ok(())
}
```

**Comment by Hazmi35** [comment]
Any updates on this?

**Comment by Schniz** [comment]
nope, feel free to open a PR that fix that 😄 , I do not use system node at all and I definitely don't think people should use it as default -- but I will accept PRs that allow it (the current error message is bad and does not give any context)

**Comment by selrond** [comment]
should be fixed in 1.28

**Comment by Schniz** [comment]
1.28 is out, please reopen if necessary :)

**Comment by Hazmi35** [comment]
> 1.28 is out, please reopen if necessary :)

While you can set a default or other word as an alias to `system` but numbers are not, it will say `Can't find an installed Node version matching v17.x.x.`, and prompting whether to install it or not.

If you say yes to install it, it will install that version but the alias won't work, idk if this intended or not, Should I open a new issue for that?

**Comment by Schniz** [comment]
> Should I open a new issue for that?

Sure, if this is an issue. However, I don't really understand why have a 16.x.x alias when you can `fnm install 16` and `fnm use 16` 😇

**Comment by Hazmi35** [comment]
> > Should I open a new issue for that?
> 
> Sure, if this is an issue. However, I don't really understand why have a 16.x.x alias when you can `fnm install 16` and `fnm use 16` 😇

Well, It's simply to not have 2 of the same Node.js versions installed in the system, for example you're using Yarn in Arch Linux and installing it through pacman, it will also install `nodejs` as a dependencies, right now it's Node.js 17, so aliasing `17` to system is nice

**Comment by Schniz** [comment]
In the meantime you can alias `n17` instead of `v17`
