### ISSUE TITLE
Infer complete semver in `use` and `install`

### ISSUE THREAD

**Issue by wangzuo** [Schniz/fnm#35]
Similar to nvm, it would be helpful to support `fnm install 11`.

**Comment by wangzuo** [comment]
Also thanks for the great work, I have switched from nvm to fnm.

**Comment by wangzuo** [comment]
Sorry, just find it in the future plan.

**Comment by Schniz** [comment]
Hey! Don’t worry. It’s good to have it as an issue :) 
There are couple of things that need to be sorted out though. Like, I guess `install 11` will install the latest version. Will `use 11` try to use the latest version _installed_?
I think this will be the right behavior but still it is something worth discussing 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wangzuo** [comment]
nvm uses `install node` for the latest version so I guess `install 11` may just install the latest version from `v11`.

**Comment by compilenix** [comment]
> There are couple of things that need to be sorted out though. Like, I guess `install 11` will install the latest version. Will `use 11` try to use the latest version _installed_?

I would like it exactly as you proposed.
`install 11` will install the latest version of 11 while `use 11` will use the latest version of localy installed or fail.

This way no internet connection is required for `use 11` (if any version of 11 is available) and therefore no added network latency.
