### ISSUE TITLE
Install to XDG dir by default instead

### ISSUE THREAD

**Issue by samhh** [Schniz/fnm#357]
Probably `$XDG_DATA_HOME` defaulting to `$HOME/.local/share` in its absence, per [the spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

The purpose is to avoid cluttering up `$HOME`, as with the present default which creates `.fnm` in there.

**Comment by Schniz** [comment]
Makes sense. We can use [`dirs::config_dir`](https://docs.rs/dirs/3.0.1/dirs/fn.config_dir.html) to do that, and if we find `$HOME/.fnm` we can mention that it is deprecated.

I wonder if `$HOME/Library/Application Support` is actually a good fit for Mac 🤔

**Comment by Siilwyn** [comment]
It might also be useful to look at the locations used by solutions like [env-paths](https://github.com/sindresorhus/env-paths). Indeed on Mac `Application Support` seems to be used.

**Comment by MarioRicalde** [comment]
I would probably stick with `$XDG_DATA_HOME` rather than using `Library` path.

**Comment by waldyrious** [comment]
Now that #416 is merged, perhaps the documentation should be updated [here](https://github.com/Schniz/fnm#parameters) and [here](https://github.com/Schniz/fnm#removing), right?

**Comment by ismay** [comment]
I'm not sure if this is intentional, but the install scripts (https://fnm.vercel.app/install) still installs to ~/.fnm. So following the defaults for the installer result in a warning for each new shell I open.

**Comment by Schniz** [comment]
Yeah, I will do a gradual migration for this and publish a new version soon.
