### ISSUE TITLE
Error when opening a terminal in Nova on macOS

### ISSUE THREAD

**Issue by skilar** [Schniz/fnm#363]
This is a very similar issue to #285. I use `fish` as my shell and [Nova](https://nova.app/) as my code editor. When I open a shell in Nova, I get this error:

> error: Can't infer shell!
> fnm can't infer your shell based on the process tree.
> Maybe it is unsupported? we support the following shells:
> * bash
> * zsh
> * fish
> * powershell

For `npm` and `node` to be found, I must start a new `fish` session. This does not happen in iTerm2 or Terminal.app.

**Comment by Schniz** [comment]
Please provide your shell configurations. Also, consider using `--shell=fish` to force fish shell if you want to solve it immediately. 

If you want to help debug that, which would be more preferable, you can run fnm with debugging prints enabled. `env RUST_LOG=fnm=debug fnm env` would do the trick. I guess the process name is something that we don’t understand. Please share your findings if you can!

**Comment by skilar** [comment]
Thanks for the quick reply! My configuration is as suggested in the readme: `fnm env | source`

Running with debugging prints enabled gives this:
```
[2021-01-15T00:05:36Z DEBUG fnm::shell::infer::unix] binary is not a supported shell: "fnm"
[2021-01-15T00:05:36Z DEBUG fnm::shell::infer::unix] binary is not a supported shell: "l"
[2021-01-15T00:05:36Z DEBUG fnm::shell::infer::unix] binary is not a supported shell: "Nova"
[2021-01-15T00:05:36Z DEBUG fnm::shell::infer::unix] binary is not a supported shell: "launchd"
```

Does that help?

**Comment by Schniz** [comment]
It does! Do you see that we don’t find any shell in the process tree? I’m not entirely sure what `l` is, maybe that’s a shell wrapper? Anyway, this is why we can’t infer the shell. 

Maybe providing the shell explicitly is inevitable. Maybe inferring should be deprecated in the long run.

**Comment by Schniz** [comment]
If you use fish, then `fnm env --shell=fish | source` will work 😇

**Comment by skilar** [comment]
That's helpful information. Thank you! I do believe `l` must be the wrapper Nova uses for the shell. Setting `--shell=fish` cleans everything up nicely. Thanks again.

**Comment by Schniz** [comment]
Cool! Happy to help
