### ISSUE TITLE
[not bug] Installing problem in mac arm64(m1, apple silicon)

### ISSUE THREAD

**Issue by gucheen** [Schniz/fnm#369]
not a bug but just some notice.

Since nodejs.org hasn't release a darwin-arm64 binary, fnm cannot download the target binary line `https://nodejs.org/dist/latest/node-v15.6.0-darwin-arm64.tar.xz`.

And also, node.js currently only support apple silicon after version v15.x, if no further updates on lower versions, some testing will be failed(like install node v12.x).

refer: https://github.com/nodejs/build/issues/2474
related pr: https://github.com/Schniz/fnm/pull/368

**Comment by Schniz** [comment]
Woah. what would other package managers do? install from source? That would be a waste of time for most people.

**Comment by 7rulnik** [comment]
@Schniz for example, nvm will compile it from source, yeah. As I understand it's just a temporary solution. Native support was introduced in 15.3.0.

**Comment by 7rulnik** [comment]
And sorry for off-topic, but can you take a look at https://github.com/Homebrew/homebrew-core/issues/68301?

**Comment by gucheen** [comment]
@Schniz fallback to a x64 version of nodejs would be a choice. x64 nodejs runs well through Rosetta.
Maybe offer an option to selected target arch like https://github.com/tj/n

**Comment by ole3021** [comment]
I use n currently to solve the node env management problem. but fnm is my favorite one. so hopefully there will have a solution that works for me. Thanks in advance.

**Comment by Schniz** [comment]
> And sorry for off-topic, but can you take a look at [Homebrew/homebrew-core#68301](https://github.com/Homebrew/homebrew-core/issues/68301)?

@7rulnik I will release a new version soon with #368 that should possible fix this issue. That being said, I am not sure about fnm for building from source, so I don't know how it would help. Still need to consider if we want to allow building from source, and if we do, understand how to do that 😄

**Comment by dvcrn** [comment]
> Woah. what would other package managers do? install from source? That would be a waste of time for most people.

I found this problem looking for something that can help me out of slow nvm load speeds. Does this project have no option to compile from source? Another M1 user here and I quite like that NVM can just compile node when no bin is available

**Comment by Schniz** [comment]
> Does this project have no option to compile from source?

Right now it does not. I would consider accepting a contribution that adds this feature (it feels like a massive maintaining burden, but maybe I'm afraid for nothing). Anyway, in my current workflow, I don't find myself in need of compiling for source, and it does not sound very interesting to build, so I don't see myself building it.

If someone wants to chime in and make fnm optionally build from source, let me know!

**Comment by gucheen** [comment]
https://github.com/nodenv/node-build
Currently I use `node-build` to build node v15.x on my MacBook m1.
eg `node-build 15.11.0 ~/.fnm/node-versions/v15.11.0/installation/` and all things works well (it takes a while to compile, though)

**Comment by Schniz** [comment]
fnm v1.24.0 now installs the x64 version which Rosetta can run. 😃

**Comment by 7rulnik** [comment]
@Schniz node 16 just released with prebuilt binaries for darwin-arm64
https://nodejs.org/dist/v16.0.0/
