### ISSUE TITLE
Command 'npm ls -g' not working (windows, powershell)

### ISSUE THREAD

**Issue by klaseca** [Schniz/fnm#373]
After installing a global package (for example `pnpm`) I can use it, but the command `npm ls -g` does not display it (and `npm` too). How to fix it?
![изображение](https://user-images.githubusercontent.com/48491463/105215679-00530080-5b6b-11eb-9685-ca8a9bf867bf.png)

**Comment by Schniz** [comment]
What is the output of `npm list -g --depth=1`?

**Comment by klaseca** [comment]
> 
> 
> What is the output of `npm list -g --depth=1`?

![изображение](https://user-images.githubusercontent.com/48491463/105378314-20df9100-5c25-11eb-8c40-d79f332b4e94.png)

**Comment by Schniz** [comment]
I have a feeling that it is something related to symlinks in Windows.
I don't use global packages using `npm` (I'm using the unreleased [`gpkg`](https://github.com/Schniz/gpkg)) and I don't use Windows. I wonder if this is a bug in npm on Windows, which does not resolve symlinks or something.

**Comment by klaseca** [comment]
Problem in node on windows after version 15 (npm/cli#2229). Last lts version works fine.
![изображение](https://user-images.githubusercontent.com/48491463/105391524-a10cf300-5c33-11eb-93f3-c32d7c0de8a3.png)

**Comment by Schniz** [comment]
I don't really follow. You're saying that the npm version comes with Node LTS (v14.15.4) does support symlinks while the version you have installed with v15.6.0 doesn't?
can you do `npm --version` in both Node version? maybe that's a regression in npm

**Comment by klaseca** [comment]
![изображение](https://user-images.githubusercontent.com/48491463/105397169-24c9de00-5c3a-11eb-9bac-fec9c08da684.png)
After installing npm@6.14.10 on node version 15.6.0 no problem.
![изображение](https://user-images.githubusercontent.com/48491463/105397610-b89baa00-5c3a-11eb-9ad9-e56ca4cb77ee.png)

**Comment by Schniz** [comment]
Cool. Please open a bug report to npm regarding this regression. Sorry I can't help more than that.
