### ISSUE TITLE
Terminal-local "use"?

### ISSUE THREAD

**Issue by jaredly** [Schniz/fnm#375]
It's cool that `fnm use` uses a `.nvmrc` or `.node-version` file in the current directory, but it's weird that this effects the global node version that's in use.
For example, if you have two terminals open to different projects that use different versions of node, then you might expect that fnm would just "take care of it", but in fact you'll be stuck with the version of the folder you `cd`d to *second*.

Is this unreasonable? I know that fnm works by symlinking, which is why it's global, but could there be a mode where `fnm use` (or like `fnm use-local`) just modifies the current shell's `$PATH`?

**Comment by Schniz** [comment]
Hi! that's exactly how fnm works. 😃

Every shell session gets its own symlink which is prepended to `$PATH`. So `fnm use` should only affect the current shell session.

The Rust version has no option to have a global Node version anyway. Maybe you're using an old version? If not, this is probably a bug of some sort. 

The following commands can let us understand a little more:
```
env | grep FNM_
echo $PATH
fnm --version
```

**Comment by jaredly** [comment]
d'oh should have made sure to upgrade before posting 🙃 works great!

**Comment by Schniz** [comment]
Haha great to hear! 😃
Let me know if there is anything else I can help with 😁
