### ISSUE TITLE
`fnm` on chocolatey packages?

### ISSUE THREAD

**Issue by dalisoft** [Schniz/fnm#378]
Hi @Schniz 

I am using your tool on all Unix platforms. Recently i tried move to Windows 10 and missing your tool.
I am tried `scoop`, but it doesn't work properly for many tools, so only way is `choco` for me.

Can you please add it to `choco` or somehow make it available?

Thanks for great tool

**Comment by goldcoders** [comment]
you can always install rust and cargo , to install fnm...

**Comment by Schniz** [comment]
Unfortunately, I do not use Windows, so I can't really help with Windows-based package managers. I'd be happy to help with everything you need in order to add it to `choco`, if that's something you're willing to do 😃

**Comment by dalisoft** [comment]
I'll try add `fnm` to `choco` list. Thanks for reply @goldcoders

**Comment by dalisoft** [comment]
I'm currently following guides from [here](https://docs.chocolatey.org/en-us/create/create-packages)

**Comment by Schniz** [comment]
@dalisoft let me know when it's done 😃
then we can update the README file with Chocolatey instructions 💪

**Comment by CMeeg** [comment]
Hi @Schniz - I've recently started using fnm (which I think is great by the way!) on Windows and also wanted to install via Chocolatey. After finding it was not available in the Chocolatey package feed I came across this issue, but noticed it has been 7 months without an update so I thought I would get it pushed up to Chocolatey.

I hope I'm not stepping on your toes @dalisoft by doing this, but I assumed that given the time period that had elapsed that you hadn't found the time yourself to create the Chocolatey package and wouldn't mind somebody else taking it on.

I have pushed the latest version (1.26.0) of fnm up to Chocolatey and it's currently awaiting manual moderation (automated checks have passed) and approval. The guidelines state this can take 1 - 3 business days.

I have setup an [fnm-chocolatey](https://github.com/CMeeg/fnm-chocolatey) repo that contains the source code for creating fnm Chocolatey packages. The repo contains a scheduled action that will check for new releases of fnm and automatically package and publish to the feed when a new version is found.

I will submit a PR to add Chocolatey install instructions to this repo's README once the package has been approved and is available on the public Chocolatey feed.

I hope that is OK with both of you - I just really like this software and wanted to see it on Chocolatey!

**Comment by dalisoft** [comment]
Hi @CMeeg 
Yes, i couldn’t not get some time to create Chocolatey package due of full time job tasks and not using Windows due of very slow performance on my job tasks. I also love this project and thank you for hard work, really awesome to see. 

Hi @Schniz
Sorry to not creating package within so more time with opened issue, i hope you understand me

**Comment by CMeeg** [comment]
No worries @dalisoft - thanks for opening this issue in the first place so I knew it wasn't just me that wanted to see fnm on Chocolatey!

**Comment by dalisoft** [comment]
@CMeeg I love this project and this project really amazing, when i opened this issue, i wanted migrate to Windows from macOS but i failed for DevOps tasks and back to macOS again  
Thank you for understanding

**Comment by Schniz** [comment]
haha no need to be sorry @dalisoft! This is free software--you don't get paid for it and you should only contribute when you are in the mental and physical state to do so. People like @CMeeg can hop in and help when they have time and will 😃  I also have my highs and lows and not always giving fnm the attention it deserves. Hope that no one hates me for it 😃  anyway, I am grateful for any contribution, including issues 😃 

and @CMeeg, thank you! I have been a happy Choco user back when I partially used Windows. Really appreciate the work you put to make it available for more users 👯

**Comment by dalisoft** [comment]
@Schniz @CMeeg You are both amazing and thank you for understanding

**Comment by CMeeg** [comment]
Great stuff, thanks @Schniz !
