### ISSUE TITLE
`list` command lists up irrelevant files

### ISSUE THREAD

**Issue by chalkygames123** [Schniz/fnm#382]
Hi,

I noticed that when there are irrelevant files to `fnm`, the command incorrectly reports them as versions.

For example, with the default install directory, after running this:

```
touch ~/.fnm/node-versions/foo
```

the `list` command will output:

```
% fnm list
* foo
* system
```

It will cause listing `.DS_Store` files that might be created by macOS Finder when you browse the versions directory.

**Comment by Schniz** [comment]
fnm uses the directory structure as its database, so it makes sense that we will list `foo`. That being said, it makes sense to ignore hidden files. Seems like an easy fix — need to add another condition here:

https://github.com/Schniz/fnm/blob/bcbf3b1d08c65c6b23cd92b187179459e7d35be8/src/installed_versions.rs#L9-L11

Would you want to submit a PR? 😃

**Comment by chalkygames123** [comment]
Thank you for the response.

> Would you want to submit a PR? 😃

No, I'd like to leave it to you.

**Comment by jungaretti** [comment]
@Schniz I could tackle this!

**Comment by jungaretti** [comment]
Oops, looks like it's already fixed. I think #384 should have closed this issue.

**Comment by Schniz** [comment]
Yes! Thanks, and sorry.
