### ISSUE TITLE
[homebrew]: no bottle available on M1 machines

### ISSUE THREAD

**Issue by screendriver** [Schniz/fnm#383]
Unfortunately I am not able to install `fnm` on my Apple M1 machine:

```sh
❯ uname -m
arm64

~ 
❯ curl -fsSL https://fnm.vercel.app/install | bash
Downloading fnm using Homebrew...
Checking dependencies for the installation script...
Checking availability of curl... OK!
Checking availability of unzip... OK!
Checking availability of Homebrew (brew)... OK!
Error: fnm: no bottle available!
You can try to install from source with:
  brew install --build-from-source fnm
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

**Comment by Schniz** [comment]
interesting. I don't have M1 so I don't know what's the process.

Looks like https://github.com/Homebrew/homebrew-core/pull/69550 has failed. I'm going to comment there to verify if I can do something to help.

**Comment by laurentvd** [comment]
I managed to install `fnm` manually. However, when installing node versions, it seems to always install the Intel (x86) arch version. At least node 15 supports ARM natively, but not when installed through `fnm install 15`.

**Comment by Schniz** [comment]
So, seems that the issue is failed tests — because as you said, we can't install Node versions. I'd be happy if someone who actually has an M1 to help, because I don't have one, and I know of any CI system that supports these. Uncharted territory here!

It does not seem like a big issue, the biggest issue is that there are no prebuilt binaries for M1, which will make fnm useless (https://nodejs.org/dist/latest/)

I guess we'll have to track https://github.com/nodejs/build/issues/2474

**Comment by Schniz** [comment]
Can we somehow fix fnm so it will run Node using Rosetta?
I don't know all of these fancy words, I'm using my old MacBook Pro 2017, and have no M1 machine to play with 😃

**Comment by screendriver** [comment]
Right now there is no Node.js built for M1. Their goal is to start with universal binaries beginning with Node 16.

What  I could imagine that `fnm` is a native M1 binary but downloads Node.js as usual. Node.js will then run through Rosetta 2 (which runs fine). I believe `nvm` is doing that as well. 

If you need any help with testing or something like that I would be available 🙂 

> and I know of any CI system that supports these

How does other in Rust written tools like `fd`, `exa`, `ripgrep`, `bat` and so on build their things? (all of them have native M1 binaries)

**Comment by Schniz** [comment]
> How does other in Rust written tools like `fd`, `exa`, `ripgrep`, `bat` and so on build their things? (all of them have native M1 binaries)

fnm compiles perfectly for M1 AFAIK, but can't download Node because there are no prebuilt binaries. Maybe the generated URL for the binaries won't match the actual binary URL:

https://github.com/Schniz/fnm/blob/cb1079f5e9dde09f3492750442fe927616660ff2/src/downloader.rs#L33-L51

(and https://github.com/Schniz/fnm/blob/cb1079f5e9dde09f3492750442fe927616660ff2/src/system_info.rs)

**Comment by vikiival** [comment]
Is there some tutorial, how to install `fnm` through ` brew install --build-from-source fnm` ?

**Comment by Schniz** [comment]
Lots of options in the README, but specifically:
* [installing the binary without Homebrew with the installation script](https://github.com/Schniz/fnm#parameters)
* [install using Homebrew with Rosetta](https://twitter.com/galstar/status/1360575882230956033)

If you want to compile it from source, it's a matter of:

```
git clone git@github.com:Schniz/fnm.git
cd fnm
cargo build
```

then you can contribute and make it work seamlessly!

**Comment by dvcrn** [comment]
> Is there some tutorial, how to install `fnm` through ` brew install --build-from-source fnm` ?

It's literally just that. Specifying `--build-from-source` makes brew compile it, and rust/cargo already supports M1/arm64. Running fine here natively.

**Comment by Schniz** [comment]
greetings, fnm v1.24.0 is now bottled on M1 machines.
Thanks for reporting!

**Comment by laurentvd** [comment]
Thanks for your work on this @Schniz! Does it also automatically install ARM (M1) builds of node if available?

**Comment by Schniz** [comment]
AFAIK there are no prebuilt M1 binaries. So no.. but we will support it in the future

**Comment by laurentvd** [comment]
You're right. I had an ARM version of Node installed, but it was probably built from source. We'll just have to wait for the prebuilt binaries.
