### ISSUE TITLE
Git Bash issues with CLI tools

### ISSUE THREAD

**Issue by alumni** [Schniz/fnm#390]
The setup for Git Bash (Windows) cannot run cli tools that are installed using `npm install -g`.
```
$ fnm env
export PATH="C:\\Users\\XXX\\AppData\\Local\\Temp\\fnm_multishell_15584_1612875966568":$PATH
export FNM_MULTISHELL_PATH="C:\\Users\\XXX\\AppData\\Local\\Temp\\fnm_multishell_15584_1612875966568"
...
```
Running node works:
```
node -v
v15.8.0
```
But bash is somehow confused about the actual path:
```
$ which node
/c/Users/XXX/Work/neo-backend/\Users\XXX\AppData\Local\Temp\fnm_multishell_17812_1612875949353/node
```
And if I use any cli tool installed with npm, I'll get this:
```
$ npm install -g yarn
added 1 package

$ yarn 
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module 'C:\Program Files\Git\Users\XXX\AppData\Local\Temp\fnm_multishell_17812_1612875949353\node_modules\yarn\bin\yarn.js'
```

This can be fixed by making sure that the `PATH` env variable is using Git-Bash paths:
```
export PATH="/c/Users/XXX/AppData/Local/Temp/fnm_multishell_15584_1612875966568":$PATH
```

**Comment by alumni** [comment]
One more Git Bash issue, after setting the correct `PATH` variable:

If running `fnm use system`, `FNM_MULTISHELL_PATH`  will symlink `Z:\_fnm_\Nothing\Should\Be\Here\installation`, which does not exist. This apparently confuses Git Bash, which stops checking the other folders in the path for the actual node executable.

**Comment by alumni** [comment]
I've been playing with `fnm` today and I must say it's quite fast, I like it a lot ;) 

I made a workaround for this invalid `PATH` issue. Here's my startup (`.bashrc` etc) script:

```sh
eval $(fnm env | sed 1d)
export PATH=$(cygpath $FNM_MULTISHELL_PATH):$PATH

if [[ -f .node-version || -f .nvmrc ]]; then
    fnm use
fi
```

**Comment by Schniz** [comment]
what is `cygpath` 😨 can we fix it upstream?

**Comment by Schniz** [comment]
I mean, currently the path is windows-like if you are on a Windows build, maybe it should differ based on the shell instead? And if that so, should we use `cygpath`? Will it be supported on every Bash on Windows? or should we differentiate between Bash and Git Bash?

**Comment by alumni** [comment]
On MSYS and CygWin, `cygpath` converts between Windows <-> POSIX paths (replaces the path separators and drive letter: `X:\some\path` <-> `/x/some/path`), but might also map some common paths like `/tmp` ~~or home~~ or system folders (`/usr/bin` is `C:\Program Files\Git\usr\bin`. In this specific case:
`C:\Users\XXX\AppData\Local\Temp\fnm_multishell_9452_1612950115921` -> `/tmp/fnm_multishell_9452_1612950115921`

Git for Windows provides a stripped-down version of MSYS. The thing is that MSYS internally uses POSIX paths, and it maintains its own `PATH` variable in the POSIX format. It also converts CLI arguments - when executing `fnm --fnm-dir ~/.fnm`, `fnm` will think it's called like this: `fnm.exe --fnm-dir C:\Users\XXX\.fnm`.

On Windows, every cli command that is installed from node has two versions, e.g. `yarn` (shell script) and `yarn.cmd` (Windows Command Script). If node is started from Bash, spawning a `yarn` process from node will call the shell script, if it's started somehow else, it calls the `cmd` file.

I don't think `zsh`, `fish` or `bash` can ever use Windows paths. At the moment, you can only run them on Windows if you use MSYS, CygWin and WSL. I am not aware of any "native" port (well, MSYS is the only one that is running Windows-native executable code but with this path conversion). 

PowerShell is probably the only one that adapts to the OS (POSIX paths on Linux).

**Comment by rashil2000** [comment]
Was this issue fixed? I've been unable to get fnm working in Git Bash (it works fine in CMD and PowerShell). Even the command 'node' isn't found.

Upon checking the output of `fnm env`, fnm tries to mix Windows style paths and unix style paths, which can be solved with cygpath as @alumni mentions.

**Comment by Debonex** [comment]
> Was this issue fixed? I've been unable to get fnm working in Git Bash (it works fine in CMD and PowerShell). Even the command 'node' isn't found.
> 
> Upon checking the output of `fnm env`, fnm tries to mix Windows style paths and unix style paths, which can be solved with cygpath as @alumni mentions.

Same problem, node can not be found in git bash (works well in PowerShell), did you find a way to solve this?

**Comment by cweekly** [comment]
> I've been playing with `fnm` today and I must say it's quite fast, I like it a lot ;)
> 
> I made a workaround for this invalid `PATH` issue. Here's my startup (`.bashrc` etc) script:
> 
> ```shell
> eval $(fnm env | sed 1d)
> export PATH=$(cygpath $FNM_MULTISHELL_PATH):$PATH
> 
> if [[ -f .node-version || -f .nvmrc ]]; then
>     fnm use
> fi
> ```

Thanks so much for this workaround; it worked perfectly for me.

**Comment by eegli** [comment]
> I've been playing with `fnm` today and I must say it's quite fast, I like it a lot ;)
> 
> I made a workaround for this invalid `PATH` issue. Here's my startup (`.bashrc` etc) script:
> 
> ```shell
> eval $(fnm env | sed 1d)
> export PATH=$(cygpath $FNM_MULTISHELL_PATH):$PATH
> 
> if [[ -f .node-version || -f .nvmrc ]]; then
>     fnm use
> fi
> ```

This. Thank you so much! 

I think it would be helpful to mention this in the readme, maybe under a new section `Bash (Windows)`.  The quirks of cygpath path conversion are not obvious to everyone.

**Comment by ModyQyW** [comment]
> I've been playing with `fnm` today and I must say it's quite fast, I like it a lot ;)
> 
> I made a workaround for this invalid `PATH` issue. Here's my startup (`.bashrc` etc) script:
> 
> ```shell
> eval $(fnm env | sed 1d)
> export PATH=$(cygpath $FNM_MULTISHELL_PATH):$PATH
> 
> if [[ -f .node-version || -f .nvmrc ]]; then
>     fnm use
> fi
> ```

Just a note. `eval "$(fnm env | sed 1d)"` works for me but `eval $(fnm env | sed 1d)` doesn't. Thanks so much for this workaround.

**Comment by alumni** [comment]
I can confirm that everything is fine on Git Bash, no need for workarounds:

```sh
eval "$(fnm env --use-on-cd)"
```

**Comment by cweekly** [comment]
Confirmed same: as of v1.34.0, git-bash in Win10 works as designed and documented, making workarounds moot.

**Comment by yoont4** [comment]
I am running into the same error still and I am on version 1.35.1. Is there anything I need to do other than upgrade for this to work?

**Comment by pierreh** [comment]
FNM_MULTISHELL_PATH wasn't fixed with this.
