### ISSUE TITLE
include windows binaries in release

### ISSUE THREAD

**Issue by prabirshrestha** [Schniz/fnm#4]

**Comment by Schniz** [comment]
I'll start off by saying sorry for all the people who use Windows! This is clearly on the todo list. I only use and have Linux and MacOS machines so Windows is only available via the Azure CI for me, but I'd like to tackle this problem soon.

I would also love to get PRs that do that - if you're into that!

**Comment by ulrikstrid** [comment]
#88 should make it possible to build on Windows which is the first step.

I think there are a bunch of Unix-specific things that will also have to be fixed, but I haven't looked deeper.

**Comment by Schniz** [comment]
I'm still not over @ulrikstrid's awesomeness, and I want to try making it work. Hope I will have some time 😄 Time to install a Windows VM...

**Comment by ulrikstrid** [comment]
I plan to continue working on this soon. Maybe we can put together a task list about things we know we have to do?

**Comment by slikts** [comment]
Windows support would be nice since nvm-windows (unrelated to nvm) is substandard in multiple ways.

**Comment by Schniz** [comment]
I recently dropped @ulrikstrid work regarding Windows build. I believe Windows support is much harder than I initially think and should be treated differently. I still believe we can run the same feature tests on Windows and Unix builds so they'll share the same API and capabilities

**Comment by tomByrer** [comment]
I've used this on Windows:
https://github.com/coreybutler/nvm-windows

**Comment by slikts** [comment]
I'd recommend [nodist](https://github.com/nullivex/nodist) over nvm-windows, since it works [more like nvm](https://github.com/coreybutler/nvm-windows/issues/390) (allows using multiple parallel node versions and doesn't require system permissions).

**Comment by ljharb** [comment]
alternately, https://github.com/jasongin/nvs

**Comment by Schniz** [comment]
We now ship Windows binaries! Now we need to figure out how to make it easy to install it on Windows. What are the cool people using? Scoop? Chocolatey?

**Comment by ulrikstrid** [comment]
`winget` will probably get traction since it's supporter by Microsoft.

https://docs.microsoft.com/en-us/windows/package-manager/

**Comment by alumni** [comment]
`winget` would be very nice, however it requires that [packages have an installer](https://docs.microsoft.com/en-us/windows/package-manager/package/manifest). This could easily be created with [msitools](https://gitlab.gnome.org/GNOME/msitools) under Linux.

**Comment by Hazmi35** [comment]
> `winget` would be very nice, however it requires that [packages have an installer](https://docs.microsoft.com/en-us/windows/package-manager/package/manifest). This could easily be created with [msitools](https://gitlab.gnome.org/GNOME/msitools) or [NSIS](https://www.conjur.org/blog/building-a-windows-installer-from-a-linux-ci-pipeline/) under Linux.

Sorry for the bump / necropost
`winget` in the future doesn't need the package to have an installer, but we need to wait for microsoft/winget-cli#140

**Comment by janpio** [comment]
Turned the `winget` (and installer) request into a standalone issue: https://github.com/Schniz/fnm/issues/683
