### ISSUE TITLE
Mac OS command not found

### ISSUE THREAD

**Issue by nadavkaner** [Schniz/fnm#40]
Mac OS, if I'm not wrong, by default running .bash_profile before opening new terminal window, so when I installed fnm via curl i need to copy those lines from .bashrc to .bash_profile: 
`export PATH=$HOME/.fnm:$PATH
eval fnm env --multi`

don't know if it's really a problem but it took me little digging why fnm command not found..

**Comment by Dean177** [comment]
Looks like its due to Terminal.app not running `.bashrc` files: https://apple.stackexchange.com/questions/12993/why-doesnt-bashrc-run-automatically

**Comment by Schniz** [comment]
Should we change the install script to write to `~/.profile`?

**Comment by maxknee** [comment]
https://github.com/Schniz/fnm/pull/58
