### ISSUE TITLE
Load .nvmrc / .node-version on shell startup

### ISSUE THREAD

**Issue by florian-richter** [Schniz/fnm#410]
I use `fnm` with `fish`.

My `~/.config/fish/conf.d/fnm.fish`:
```
fnm env --use-on-cd | source
```

`fnm` works great when I go to the directory with `cd` but if I start the terminal included in VSCode it starts the terminal in the project folder already. In that case, it does not load the `.nvmrc`.

**Comment by florian-richter** [comment]
Thanks for the quick PR! It helped me find a workaround to use until a new version is released and includes this change.

For those interested in the workaround: I added this line to my `~/.config/fish/config.fish`.
```
_fnm_autoload_hook
```

**Comment by jhirn** [comment]
Wee... this saved me =)
