### ISSUE TITLE
fnm requires administrator privilege to create symlink in windows

### ISSUE THREAD

**Issue by iamprady** [Schniz/fnm#424]
![WindowsTerminal_rERIyrPBzT](https://user-images.githubusercontent.com/75474807/113469041-fcdfcd80-9467-11eb-81bd-43be58956093.png)

**Comment by Schniz** [comment]
You can enable developer mode in Windows as recommended in the README: https://github.com/Schniz/fnm#powershell

**Comment by iamprady** [comment]
> You can enable developer mode in Windows as recommended in the README: https://github.com/Schniz/fnm#powershell

Yeah it worked. Thank you!

**Comment by Schniz** [comment]
No problems. Glad everything is working! 😃

**Comment by ourongxing** [comment]
> You can enable developer mode in Windows as recommended in the README: https://github.com/Schniz/fnm#powershell

if I enable developer mode, I can't use conda to switch python version

**Comment by Schniz** [comment]
Sorry. Not familiar with Conda. Can you give me links for documentation that says it does not work on developer mode? (Sounds counter intuitive to me)
