### ISSUE TITLE
M1 default behavior?

### ISSUE THREAD

**Issue by dalisoft** [Schniz/fnm#430]
Hi @Schniz 

Thank you again for nice tool, but I'm have some incorrect binary on M1.

I installed nodejs by `fnm install 15`, it should be install Apple M1 version by default? But I'm getting `x64` binary

**Comment by dalisoft** [comment]
This is test from bash

```bash
config on  master [!] 
❯ node -p process.arch
arm64
config on  master [!] 
❯ fnm env --shell=fish --arch=arm64 | source
config on  master [!] 
❯ fnm use 15 --arch=arm64
Using Node v15.14.0
config on  master [!] 
❯ node -p process.arch
x64
config on  master [!] 
❯ 
```

**Comment by Schniz** [comment]
I understand that this is unfortunate, but we explicitly don't install arm64 and instead using x64 because Node does not yet distribute prebuilt binaries for M1: https://nodejs.org/dist/v15.14.0/

https://github.com/Schniz/fnm/blob/173ba3cc30f99a63606988ecaee0017d643c9a1e/src/arch.rs#L17-L21

> Thank you again for nice tool

Thank you too!

**Comment by dalisoft** [comment]
How i can install arm64 binaries? It is possible?

**Comment by Schniz** [comment]
From what I know, the only way to install darwin+arm64 binaries is to compile them on your machine

**Comment by dalisoft** [comment]
Thanks, i compile them then ;)

**Comment by firdauswarpin** [comment]
@Schniz @dalisoft how's about Node v16.0.0? Is it possible to achieve this? 
since they provided prebuilt binaries for Apple Silicon

**Comment by firdausious** [comment]
@Schniz @dalisoft  how's about Node v16.0.0? Is it possible to achieve this? 
since they provided prebuilt binaries for Apple Silicon.

**Comment by Schniz** [comment]
This will be the case once I release the latest commit in master. I'm not available right now (reserve duty for two weeks). Sorry for the inconvenience :(
