### ISSUE TITLE
Does not respect npm version per node version

### ISSUE THREAD

**Issue by uloco** [Schniz/fnm#434]
Updating the npm version for one node version also affects all other node versions.
This is unfortunate, since npm changed their package.json format from 6 to 7.
Older projects with e.g. node v 10 do not understand lock-file version 2, so this will not work.

NVM does have this behavior of keeping npm versions separate from each other, so migrating an existing nvm project to fnm would be only possible if every developer in the team does so (which is quite not possible in my case...)

Is this something by design or do you plan on keeping track of the different npm installations per node version?

**Comment by Schniz** [comment]
Greetings, please make sure you actually use the npm binary from the fnm installation. Npm is installed with the node installation so it's not related to fnm. Please let me know what happens 😃

**Comment by uloco** [comment]
Appearently I am just stupid and tested it wrongly lol -.-.

**Comment by robcresswell** [comment]
@uloco What was your fix here? I'm still seeing issues with `fnm` and `npm`. For some reason, when using `fnm`, `node` is correctly aliased:

```shell
$ which node
/var/folders/p9/n6cgtv2d5dj347pc26tz4f1h0000gn/T/fnm_multishells/33177_1623769679868/bin/node
```

But `npm` is not:

```shell
/usr/local/bin/npm
```

This is quite annoying, as I regularly jump between projects on older Node / NPM versions, and those on newer, but the `npm` version seems to be managed globally.

**Comment by robcresswell** [comment]
I'll investigate more, thanks!

**Comment by dunklesToast** [comment]
Had the same issue on macOS. Turns out that `brew uninstall node` does not remove npm. You have to remove npm yourself:
```sh
rm -f /usr/local/bin/npm
```

After that everything works as expected:

```sh
$ which node npm
/var/folders/hd/nnxx3p2d4njcc9_h4hcv1cnc0000gq/T/fnm_multishells/10036_1633180414186/bin/node
/var/folders/hd/nnxx3p2d4njcc9_h4hcv1cnc0000gq/T/fnm_multishells/10036_1633180414186/bin/npm
```

**Comment by robcresswell** [comment]
Interesting! I never did uncover an exact cause, but I did end up purging a lot of things and it eventually started working as expected. I wasn't very scientific unfortunately... I got a bit frustrated 😅

**Comment by kcrwfrd** [comment]
I had an issue where there was a mismatch between my `node` and `npm` versions in the directory of a project with an `.nvmrc`, even though `which npm` was indicating that it was pointing to a binary managed by `fnm`.

The following worked for me to fix it:

```
fnm uninstall
```

followed by
```
fnm install
```
