### ISSUE TITLE
`fnm default system` does not work

### ISSUE THREAD

**Issue by dalisoft** [Schniz/fnm#439]
Hi @Schniz.

It's again me, thank you for developing this amazing tool.

My system now updated to Node.js v16 and i tried fnm to use Node.js v14 and it worked fine.
But reverting does not work `fnm use system`.

## Environments
- OS: macOS Big Sur 11.2.3
- Arch: **Apple Silicon** and **x64 Intel**
- Shell: fish
- Prompt: starship
- Node.js: System v16, calling v14

## Related issue

> Maybe it's not related

- #381 
- #366 
- #336

**Comment by Schniz** [comment]
What shell do you have?

**Comment by dalisoft** [comment]
Oh, forgot to mention. 

Shell: fish
Prompt: starship

**Comment by dalisoft** [comment]
As `fnm 1.26.0` seems issue was fixed

**Comment by dalisoft** [comment]
`fnm use system` works whereas `fnm default system` not

```bash
❯ fnm default system                                                                                                                                 (base) 
error: Can't create symlink for alias: entity not found
```

**Comment by vith** [comment]
- `fnm 1.27.0`
- `zsh 5.8 (x86_64-pc-linux-gnu)`

`fnm use system` is not working for me:

```console
~
❯ /usr/bin/node -v
v16.10.0

~
❯ fnm current
v14.17.5

~
❯ node -v       
v14.17.5

~
❯ fnm use system
Bypassing fnm: using system node

~
❯ node -v
v14.17.5

~
❯ which node
/tmp/fnm_multishells/44696_1633509478283/bin/node

~
❯ fnm current
system
```

**Comment by Schniz** [comment]
@vith Can you please share your `$PATH`? :)

**Comment by vith** [comment]
@Schniz Weird, now `fnm use system` is working... here's my `$PATH` now but not sure if that helps anymore:

```
~
❯ for x ($path) { echo $x }
/tmp/fnm_multishells/149123_1633543763857/bin
/home/vith/.fnm
/home/vith/.zplug/repos/zplug/zplug/bin
/home/vith/.zplug/bin
/home/vith/.local/bin
/home/vith/code/bin
/home/vith/.npm/bin
/opt/jython/bin/
/usr/local/bin
/usr/bin
/usr/local/sbin
/home/vith/.dotnet/tools
/usr/lib/jvm/default/bin
/usr/bin/site_perl
/usr/bin/vendor_perl
/usr/bin/core_perl
```

If it happens again I'll check that next time.

**Comment by dalisoft** [comment]
@Schniz I confirm `fnm use` works

**Comment by boompikachu** [comment]
`fnm default system` command doesn't give any error it doesn't set `system` as the default

<img width="682" alt="image" src="https://user-images.githubusercontent.com/37561295/185431559-59ffc87e-674f-408a-b179-83b85ff372a7.png">

Also, if start terminal with `default system` switching version doesn't change node. Might be due to `fnm current => none`
https://github.com/Schniz/fnm/issues/583#issuecomment-1173142617
