### ISSUE TITLE
after install fnm get error: Invalid value for '--arch <arch>': Unknown Arch: x64export error

### ISSUE THREAD

**Issue by sunOpar** [Schniz/fnm#451]
![image](https://user-images.githubusercontent.com/13537651/119162322-cc420a80-ba8c-11eb-8e93-0894d86e6150.png)

**Comment by Schniz** [comment]
Can you please reload your shell? As in opening a new session/tab/sourcing your shell  profile

**Comment by Schniz** [comment]
Hi! Is it solved? What solved it?
