### ISSUE TITLE
How to prevent the "Using Node v**.**.*" message from appearing

### ISSUE THREAD

**Issue by osenvosem** [Schniz/fnm#458]
I have some issues with a CLI tool because of it. Can I switch it off somehow?

**Comment by Schniz** [comment]
`fnm` accepts a log level, one of `info, error, quiet`:

```sh-session
$ fnm --log-level=error use my-version
```
will make it only show errors.

You can pass this to `fnm env` to make it the default on your machine:

```sh-session
$ eval "$(fnm --log-level=quiet env)"
# now everything is silent!
```
