### ISSUE TITLE
Change feature test runner to use Rely

### ISSUE THREAD

**Issue by Schniz** [Schniz/fnm#46]
Use the installed test runner instead of bootstrapping ourselves in Bash

**Comment by dangdennis** [comment]
I can assist in implementing these tests in Rely if you're able to help me formulate a proper way of testing fnm. 

Are you planning to use Rely only for unit testing? Or are you also implementing the Bash tests in Rely as well?

**Comment by Schniz** [comment]
I already use Rely for unit tests, but I had a thought to implement the tests using Rely instead of Bash scripts, but we don't have a reason to do that now:

* We won't be able to see progress
* It doesn't run in parallel
* Bash scripts are a great way to do E2E tests, act like users!

I did think about making a script generator, that takes a syntax (maybe lisp-y syntax) and generates script files for: bash, fish, zsh and Batch/PowerShell (when we'll get to windows support)

So there will be only one script that will contain the logic, and will derive all the permutations from it, giving more coverage

**Comment by Schniz** [comment]
Closing since the project migrated to Rust
