### ISSUE TITLE
Consider using bats from writing tests

### ISSUE THREAD

**Issue by wildcard** [Schniz/fnm#47]
You can use bats to write TAP compliant tests see https://github.com/sstephenson/bats

see an example of project using bats https://github.com/eficode/wait-for

**Comment by Schniz** [comment]
Hey @wildcard! that looks very cool. I actually thought about migrating the tests to Reason instead of Bash (#46), and run it with the "smoke" tests I already have - it makes more sense to me.

I think that although Bash is awesome, maintaining this kind of scripts over time is hard. What do you think?

**Comment by wildcard** [comment]
I think tests in Reason would be unit tests (white box) while those bash/shell tests are e2e - black box tests (simulating user behavior).

My humble opinion is that you need both kind of tests.

You can write e2e in any language you like, for me bash/shell feels to must natural way to test command line tool like fnm. 

קובי קדוש,
נשלח מה-iPhone שלי

**Comment by Schniz** [comment]
I totally agree that having bash files as the e2e scenarios will be nice (and easy to understand the underlying features)

The problem I have is Bash is harder to maintain and use a library written in Bash feels wrong to me. What I thought about is something like running Bash scripts from each test scenario, and then snapshot the result.
This is what I'd do if I was writing a Node app. It could run in parallel and finish much much faster.

That being said, bats looks super dope!

**Comment by wildcard** [comment]
Snapshot testing is dope! 
So I guess you can go ahead and do what you are suggesting.

For now I'll close the issue ;)
