### ISSUE TITLE
Error `Can't create symlink!: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }` while running fnm with non-root environment

### ISSUE THREAD

**Issue by IceCodeNew** [Schniz/fnm#470]
**`user@**********:~$ RUST_BACKTRACE=full /usr/local/bin/fnm env`**

```
thread 'main' panicked at 'Can't create symlink!: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/commands/env.rs:44:58
stack backtrace:
   0:     0x7fb8187d1a50 - <unknown>
   1:     0x7fb81881045f - <unknown>
   2:     0x7fb8187cb2d2 - <unknown>
   3:     0x7fb8187d4175 - <unknown>
   4:     0x7fb8187d3c23 - <unknown>
   5:     0x7fb8187d48ed - <unknown>
   6:     0x7fb8187d4457 - <unknown>
   7:     0x7fb8187d1eec - <unknown>
   8:     0x7fb8187d43b9 - <unknown>
   9:     0x7fb81880e981 - <unknown>
  10:     0x7fb81880e7a3 - <unknown>
  11:     0x7fb818451f03 - <unknown>
  12:     0x7fb818473741 - <unknown>
  13:     0x7fb81848a2f4 - <unknown>
  14:     0x7fb818452ba3 - <unknown>
  15:     0x7fb818452bb9 - <unknown>
  16:     0x7fb8187d4c59 - <unknown>
  17:     0x7fb81848a332 - <unknown>
```

---

**`user@**********:~$ ll /tmp`**

```
total 80
drwxrwxrwt 18 root    root     12288 Jun  6 20:03 ./
drwxr-xr-x 24 root    root      4096 Jun  6 19:33 ../
drwxrwxrwt  2 root    root      4096 Jun  6 19:33 .ICE-unix/
drwxrwxrwt  2 root    root      4096 Jun  6 19:33 .Test-unix/
drwxrwxrwt  2 root    root      4096 Jun  6 19:33 .X11-unix/
drwxrwxrwt  2 root    root      4096 Jun  6 19:33 .XIM-unix/
drwxrwxrwt  2 root    root      4096 Jun  6 19:33 .font-unix/
drwxr-xr-x  2 root    root      4096 Jun  6 19:59 fnm_multishells/
drwxr-xr-x  2 user www-data  4096 Jun  6 19:34 hsperfdata_user/
drwxr-xr-x  2 root    root      4096 Jun  6 19:44 hsperfdata_root/
drwxr-xr-x  2 root    root      4096 Jun  6 19:44 jetty-127.0.0.1-7474-browser-_browser-any-************.dir/
drwx------  3 root    root      4096 Jun  6 19:33 systemd-private-***************-apache2.service-ssW57g/
drwx------  3 root    root      4096 Jun  6 19:33 systemd-private-***************-chrony.service-aV27Rg/
drwx------  3 root    root      4096 Jun  6 19:33 systemd-private-***************-nginx.service-msW3bg/
drwx------  3 root    root      4096 Jun  6 19:33 systemd-private-***************-systemd-logind.service-db79lj/
drwx------  3 root    root      4096 Jun  6 19:33 systemd-private-***************-systemd-resolved.service-sQEp1i/
drwx------  3 root    root      4096 Jun  6 19:33 systemd-private-***************-vnstat.service-i0Qdbf/
drwx------  2 user www-data  4096 Jun  6 19:38 tmux-1000/
```

**Comment by Schniz** [comment]
Maybe the following line is the problem:

```
drwxr-xr-x  2 root    root      4096 Jun  6 19:59 fnm_multishells/
```

Can you try chown or remove it?

**Comment by IceCodeNew** [comment]
> Maybe the following line is the problem:
> 
> ```
> drwxr-xr-x  2 root    root      4096 Jun  6 19:59 fnm_multishells/
> ```
> 
> Can you try chown or remove it?

Thanks for your quick response, it works ;-)

How do you think the following use-case, that multiple users use `fnm` to manage their own nodejs runtime environment. Would it be worth modifying the current behavior so that `fnm` would use `/tmp/alice_fnm_multishells` for the symbolic link path?

**Comment by Schniz** [comment]
I'm not sure if this is worth trying, because they don't mean anything.. multiple users can use the same `/tmp/fnm_multishells` directory: we always generate a unique symlink for every shell 😃 

https://github.com/Schniz/fnm/blob/8729fc7982b0578458baa95827c6909ad2a76680/src/commands/env.rs#L34-L46

fnm used to throw everything in `/tmp`, but some people didn't like all the noise it is making (#419) so we fixed it to be contained in a single directory

**Comment by Tyl3rM** [comment]
Thank you. I'm currently having this problem. Waiting on the next release!

**Comment by adamchalmers** [comment]
I kept experiencing this after upgrading, eventually I uninstalled and reinstalled fnm, then overwrote the old env vars I had set in my .zshrc with the new env vars (from `fnm env`). That fixed it.

**Comment by Schniz** [comment]
Can you please share your .zshrc config section with me?

**Comment by adamchalmers** [comment]
Sure
```diff
--- a/main.zsh
+++ b/main.zsh
@@ -12,9 +12,9 @@ export PATH="/usr/local/bin/code:$PATH"
 DEFAULT_USER=$USER
 
 # fnm
-export PATH="/var/folders/4j/r1kf44dx2xgd5ct6snpxpfy00000gn/T/fnm_multishells/46371_1636061730326/bin":$PATH
-export FNM_MULTISHELL_PATH="/var/folders/4j/r1kf44dx2xgd5ct6snpxpfy00000gn/T/fnm_multishells/46371_1636061730326"
+export PATH="/var/folders/4j/r1kf44dx2xgd5ct6snpxpfy00000gn/T/fnm_multishells/64086_1639164473836/bin":$PATH
+export FNM_MULTISHELL_PATH="/var/folders/4j/r1kf44dx2xgd5ct6snpxpfy00000gn/T/fnm_multishells/64086_1639164473836"
 export FNM_DIR="/Users/adamchalmers/.fnm"
 export FNM_LOGLEVEL="info"
 export FNM_NODE_DIST_MIRROR="https://nodejs.org/dist"
-export FNM_ARCH="x64"
+export FNM_ARCH="x64"
```

**Comment by Schniz** [comment]
Well I guess this is why you had the issue. Please try to replace the entire block with literally the following _instead_ of its output:

```
eval "$(fnm env)"
```

😃

**Comment by nikolay-govorov** [comment]
Hi. Thank you for the work you are doing.

I have this issue if fnm is used in different sessions of several different users (e.g. on diffirint tty). Setup: Arch Linux (`Linux version 5.15.13-arch1-1 (linux@archlinux)`, Fish, Fnm `1.29.2`. 

Steps how to reproduce:
- log in using gooduser username;
- fnm creates `/tmp/fnm_multishells` which will belong to gooduser;
- log in using baduser username;
- fnm won't create new alias in `fnm_multishells` as the folder belongs to `gooduser`.

On behalf of baduser there will be such a picture:
```sh
$ ls -l /tmp/ | grep 'fnm'                                                                                                                                 
drwxr-xr-x 2 gooduser users    80 Jan 22 19:56 fnm_multishells

$ ls -l /tmp/fnm_multishells/
total 0
lrwxrwxrwx 1 gooduser users 35 Jan 22 19:56 1505_1642870618489 -> /home/gooduser/.fnm/aliases/default
lrwxrwxrwx 1 gooduser users 35 Jan 22 19:55 893_1642870526293 -> /home/gooduser/.fnm/aliases/default

$ fnm env 
thread 'main' panicked at 'Can't create symlink!: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/commands/env.rs:44:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

If I make this folder public (`sudo chmod ugo+rw -R /var/share`), then everything will work great.

I do not know all the details of the implementation in the project, but I assume that creating a shared folder without sudo will not work, but separate folders for different users would solve the problem. Or a parameter to set your own folder (in each user's .bashrc).

@Schniz, what do you think about it?

**Comment by nikolay-govorov** [comment]
Now I use such a hack (before `fnm env` in my shell config), but I'm not sure that making this folder shared is a good idea.

```
bash -c "if ! [ -d /tmp/fnm_multishells/ ]; then mkdir -p '/tmp/fnm_multishells' && chmod ugo+rw '/tmp/fnm_multishells'; fi;"
```

**Comment by Schniz** [comment]
We're working on storing the multi shells somewhere else. It will probably be in a user-owned directory now.  

Related:
* #638
