### ISSUE TITLE
Installing Fish Completions

### ISSUE THREAD

**Issue by idkjs** [Schniz/fnm#490]
How do you install these completions? running `fnm completions` logs them out to terminal. 
`fnm completions --help` doesnt have an option. 

Thanks
```sh
> fnm completions --help
fnm-completions 1.25.0
Print shell completions to stdout

USAGE:
    fnm completions [OPTIONS]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
        --arch <arch>
            Override the architecture of the installed Node binary. Defaults to arch of fnm binary [env: FNM_ARCH]
            [default: x64]
        --fnm-dir <base-dir>                     The root directory of fnm installations [env: FNM_DIR]
        --log-level <log-level>                  The log level of fnm commands [env: FNM_LOGLEVEL]  [default: info]
        --node-dist-mirror <node-dist-mirror>
            https://nodejs.org/dist/ mirror [env: FNM_NODE_DIST_MIRROR]  [default: https://nodejs.org/dist]

        --shell <shell>
            The shell syntax to use. Infers when missing [possible values: zsh, bash, fish, powershell, elvish]

```

Thank you.

**Comment by Schniz** [comment]
Homebrew installs them for you. If you don't use Homebrew, you can follow [your shell guide on how to install completions](https://fishshell.com/docs/current/completions.html). I just tried the following and it worked:

```
fnm completions --shell=fish > ~/.config/fish/completions/fnm.fish
```

**Comment by Schniz** [comment]
![image](https://user-images.githubusercontent.com/2054772/124941006-208c5400-e013-11eb-8252-79f954e74110.png)

**Comment by idkjs** [comment]
I need your terminal. That is so clear to read. Also, I guess I was assuming there was some magic command instead of just doing what i have done a hundred times, `fnm completions --shell=fish > ~/.config/fish/completions/fnm.fish`. Sorry about that. And thank you.
