### ISSUE TITLE
Error when adding ZSH completions

### ISSUE THREAD

**Issue by JuanM04** [Schniz/fnm#491]
After adding the ZSH completions, it throws this error:

```
_arguments:comparguments:325: can only be called from completion function
```

**Comment by WolfSkin0** [comment]
Zsh is a bit weird with its completions at times.
Depending on how you've setup your shell, you have multiple options. Easiest is creating a folder in fpath that you can access, to put the completions there:
```zsh
# Create a folder you an write to in home
mkdir $HOME/.zfunc
# Add the folder to zsh's fpath
echo "fpath+=~/.zfunc" >> $HOME/.zshrc
# Write the completions into a file in that folder. Notice the _ in front
fnm completions --shell zsh > $HOME/.zfunc/_fnm
```
Alternatively, you can write the `_fnm` file into `/usr/local/share/zsh/site-functions` afaik.

Hope that helps :3

**Comment by JuanM04** [comment]
Thank you! That solved it
