### ISSUE TITLE
`node` always using system instead of fnm

### ISSUE THREAD

**Issue by ryanccn** [Schniz/fnm#494]
I installed fnm using `curl -fsSL https://fnm.vercel.app/install | bash` normally, but although the fnm `multishell` directory *is* in the `PATH`, when I execute `node --version` it always is the system version rather than the fnm version.

## Environment

- MacBook Pro
- macOS Big Sur v11.4 (latest, stable)
- Apple M1 chip
- `zsh` shell

## Screenshots

<img width="650" alt="Screen Shot 2021-07-19 at 11 29 23 AM" src="https://user-images.githubusercontent.com/70191398/126098605-410fe16e-3c26-44b2-8d38-0b2fe4a221cf.png">

<img width="650" alt="Screen Shot 2021-07-19 at 11 28 25 AM" src="https://user-images.githubusercontent.com/70191398/126098528-31b3fe12-ce5e-4c57-85cc-279b77f478e1.png">

**Comment by Schniz** [comment]
I thought I already commented on that. Sorry.
Can you try running `rehash`?

**Comment by ryanccn** [comment]
<img width="717" alt="Screen Shot 2021-07-22 at 12 50 52" src="https://user-images.githubusercontent.com/70191398/126591381-853a848f-9c40-4c52-b4a7-1eb78ccec712.png">

**Comment by ryanccn** [comment]
@schniz What does `rehash` do, by the way? Curious 😀

**Comment by Schniz** [comment]
Bash and some Zsh shells cache the locations of executables to not look them up in all of your `PATH`. for some reason, my Zsh does not do it, but for some friends it does. Anyway, `rehash` refreshes the cache 😃 

* Do you have nvm installed maybe? Do you have something else in your `.zshrc` file? Can we isolate fnm and only have it in zshrc to see if it works in isolation?
* Can you try running `fnm exec --using=14 node --version`?

**Comment by balazs-endresz** [comment]
I had a similar issue on bash too and noticed that the readme mentions `fnm env --use-on-cd` but after installing it with the script I was told to add only ``eval "`fnm env`"`` without `--use-on-cd`. Could that be the reason why it's not switching automatically?

Also you might want to look for the nvmrc file in parent directories too, with something like this:

```
function find-up() {
    path=$(pwd)
    while [[ "$path" != "" && ! -e "$path/$1" ]]; do
        path=${path%/*}
    done
    echo "$path"
}
``` 

I think it doesn't do that here: https://github.com/Schniz/fnm/blob/57277df20eeeaad341553e95ccb5b41adfce88f5/src/shell/bash.rs#L24-L28

**Comment by Schniz** [comment]
The problem seems to be unrelated to `--use-on-cd`. fnm does not switch versions with a manual `fnm use`

**Comment by ryanccn** [comment]
<img width="717" alt="Screen Shot 2021-07-24 at 18 00 46" src="https://user-images.githubusercontent.com/70191398/126865042-42236e17-f35d-4a16-a262-03e6e93b7ea2.png">

Interestingly after I've installed Rosetta switching to `v14.17.3` works as expected. The Node binary for this version is `x64` arch.

Does `zsh` fallback to other executables if the arch doesn't match? 🤔

**Comment by Schniz** [comment]
Ahhhh. Probably!
Didn't know you don't have Rosetta installed. I don't own an M1 machine so I guess Rosetta is required for Node version lower than 16. Maybe we can emit a warning when installing them if the current machine does not have Rosetta.

**Comment by ryanccn** [comment]
Maybe there should be an option to compile an executable on local?

**Comment by Schniz** [comment]
See #488

**Comment by ryanccn** [comment]
👍 closing this issue
