### ISSUE TITLE
Release a Homebrew formula

### ISSUE THREAD

**Issue by yardnsm** [Schniz/fnm#5]
It'll be awesome to have a [Homebrew formula](https://docs.brew.sh/Formula-Cookbook) so it can be installed using Homebrew. I can tackle this if you'd like.

Awesome work btw!

**Comment by Schniz** [comment]
I would be happy to get help with that!

**Comment by flesch** [comment]
:wave: Hi @Schniz and @yardnsm!

I just submitted a pull request adding this to Homebrew: https://github.com/Homebrew/homebrew-core/pull/36744.

**Comment by Schniz** [comment]
Yay! Thanks @flesch 😸

**Comment by Schniz** [comment]
Let's hope they'll merge it. If they do, we can add `brew install fnm` to the README 😄

**Comment by Schniz** [comment]
`brew install Schniz/tap/fnm` 😄
