### ISSUE TITLE
Tests: use another Node.js mirror

### ISSUE THREAD

**Issue by Schniz** [Schniz/fnm#51]
Taobao (Chinese Node.js mirror) is making our tests flakey and slow.
I guess we can setup a simple server to something like netcat and proxy all requests to nodejs, making it a proxy instead of a mirror, but that acts the same?
maybe drop the test or something?

**Comment by wangzuo** [comment]
What about [r.cnpmjs.org](https://cnpmjs.org/) ? The taobao mirror actually syncs from it and its generally 50% faster when testing outside China.

**Comment by Schniz** [comment]
Sounds good. I'll try and switch to that! thanks
