### ISSUE TITLE
Load .nvmrc / .node-version on shell startup (PowerShell)

### ISSUE THREAD

**Issue by naoey** [Schniz/fnm#513]
Wasn't sure about bumping an old and closed issue, but I'm seeing the same issue as #410 except with PowerShell on Windows 10. The `.nvmrc` is not auto loaded on startup.

**Comment by Schniz** [comment]
Would you like to send a PR that will call `If ((Test-Path .nvmrc) -Or (Test-Path .node-version)) { & fnm use }`?

https://github.com/Schniz/fnm/blob/fd584746a6206d4138f35966629c000026f5fe96/src/shell/powershell.rs#L22-L25

Maybe we can create a function that has the `If` inside it, and use it in `Set-LocationWithFnm` 😃

**Comment by Schniz** [comment]
I don't own a Windows machine, so I'd be happy to have some help here 😃
