### ISSUE TITLE
Latest 1.26.0 not available on crates.io

### ISSUE THREAD

**Issue by ariasuni** [Schniz/fnm#517]
I use `cargo install fnm` to have the latest version, unfortunately latest version is not available this way.

**Comment by Schniz** [comment]
You are right. I forgot to publish it. I will do it next week. Need to automate this! 😅 sorry in the meantime

**Comment by Schniz** [comment]
published 🙏 
https://crates.io/crates/fnm/1.26.0

**Comment by ariasuni** [comment]
That was fast, thanks. :smile:
