### ISSUE TITLE
When a version does not exist, fnm exists with status code 0

### ISSUE THREAD

**Issue by ranyitz** [Schniz/fnm#53]
After using `fnm install` I got an informative message `Version v8 not found!` It said that the task was not sucessfull, but It would be better if the color would be red.

I also expected the status code for unsuccessful oparation to be `1` instead of `0`.

![image](https://user-images.githubusercontent.com/11733036/53013350-3bfc6180-344e-11e9-8fe3-250139c260b8.png)

**Comment by Schniz** [comment]
Hey and welcome 👋 

I think it is a relatively easy fix, so I will wait for a PR from someone who wants to try programming in Reason 😄 

Here's a reference to a fix for the last issue by @compilenix: https://github.com/Schniz/fnm/pull/45

**Comment by ranyitz** [comment]
@Schniz Thanks!
I'd like to take this one 👍
