### ISSUE TITLE
[windows] Git-bash asks for privileges 

### ISSUE THREAD

**Issue by zeljkomarinkovic** [Schniz/fnm#538]
Installed fnm on windows using choco and added fnm to PATH and added `eval $(fnm env)` to .bashrc. While it works great in powerShell its quite annoying in git-bash which throws this error when not running as admin

```
thread 'main' panicked at 'Can't create symlink!: Os { code: 1314, kind: Other, message: "A required privilege is not held by the client." }', src\commands\env.rs:44:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by zeljkomarinkovic** [comment]
Found out too late but this is related to https://github.com/Schniz/fnm/issues/338

**Comment by Schniz** [comment]
Is it still the case with the latest release? What version of fnm are you using? we now use junctions (thanks to #519)

**Comment by zeljkomarinkovic** [comment]
Installed with `choco install fnm` which installed `1.26.0`

**Comment by zeljkomarinkovic** [comment]
Just upgraded and can confirm that it works fine with latest version

**Comment by Schniz** [comment]
Amazing! thank you @davidaurelio 

closing 😃
