### ISSUE TITLE
fnm env produce error: Can't infer shell!

### ISSUE THREAD

**Issue by codeitlikemiley** [Schniz/fnm#561]
Recently im facing this error,
```
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* cmd
* powershell
* bash
* zsh
* fish
```
Im using windows 11 , and before im not facing this issue,
i did try to reinstall fnm and build from cargo
but the error persist.

is there a way to fix this?
Only in windows this is persisting, im using it in all my dev machine, artix linux, mac big sur no problem.

hope this will be resolve
coz the command wont simple generate the correct fnm path for windows now.
so the command node and npm are both not found.

i just use pure node js installation for now until this is resolve 
thanks for building fnm

**Comment by dabide** [comment]
@Schniz Would it also be an idea to be able to specify the shell type on the command line? That would both make it future proof _and_ even faster.

**Comment by dabide** [comment]
There is a workaround, @codeitlikemiley : You can specify the shell on the command line, like this: `fnm env --use-on-cd --shell powershell | Out-String | Invoke-Expression`

**Comment by rhacker** [comment]
@dabide thanks for this, it works perfectly fine :)

**Comment by Schniz** [comment]
I really think about deprecating the automated shell check, it makes so much sense to just provide it when installing. The magic is fragile.

**Comment by radiorz** [comment]
> There is a workaround, @codeitlikemiley : You can specify the shell on the command line, like this: `fnm env --use-on-cd --shell powershell | Out-String | Invoke-Expression`

works for me

**Comment by mk6281** [comment]
i am also facing this issue
