### ISSUE TITLE
[FEATURE REQUEST] Support for parameter "which"

### ISSUE THREAD

**Issue by silvioprog** [Schniz/fnm#567]
Hi.

Firstly, thanks a lot for this incredible tool! 👏

So, it would be nice some option to show the full path where a Node version is installed, something like this:

```bash
fnm which v17.0.1
/home/some-user/.fnm/node-versions/v17.0.1/installation/bin/node
```

The `pyenv` tool supports this option: [github.com/pyenv/pyenv/COMMANDS.md#pyenv-which](https://github.com/pyenv/pyenv/blob/master/COMMANDS.md#pyenv-which).

What do you think about to implement it in `fnm`? 😅

cheers

**Comment by Schniz** [comment]
Doing it should be fairly straightforward to contribute, but I wonder if this is necessary:

* What would we print if we are using the system version? "system version" in fnm means that we are _bypassing_ fnm, so it does not know about the Node version
* It is basically `realpath $(which node)` and that would give you more accurate results (unless we're willing to debug an issue, and then we would want to know the difference between the output of the previous command and the current expected Node version based on fnm)

What are your use cases for this command? 😃

**Comment by silvioprog** [comment]
@Schniz, thanks a lot for answering! 🙂

Using `realpath $(which node)`, it returned the properly Node path. The first time I tested using `which node`, that returned `/tmp/fnm_multishells/15703_1636040358525/bin/node`, but, after `realpath`, it returned `/home/my-username/.fnm/node-versions/v17.0.1/installation/bin/node`, so it seems the `which` parameter would be useless.
