### ISSUE TITLE
Can I use fnm on top of the nvm already installed?

### ISSUE THREAD

**Issue by Dingzhaocheng** [Schniz/fnm#569]
#### hi , I already have nvm installed, and I installed fnm on top of that, and although I installed the specified node version using fnm install, the node -v output is still the version used by nvm
Here are some relevant facts：
<img width="596" alt="截屏2021-11-10 上午11 53 36" src="https://user-images.githubusercontent.com/38446493/141046534-14c6eb76-450f-43a6-999f-04b00cd1f0ce.png">

**Comment by Schniz** [comment]
fnm does not work with nvm installed and sourced. why do you want to run them both at the same time?

**Comment by ljharb** [comment]
Why doesn't it? nvm uses the PATH; i assume that fnm's shims are either higher in precedence in the PATH than nvm, or lower, so that it either takes precedence, or `nvm use system` is required to defer to fnm?

**Comment by Schniz** [comment]
I am not really sure how nvm works and I only know that when I started implementing fnm, it clashed with nvm for some reason that I have never tried to figure out. We need to see @Dingzhaocheng to know which one is taking precedence, as fnm uses PATH as well (with a symlink)

**Comment by ljharb** [comment]
nvm is a sourced shell function; all it does is change the `PATH` to include the intended node version's directory (and removes any unintended ones that are inside `$NVM_DIR`)

**Comment by Dingzhaocheng** [comment]
I'm sorry, it's really not a big problem, I've used nvm before this and it's really popular and I wanted to experience the new features of fnm. And after I restarted the terminal fnm started to take effect.
<img width="573" alt="截屏2021-11-10 下午6 57 46" src="https://user-images.githubusercontent.com/38446493/141100489-5dfce8f3-066b-4e83-bcbe-09b8f004ef93.png">
.

**Comment by Schniz** [comment]
hmm, so it looks like fnm is not being evaluated at all.
Can you share your `$PATH` env var?

**Comment by Dingzhaocheng** [comment]
<img width="580" alt="截屏2021-11-11 上午10 06 41" src="https://user-images.githubusercontent.com/38446493/141224018-fb44101f-72fa-4fff-80e2-f16f5f80d75d.png">
.

**Comment by Schniz** [comment]
looks like you did not set up fnm in your shell profile: https://github.com/Schniz/fnm#shell-setup

**Comment by Dingzhaocheng** [comment]
I did this, but restarting the terminal will not work and I need to set it up again

**Comment by Schniz** [comment]
Can you please explain what does it mean "restarting the terminal will not work"?

**Comment by Dingzhaocheng** [comment]
When reopening the terminal, I need to set the environment variables again for it to work
<img width="1066" alt="截屏2021-11-11 下午5 47 20" src="https://user-images.githubusercontent.com/38446493/141275870-f5dbbfd4-a87a-42d3-9b68-d89161cd33f6.png">
.
You can see that the environment variables have been set on the left, but opening a new terminal (on the right) still requires re-executing eval "$(fnm env)"

**Comment by Schniz** [comment]
Every shell needs to evaluate it, just like your nvm setup. You can append the following to `~/.zshrc`:

```zsh
eval "$(fnm env --use-on-cd --shell=zsh)"
```

**Comment by Dingzhaocheng** [comment]
thanks

**Comment by Schniz** [comment]
Does it work? does it help? :)

**Comment by Schniz** [comment]
ping

**Comment by Dingzhaocheng** [comment]
Sorry sir for replying you only now, this works very well for me, this project is very nice！
