### ISSUE TITLE
error: Can't create the symlink: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by andyfleming** [Schniz/fnm#582]
```
$ fnm ls
* v16.13.0 default
* system
```

```
$ fnm use v16
Using Node v16.13.0
error: Can't create the symlink: No such file or directory (os error 2)
```

Installed originally with brew. Uninstalled, removed `~/.fnm`, and reinstalled, and still get the same error message.

This is on an M1 Macbook Pro. It was previously working. This may have been caused by installing the patch for 12.0.1.

**Comment by Schniz** [comment]
Eh. Sorry that it does not work. Let's try to debug it. What do you mean by "patch for 12.0.1"? 

Can you show me the output of the following commands:

```
env | grep FNM_
echo $PATH
ls -la /tmp/fnm_multishell
```

**Comment by andyfleming** [comment]
Patch for 12.0.1 is in reference to the macOS version.

```
[  1:30PM ] ~/src/github.com/andyfleming  $ env | grep FNM_
echo $PATH
ls -la /tmp/fnm_multishell
FNM_MULTISHELL_PATH=/var/folders/0q/ycpq7ksn6xz1crxc5ljvdq640000gn/T/fnm_multishells/23646_1635277188471
FNM_DIR=/Users/andyfleming/.fnm
FNM_LOGLEVEL=info
FNM_NODE_DIST_MIRROR=https://nodejs.org/dist
FNM_ARCH=arm64
/var/folders/0q/ycpq7ksn6xz1crxc5ljvdq640000gn/T/fnm_multishells/23646_1635277188471/bin:/var/folders/0q/ycpq7ksn6xz1crxc5ljvdq640000gn/T/frum_13509_1637530215080/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/andyfleming/.cargo/bin:/Users/andyfleming/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin/
ls: /tmp/fnm_multishell: No such file or directory
```

**Comment by koalazub** [comment]
Hey! Just letting you know that I'm running into the same issue in Mac OS Monterey. Below are the logs:

```
env | grep FNM_
echo $PATH
ls -la /tmp/fnm_multishell
FNM_MULTISHELL_PATH=/var/folders/9m/hdjt59lj29j02q2qqbr7sn240000gn/T/fnm_multishells/89345_1637653971469
FNM_DIR=/Users/username/.fnm
FNM_LOGLEVEL=info
FNM_NODE_DIST_MIRROR=https://nodejs.org/dist
FNM_ARCH=x64
/usr/local/opt/php@7.4/bin:/usr/local/anaconda3/bin:/Users/username/.local/bin/lvim:/Users/username/.deno/bin:/usr/local/sbin:/var/folders/9m/hdjt59lj29j02q2qqbr7sn240000gn/T/fnm_multishells/89345_1637653971469/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/username/.cargo/bin:/usr/local/opt/go/libexec/bin:/Users/username/.cargo/bin:/bin
"/tmp/fnm_multishell": No such file or directory (os error 2)
```

fnm version is `fnm 1.28.1`

**Comment by Schniz** [comment]
Can you both please let me know what the following outputs:

```bash
ls -la $(dirname $FNM_MULTISHELL_PATH)
ls -lah $FNM_MULTISHELL_PATH
```

**Comment by koalazub** [comment]
Getting the following:

```zsh
lrwxr-xr-x 36 username 23 Nov 18:52 89345_1637653971469 -> /Users/username/.fnm/aliases/default
"/var/folders/9m/hdjt59lj29j02q2qqbr7sn240000gn/T/fnm_multishells/77367_1637650514883": No such file or directory (os error 2)
```

**Comment by andyfleming** [comment]
I get the following:

```
ls: /var/folders/0q/ycpq7ksn6xz1crxc5ljvdq640000gn/T/fnm_multishells: No such file or directory
ls: /var/folders/0q/ycpq7ksn6xz1crxc5ljvdq640000gn/T/fnm_multishells/23646_1635277188471: No such file or directory
```

**Comment by Schniz** [comment]
> I should also note that I have tried uninstalling node, npm and fnm on top of deleting their respective configuration files to see if that would help with the symlink issue.

The only thing that could probably help is `rm -rf /var/folders/9m/hdjt59lj29j02q2qqbr7sn240000gn/T/fnm_multishells` but it is a temporary path anyway. VERY weird.



> ```
> ls: /var/folders/0q/ycpq7ksn6xz1crxc5ljvdq640000gn/T/fnm_multishells: No such file or directory
> ls: /var/folders/0q/ycpq7ksn6xz1crxc5ljvdq640000gn/T/fnm_multishells/23646_1635277188471: No such file or directory
> ```

this is very weird either. I'm pushing a PR with a build that generates a warning when `fnm_multishells` can't be created that I would like you to try :)

**Comment by koalazub** [comment]
Before even attempting to remove the temporary path files it was able to work again? This was bizarre. I'm not sure where to go with this besides stating that I'd done the following:

- brew cleanup
- update all cargo packages
- restart the computer

I should also note that this was in the middle of shifting everything to a [.dotfiles](https://dotfiles.github.io/) setup that uses [GNU stow](https://www.gnu.org/s/stow/manual/stow.html). 

I think the final order after performing a `stow -vRt ~ *` was to reboot? I didn't have `.fnm` as part of my transition into a `.dotfiles` setup. 

I don't think a lot of this information is useful, but I hope it can create some form of a context for what has potentially happened

**Comment by florianfranconi** [comment]
Same error under macOS Monterey and fnm `v1.28.2`

**Comment by Schniz** [comment]
@florianfranconi  can you please share your zshrc?

**Comment by florianfranconi** [comment]
> @florianfranconi can you please share your zshrc?

Sure, here it is : 

```shell
export PATH="/var/folders/rq/f8drh_px5pq9hv1m58b4xpfm0000gn/T/fnm_multishells/6838_1639391173356/bin":$PATH
export FNM_MULTISHELL_PATH="/var/folders/rq/f8drh_px5pq9hv1m58b4xpfm0000gn/T/fnm_multishells/6838_1639391173356"
export FNM_DIR="/Users/florianfranconi/.fnm"
export FNM_LOGLEVEL="info"
export FNM_NODE_DIST_MIRROR="https://nodejs.org/dist"
export FNM_ARCH="x64"
autoload -U add-zsh-hook
_fnm_autoload_hook () {
    if [[ -f .node-version || -f .nvmrc ]]; then
        fnm use
    fi
}

add-zsh-hook chpwd _fnm_autoload_hook \
    && _fnm_autoload_hook
```

**Comment by Schniz** [comment]
Please replace all of this code with literally:

```
eval "$(fnm env --use-on-cd)"
```

Instead of having the output of the command

**Comment by florianfranconi** [comment]
It seems to work for the moment

The last time the error appeared randomly after a reboot, I'll keep an eye on it

**Comment by Schniz** [comment]
It makes sense, since `fnm env` creates the temp directory. It's not a pure command, as it's preparing the environment for fnm

**Comment by andyfleming** [comment]
Installing the latest version and updating my `.zshrc` with the output of `fnm env` (instead of the previous content that was there from fnm) seemed to solve the issue.

**Comment by Schniz** [comment]
please don't use the output of fnm env but use `eval "$(fnm env ...)"`. Regenerating the output each time is important. Otherwise we will get the same curtain all over again.
