### ISSUE TITLE
Add install --default to quickly set the default version

### ISSUE THREAD

**Issue by jungaretti** [Schniz/fnm#589]
Is there an easier way to install a new version of Node and quickly update my default version? Here's my current approach...

```sh
fnm install 17.2.0
# Installing Node v17.2.0 (x64)
fnm default 17.2.0
```

A new `install --default` option could simplify this to just one step...

```sh
fnm install --default 17.2.0
# Installing Node v17.2.0 (x64) and setting default
```

**Comment by Schniz** [comment]
Hi, thanks for the idea. I wonder if extending the API provides a big difference here. This can simplify the process, but I wonder whether this process is so frequently happening that we need to simplify it by making a larger API surface. What do you think? do you find yourself changing the default version frequently?

**Comment by jungaretti** [comment]
I don't change the default version too often, and I've changed my mind on this issue. A well-considered and well-maintained API is more valuable than accommodating every edge case.

Cheers and thanks for your great work on fnm!
