### ISSUE TITLE
Auto upgrade fnm version

### ISSUE THREAD

**Issue by Schniz** [Schniz/fnm#59]
On a schedule? check once per week or something?

**Comment by ljharb** [comment]
of node or of fnm? if the former, that sounds very intrusive.

**Comment by Schniz** [comment]
You are totally right. I’m talking about fnm, similarly to oh-my-zsh. Maybe not even upgrading - just telling that there’s a new version available

**Comment by compilenix** [comment]
I would like to add that the online version check sould have a fairly small timeout to ensure that the command is not stalling for multiple seconds within a interactive or offline enviroment.

**Comment by Schniz** [comment]
of course. Making things slow isn't on the roadmap. I'm already torn on "auto upgrade" anyway, so even a `fnm upgrade` command sounds good to me

**Comment by MoOx** [comment]
I currently blindly use this alias `alias fnm-upgrade="curl https://raw.githubusercontent.com/Schniz/fnm/master/.ci/install.sh | bash -s -- --skip-shell"` as soon as I see a new version (by watching github release) :)
Something more "native" would be sweet :)

**Comment by Schniz** [comment]
fnm is now installable using Homebrew!

**Comment by paambaati** [comment]
@Schniz That is fantastic news! What’s the best way to uninstall my current installation?

**Comment by Schniz** [comment]
I guess `rm ~/.fnm/fnm && brew install Schniz/tap/fnm` will do the trick!
Homebrew will look for `# fnm` comment in your {z,fi,ba}sh config file and if it finds it, the config file won't be altered 😄

**Comment by Schniz** [comment]
I'm closing this in favor of package managers (Homebrew, AUR etc)
