### ISSUE TITLE
http requests doesn't have the `User-Agent` header

### ISSUE THREAD

**Issue by ysc3839** [Schniz/fnm#593]
It looks like fnm's http requests doesn't have the `User-Agent` header, which cause some mirror site refuse to work.

For example:
```
export FNM_NODE_DIST_MIRROR=https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/
fnm install 16
```
Will get `error: Can't download the requested binary: Can't extract the file: invalid Zip archive`
After `export RUST_LOG=debug` you can see 403 Forbidden.

Here's another issue: fnm should report http request error instead of ignore and continue extracting.
And `FNM_LOGLEVEL` env seems not working, I have to set `RUST_LOG` to see debug logs.

**Comment by Schniz** [comment]
Hi, did you happen to have the latest version?

```
FNM_NODE_DIST_MIRROR=https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/ fnm ls-remote
```

works for me

**Comment by ysc3839** [comment]
`ls-remote` is working with this mirror, but downloading is not allowed.
