### ISSUE TITLE
Security contact?

### ISSUE THREAD

**Issue by nightwatchcyber** [Schniz/fnm#597]
Hi - is there a good security contact for this project? Thanks

**Comment by Schniz** [comment]
Hey, what do you mean by security contact?

**Comment by nightwatchcyber** [comment]
For reporting a security issue with the project or ask security questions?

See:
https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

**Comment by Schniz** [comment]
Feel free to [DM me on Twitter](https://twitter.com/galstar), email me, or use whatever platform you want to reach out. I will try to respond as quickly as I can 😃

Too bad that GitHub does not have "[confidential issues](https://docs.gitlab.com/ee/user/project/issues/confidential_issues.html)"

**Comment by nightwatchcyber** [comment]
Thank you
