### ISSUE TITLE
Cannot find node in pre-commit check when committing in vscode's source control panel

### ISSUE THREAD

**Issue by daolanfler** [Schniz/fnm#602]
I'm using vscode's source control panel to do commit (with a precommit check) , but I got this error:  

![image](https://user-images.githubusercontent.com/29777079/146110560-fcd32c5f-77cc-4d83-980c-3914365ed8cc.png) 

I'm using git bash as vscode's integrated termial, I can do commit in command line but **not in the gui**. 
And I've also set the powershell profile as described in readme because I'm not sure if the vsocde **git commit gui** uses powershell or git bash, but that doesn't work either. 

Is there any workaround in fnm or should I tweak with the vscode settings?

**Comment by daolanfler** [comment]
I see. After digging into the git log error and look into the **pre-commit hook**, I find that the hook script is not evaluating fnm. Add following lines (found here #390 ), problem temporarily solved:  
``` diff
**apparently no node in this PATH**
# Node standard installation
export PATH="$PATH:/c/Program Files/nodejs"

+ # evaluate fnm 
+ eval $(fnm env | sed 1d)
+ export PATH=$(cygpath $FNM_MULTISHELL_PATH):$PATH

# Export Git hook params
export GIT_PARAMS="$*"
```
And this seems to be similar with #428

**Comment by daolanfler** [comment]
And this project is using yorkie which is a fork of husky

**Comment by meteorlxy** [comment]
For someone like me, remember to change the default profile of VSCode integrated terminal:

```
"terminal.integrated.defaultProfile.osx": "zsh"
```

https://code.visualstudio.com/docs/editor/integrated-terminal#_configuring-profiles
