### ISSUE TITLE
Node 18 Nightly support

### ISSUE THREAD

**Issue by matteoturini** [Schniz/fnm#610]

**Comment by matteoturini** [comment]
All nightly builds are listed [here](https://nodejs.org/download/nightly/)

**Comment by matteoturini** [comment]
Found out how, but should be implemented as a flag.

`fnm --node-dist-mirror https://nodejs.org/download/nightly/ 18`

I think implementing `fnm --nightly install 18` would be nicer.

**Comment by Schniz** [comment]
Sounds interesting, as if it is a "preset". Maybe we can have more than `nightly`, but other standard mirrors?

**Comment by Schniz** [comment]
The only thing that bothers me with `--nightly` is that it extends the public API. and reusing node-dist-mirror like `--node-dist-mirror=@nightly` is too magical

**Comment by alexeyten** [comment]
IMHO, you shouldn't do this.

Nightly build are barely useful for anyone except a really small amount of people.

As there is a solution with `--node-dist-mirror` one could just create alias for it (e.g. `alias fnm-nightly=fnm --node-dist-mirror https://nodejs.org/download/nightly/`).

**Comment by matteoturini** [comment]
People want to test things. I'm not going to use this everyday, but I
wanted to check out Node 18. Adding ***@***.***`` is
perfect.

Em ter., 28 de dez. de 2021 às 10:37, Alexey Ten ***@***.***>
escreveu:

**Comment by Schniz** [comment]
> People want to test things. I'm not going to use this everyday, but I wanted to check out Node 18

What do you think about documenting `--node-dist-mirror=https://nodejs.org/download/nightly/`  as the solution? Is that good enough?

**Comment by matteoturini** [comment]
> > People want to test things. I'm not going to use this everyday, but I wanted to check out Node 18
> 
> What do you think about documenting `--node-dist-mirror=https://nodejs.org/download/nightly/` as the solution? Is that good enough?

That's good, if it's also in fnm --help

**Comment by ljharb** [comment]
Nobody should be testing nightlife’s but node core developers.

**Comment by matteoturini** [comment]
> 

So what??? I was playing with it!

**Comment by Schniz** [comment]
Hi friends,
I'm happy that we have a solution.

As @ljharb mentioned, this is something that will be rarely done with fnm. Therefore, I don't think we should add it to `fnm --help`. Only a handful of people will want to use it, but I'm grateful that I can always link them to your comment (https://github.com/Schniz/fnm/issues/610#issuecomment-999796481) that shows how to use nightlies with fnm if someone will ask :) 🙏 

Closing this issue as we have a working solution. Thanks for your inputs @matteoturini 🙏
