### ISSUE TITLE
Automatic installation script fails

### ISSUE THREAD

**Issue by michelegera** [Schniz/fnm#62]
Hello!

In my ongoing research for a fast, reliable Node Version Manager I came across your project and wanted to check it out! 

When I tried to run the automatic installation script, I got this error:

```
❯ curl https://raw.githubusercontent.com/Schniz/fnm/master/.ci/install.sh | bash
######################################################################## 100.0%
Checking dependencies for the installation script...
Checking availablity of curl... OK!
Checking availablity of unzip... OK!
Downloading https://github.com/Schniz/fnm/releases/download/## ✨ Highlight ✨ \r\n\r\nInference of complete semantic version:\r\n\r\nIn order to download the latest Node 11 version:\r\n\r\n```bash\r\nfnm install 11\r\n```\r\n\r\nIn order to use the latest installed Node 11 version:\r\n\r\n```bash\r\nfnm use 11\r\n```\r\n\r\n## All contributions 👏 🌮 \r\n\r\n#### New Feature 🎉\r\n\r\n- [#60](https://github.com/Schniz/fnm/pull/60) Disable colors for non-tty devices ([@Schniz](https://github.com/Schniz))\r\n- [#48](https://github.com/Schniz/fnm/pull/48) Add parameters to the install script, enabling custom installs (`--install-dir` and `--skip-shell`) ([@from-nibly](https://github.com/from-nibly))\r\n- [#54](https://github.com/Schniz/fnm/pull/54) Infer complete semver (`vX.X.X`) out of partial input (`vX`/`vX.X`). ([@Schniz](https://github.com/Schniz))\r\n\r\n#### Bugfix 🐛\r\n\r\n- [#58](https://github.com/Schniz/fnm/pull/58) Adding check for OSX during writing for bash shell ([@maxknee](https://github.com/maxknee))\r\n- [#56](https://github.com/Schniz/fnm/pull/56) Correct status code on `install` failures ([@ranyitz](https://github.com/ranyitz))\r\n\r\n#### Internal 🛠\r\n\r\n- [#55](https://github.com/Schniz/fnm/pull/55) Make tests faster by using cnpmjs as Node.js mirror in tests ([@Schniz](https://github.com/Schniz))\r\n\r\n#### Documentation 📝\r\n\r\n- [#49](https://github.com/Schniz/fnm/pull/49) Add a `--fnm-dir` option to `fnm env` ([@Schniz](https://github.com/Schniz))\r\n- [#50](https://github.com/Schniz/fnm/pull/50) Added CHANGELOG ([@Schniz](https://github.com/Schniz))/fnm-macos.zip...
```

Looks like the script fails when parsing the `tag_name` of the latest release, possibly because the JSON returned by GitHub API is a one-liner, and `grep` + `sed` cannot parse the tag value.

**Comment by michelegera** [comment]
Let me add that I was able to run the script successfully by copying it on my machine and editing it to set `LATEST_RELEASE` manually, so it should be just a matter of fixing the JSON parsing.

**Comment by Schniz** [comment]
Sorry for taking too much time to answer, @michelegera.

I think it was probably a problem with `curl`ling the GitHub api. I think we should have `set -e` on the top of the installation script, so people would know an error has occured

**Comment by Schniz** [comment]
I'm closing this, because the installation script should throw on any error, since #64.

[As I mentioned on twitter](https://twitter.com/galstar/status/1099626640458612736), the installation script is the most fragile piece of code in this repo. If someone has any ideas how to make it better with good tests, let me know. I can maybe add a scheduled task on CI, that verifies the installation script on Mac and Linux, but it won't stop us from merging bad code.

We can also download the latest release from GitHub everytime on our tests...

If you have any idea - please open a new issue with it!
Thanks again for the report 😄
