### ISSUE TITLE
Shell inference slow on Linux?

### ISSUE THREAD

**Issue by SanchayanMaity** [Schniz/fnm#621]
Continuing the conversation on Twitter, here are the results when `shell` argument is specified and not specified for fish and bash.

For bash

```
$ time eval "$(fnm env)"

real	0m0.501s
user	0m0.004s
sys	0m0.000s

$ time eval "$(fnm env --shell=bash)"

real	0m0.002s
user	0m0.001s
sys	0m0.000s
```

For fish

```
# ~ : time fnm env --shell=fish

________________________________________________________
Executed in    1.40 millis    fish           external
   usr time    0.35 millis  350.00 micros    0.00 millis
   sys time    1.13 millis   45.00 micros    1.09 millis

# ~ : time fnm env

________________________________________________________
Executed in  517.84 millis    fish           external
   usr time    0.45 millis  454.00 micros    0.00 millis
   sys time    3.45 millis   58.00 micros    3.39 millis
```
Results are from running fnm version 1.29.1 on Endeavour/Arch Linux. System has AMD Ryzen 9 3950X and SSD.

**Comment by Schniz** [comment]
Hi! Thanks for opening the issue 😃 
continuing our Twitter conversation, may you please try the following release: https://github.com/Schniz/fnm/releases/tag/v1.27.0 and let me know if this is faster?

This is because https://github.com/Schniz/fnm/releases/tag/v1.28.0 has changed the implementation from using `ps` to `sysinfo`. Maybe that's slower on Linux distros.

I need to automate benchmarking

**Comment by SanchayanMaity** [comment]
The 1.27 version gives these results

```
./fnm --version
fnm 1.27.0

time ./fnm env --shell=fish
________________________________________________________
Executed in    1.81 millis    fish           external
   usr time    1.44 millis    0.00 micros    1.44 millis
   sys time    0.41 millis  408.00 micros    0.00 millis

time ./fnm env
________________________________________________________
Executed in   23.17 millis    fish           external
   usr time    0.33 millis  329.00 micros    0.00 millis
   sys time    2.36 millis   79.00 micros    2.28 millis
```
The result from the latest version again

```
time fnm env
________________________________________________________
Executed in  535.26 millis    fish           external
   usr time    5.00 millis  406.00 micros    4.59 millis
   sys time    0.10 millis   97.00 micros    0.00 millis

```

The 1.27 version seems to give better results for sure.

**Comment by Schniz** [comment]
Cool, I will revert the changes for unix-based systems 😃 

I should've required to provide a shell argument from the get go instead of inferring, huh

**Comment by SanchayanMaity** [comment]
IMO, making the shell argument mandatory is perfectly fine, and especially considering the speed-up. Have defaulted to passing it manually in my own config.
