### ISSUE TITLE
Publish to AUR

### ISSUE THREAD

**Issue by caseyWebb** [Schniz/fnm#63]
It would be nice if this was installable via the [Arch User Repository](https://wiki.archlinux.org/index.php/Arch_User_Repository)

**Comment by Schniz** [comment]
Hey @caseyWebb! sounds cool. I'm not an Arch user, but I'd be love to see that happening!

**Comment by caseyWebb** [comment]
I've never prepped a package for publishing, but if you're interested I can take a look at submitting a PR

**Comment by Schniz** [comment]
That sounds awesome! I'd love to see that. Let me know if you need any help - dependencies, how to build, etc. In v1.6.0 (will be released after CI will pass), we'll drop `curl` as a dependency 😄

**Comment by Schniz** [comment]
Hey @caseyWebb, looks like someone has published it in AUR: https://aur.archlinux.org/packages/fnm-bin/

Is there something we can do to to ensure we update it on every release?

**Comment by Ugzuzg** [comment]
Hello, that was me.
@Schniz, I can add you as a co-maintainer, if you want, then all you'll have to do is bump `pkgver` here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fnm-bin#n4
I am watching the releases of this repo, going to maintain the package to the best of my abilities.

**Comment by Schniz** [comment]
@Ugzuzg that’s awesome! I think we can close this issue, then :) thanks for that — you’re awesome!
