### ISSUE TITLE
Error thrown in FISH-Shell

### ISSUE THREAD

**Issue by trm217** [Schniz/fnm#634]
I setup fnm for FISH as described in the readme. 

This is the created configuration
![image](https://user-images.githubusercontent.com/30313631/149094927-1af26d0d-16ab-4c10-b2b5-11308c21a07f.png)

When I now go into a folder that contains a configuration for what node-version should be used, the following error is thrown:

```
thread 'main' panicked at 'Can't write output: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/commands/use.rs:93:13              (base)
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <fnm::commands::use::Use as fnm::commands::command::Command>::apply
   4: fnm::commands::command::Command::call
   5: fnm::cli::SubCommand::call
   6: fnm::main
   ```
   
I am unsure what to make out of this error. Is this even a error caused by FNM or might it be caused by my FISH-configuration?

**Comment by trm217** [comment]
I just noticed, it seems to be the same issue as mentioned in #356

**Comment by Schniz** [comment]
Cool! we can reopen if things don't end up the same. thanks
