### ISSUE TITLE
How to install latest node with --LTS

### ISSUE THREAD

**Issue by dennisbaum** [Schniz/fnm#644]
Can we install the latest node version with long time support automaticly?
i.e. fnm install latest --lts

thx

**Comment by alexeyten** [comment]
What wrong with `fnm install --lts`?

**Comment by dennisbaum** [comment]
fnm install latest
error: The requested version is not installable: latest  

fnm install latest --lts
error: The argument '<version>' cannot be used with '--lts'

**Comment by dennisbaum** [comment]
sorry. get it now :)
fnm install --lts
could be so easy

**Comment by Schniz** [comment]
I understand the confusion @dennisbaum! Thanks for helping out @alexeyten 👑

**Comment by dennisbaum** [comment]
maybe another stupid question, but how to install the latest non-lts?

**Comment by alexeyten** [comment]
AFAIK there is no `latest` version tag. But you could use partial version number.
E.g.
`fnm install 17.3.0` will install exact version.
`fnm install 17.3` will install latest of `17.3.x`, in this case it would be `17.3.1`
and `fnm install 17` will install latest of `17.x.x`, that is `17.4.0` at the moment.

**Comment by dennisbaum** [comment]
ok. thx @alexeyten
