### ISSUE TITLE
fnm env panics when it fails to create a symlink

### ISSUE THREAD

**Issue by AlexAegis** [Schniz/fnm#655]
running fnm env on macOS Big Sur, Kitty, zsh results in this error:

```sh
RUST_BACKTRACE=full fnm env                                                                                                                                                                    
thread 'main' panicked at 'Can't create symlink!: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/commands/env.rs:46:58
stack backtrace:
   0:        0x105e9950a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h533490cb0144b9ac
   1:        0x105eca2eb - core::fmt::write::hd6db5571778cce6c
   2:        0x105e8994a - std::io::Write::write_fmt::h3b731249d14dbbaf
   3:        0x105e90195 - std::panicking::default_hook::{{closure}}::h47e90b77f003c5b7
   4:        0x105e8fd6e - std::panicking::default_hook::ha5ca508e09960444
   5:        0x105e9079a - std::panicking::rust_panic_with_hook::hc8381a31241f686e
   6:        0x105e99e2e - std::panicking::begin_panic_handler::{{closure}}::h459ea290df0e978a
   7:        0x105e99667 - std::sys_common::backtrace::__rust_end_short_backtrace::h7b815ac00a857fce
   8:        0x105e90283 - _rust_begin_unwind
   9:        0x105ee1fbf - core::panicking::panic_fmt::hedd127944bd71c57
  10:        0x105ee24b5 - core::result::unwrap_failed::h191e80e385ea5324
  11:        0x105ac60d3 - fnm::commands::command::Command::call::h73a2ef92774bb0fb
  12:        0x105acaecc - fnm::cli::SubCommand::call::hce55aeb7418b87f4
  13:        0x105b016ac - fnm::main::h9d9854dff2847d9c
  14:        0x105ab9a06 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbcf81bab5596860b
  15:        0x105ac789c - std::rt::lang_start::{{closure}}::hc4e58dd743d675b3
  16:        0x105e82ce5 - std::rt::lang_start_internal::h63a1a32878b6f038
  17:        0x105b01dd9 - _main
```

If the problem is at my end (which I highly suspect) then please provide a more detailed error message and some tips on how to resolve it.

**Comment by AlexAegis** [comment]
Update: So after checking the `FNM_DIR` location and the multishells cache dir, the permissions looked alright. I ran a very aggressive `chown -R` on my home folder and now it works. But I still not sure what was that other folder that caused problems. Having a glance at the source code it only ever interacts with FNM_DIR which on macOS by default is `~/Library/Application\ Support/fnm`. 

I guess this is a relatively new development as I remember fnm used `~/.fnm` before so I do have an `FNM_DIR` env var set up, pointing to  `~/Library/fnm`. I then suspected it might not respect this variable for one step. I then checked `~/Library/Application\ Support/fnm` and it was there with an empty `aliases` folder. I deleted it but on re-running `fnm env` it was not re-created.

So it's still a mystery but I would still like fnm to just print out where it tried to create a symlink so fixing it would be easier.

**Comment by Schniz** [comment]
the `aliases` dir don't get recreated automatically. `FNM_DIR` works: try `FNM_DIR=/tmp/my-test fnm install 16` and then `ls /tmp/my-test`.

The symlinks, however, are not a part of `FNM_DIR`, but they use the global cache directory now. #656 should make it easier to know what symlinked directory failed.

**Comment by Schniz** [comment]
thanks for the issue! We need to remove as much `.unwrap` and `.expect` as we can from our code 🤓
