### ISSUE TITLE
PowerShell bug & enhancement

### ISSUE THREAD

**Issue by citreae535** [Schniz/fnm#664]
Bug: On Windows PowerShell 5.1 (Default version on Windows 10/11), after setting up with `fnm env --use-on-cd | Out-String | Invoke-Expression`, PowerShell will complain with the following error message when using `cd` without any argument
```
Set-Location : Cannot process argument because the value of argument "path" is null. Change the value of argument
"path" to a non-null value.
```
Enhancement: I would like to set up fnm manually instead of automatically every time I open a new session.  I tried adding this function to my profile and calling it on demand. But this fails because fnm does not explicitly operate in global scope
```PowerShell
function usefnm {
  fnm env --use-on-cd | Out-String | Invoke-Expression
}
```

Proposed solution to both: change the following code https://github.com/Schniz/fnm/blob/c85ff97f1404b0042f7378acb0ad67b3fd607189/src/shell/powershell.rs#L39-L44
to
```PowerShell
function global:Set-FnmOnLoad {{ {autoload_hook} }} 
function global:Set-LocationWithFnm {{ param($path); if ($path -eq $null) {{Set-Location}} else {{Set-Location $path}}; Set-FnmOnLoad }}
Set-Alias -Scope global cd_with_fnm Set-LocationWithFnm
Set-Alias -Option AllScope -Scope global cd Set-LocationWithFnm
Set-FnmOnLoad
```
This works on both PowerShell 5.1 and 7.2

**Comment by Schniz** [comment]
Would you consider doing that in a PR? I don’t have a windows machine and it would be extremely helpful to know if tests pass.
