### ISSUE TITLE
is it safe to delete `/var/folders/ft/.../T/fnm_multishells` folder?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [Schniz/fnm#665]
Hello team,

is it safe to delete `/var/folders/ft/.../T/fnm_multishells` folder?

I'm not sure why it has so many here, but i only have two version installed. All previous version deleted via `fnm uninstall`
```
❯ fnm ls
* v16.14.0 default
* v17.0.1
* system
```

<img width="1601" alt="image" src="https://user-images.githubusercontent.com/33362998/153628147-3f2f8655-dbd2-4d2a-830f-8d46af1baf05.png">

**Comment by Schniz** [comment]
Yes. These are the symlinks for every shell session. Deleting them might cause Node to stop working but if you restart the shell session they should work again. 
it’s in a temp directory because it is safe to delete on reboot
