### ISSUE TITLE
feature request: provide a deactivate command

### ISSUE THREAD

**Issue by bjmgeek** [Schniz/fnm#670]
Similar to the `nvm deactivate` command, please provide a `fnm deactivate` command to remove PATH entries and other environment variables.

thanks

**Comment by Schniz** [comment]
`fnm use system` will bypass fnm

**Comment by ljharb** [comment]
`nvm deactivate` is basically `nvm use system`, and then it removes `nvm` from the shell (because `nvm` is sourced into the shell). "deactivate" probably doesn't make much sense for a binary.

**Comment by bjmgeek** [comment]
ok, thanks!
