### ISSUE TITLE
Weird completion behaviour on PowerShell

### ISSUE THREAD

**Issue by zeemanz** [Schniz/fnm#672]
Recently, I read the doc and found that I can make fnm able to complete command in PowerShell, then I tried it immediatly.
But the completion behaviour is so weird, I even don't know if it is or not a bug.
#### For examples:
1. When I just enter the `fnm ` and press `ctrl` + `space`, it shows all available commands correctly.
2. When I enter the `fnm in` and press `tab`, it will do nothing. (I expect it will just complete the command to `fnm install`, because there is only one command start with `in`).
3. But! When I enter the `fnm install --l` and press `tab`, it just work again!
#### Here is a screen record:
![screen_record](https://user-images.githubusercontent.com/57309261/154092981-1f4be916-e32d-411f-a761-ddd28be24480.gif)

**Comment by Schniz** [comment]
haha woah. I think this is out of fnm's scope as we're using https://docs.rs/clap. I guess you can open a bug there if you're interested 🙏 completions is total magic that's abstracted away in `clap` 😁 

I must say that PowerShell and new Windows looks 💯 💯 💯

**Comment by zeemanz** [comment]
Well, it's seems like a bug in clap_completion, they fixed it in the latest version.
I tried to complie fnm from latest source code, it's work fine now.
Waiting the new version of fnm. 😊
