### ISSUE TITLE
fnm can't download/extract binary.

### ISSUE THREAD

**Issue by gregersn** [Schniz/fnm#700]
```
% fnm install 15.9.0
Installing Node v15.9.0 (x64)

error: Can't download the requested binary: Can't extract the file: failed to unpack `/Users/gregersn/.fnm/node-versions/.downloads/.tmpNtWUNT/node-v15.9.0-darwin-x64/lib/node_modules/npm/changelogs/CHANGELOG-2.md`
```

MacOS 12.3
fnm version 1.31.0

```
% fnm env
export PATH="/Users/gregersn/Library/Caches/fnm_multishells/4191_1647625917675/bin":$PATH
export FNM_MULTISHELL_PATH="/Users/gregersn/Library/Caches/fnm_multishells/4191_1647625917675"
export FNM_VERSION_FILE_STRATEGY="local"
export FNM_DIR="/Users/gregersn/.fnm"
export FNM_LOGLEVEL="info"
export FNM_NODE_DIST_MIRROR="https://nodejs.org/dist"
export FNM_ARCH="x64"
```

Have tried installing binary directly downloaded, and with fnm install through brew. 

If I try to run the install command multiple times, the output differs in that it claims different files can't be extracted.

**Comment by Schniz** [comment]
can't reproduce locally :(
please add a failing test :pray:

**Comment by gregersn** [comment]
I would if I could. That is as far as I get. 
I don't know how I can add a failing test to it other than to observe that it fails when I try to install. 
Is there any way I can get any debug output that tells me what is happening and what it is failing at? 
It says it both can't download, and can't extract. Which is it? And why can it not extract it? More debug output could be helpful.

**Comment by gregersn** [comment]
I will elaborate a bit.

I have fnm on three mac minis, which are all setup more or less the same, as CI runners. 

First fnm started failing with this error on two of the machines, but still keeps working on the third.
We suspected that it might have to do with an upgrade to MacOS 12.3, but other machines running that version still has working fnm. 

One of the machines has been formatted, and reinstalled, in an effort to see if that would help, but we still get the same error message when trying to install any version of Node with fnm. 

The one failing machine is not put back into the build cluster yet, and is available for further testing, but I do not know how to proceed at the moment. 

I have checked out the source, and managed to build fnm locally on another machine, so if you have any suggestions on things I could try to figure out this issue (I have not programmed in Rust before), it would be most appreciated. 

Would it be possible maybe to add a check to see what is failing when it tries to download and/or unpack, and what actually fails?

**Comment by gregersn** [comment]
And after further investigation it looks like there is an issue with SSL. 
I tried downloading the file manually with curl and safari, on the machine that has issues,  and I get an error like: 
`curl: (56) LibreSSL SSL_read: error:06FFF064:digital envelope routines:CRYPTO_internal:bad decrypt, errno 0`

Safari says that some SSL error occured, I can't read the whole error message. But if I keep hitting "resume" in safari, on the download, the file seems to get through. 

This does not seem like it is a problem with fnm, but maybe it would be possible to get some more error checking/output in place?

**Comment by gregersn** [comment]
The issue was clearly and fully on our side, and so I am closing it. 
Though I would say it would have probably been clearer if the error message could differentiate between an extraction issue and a download issue, as the latter was the case here. 

Thank you for your time. :)

**Comment by Jintus** [comment]
Please @gregersn what was the issue ? I run into the same probleme on my side

**Comment by gregersn** [comment]
@Jintus It's been a while, so I had to search old slack discussions at the office to be reminded. But there were issues with the network setup. From what I can remember it was that the Macs did not handle 10GB connections very well.
I believe this was relevant
https://forums.macrumors.com/threads/2018-mac-mini-has-ethernet-port-issue.2284973/

**Comment by bettiolo** [comment]
Same issue today:

```
❯ fnm install 20
Installing Node v20.11.1 (arm64)
error: Can't download the requested binary: Can't extract the file: failed to unpack `/Users/mak/Library/Application Support/fnm/node-versions/.downloads/.tmpevU5av/node-v20.11.1-darwin-arm64/bin/node`
```

**Comment by ehtishamsajjad** [comment]
@bettiolo I deleted `/Library/Application Support/fnm/node-versions/.downloads/` and installed it again.
