### ISSUE TITLE
can’t infer shell in Nova editor

### ISSUE THREAD

**Issue by drwpow** [Schniz/fnm#706]
On macOS, using zsh (and oh-my-zsh). fnm works just great in Mac Terminal, iTerm 2, and even VS Code’s terminal.

However, when I’m using [Nova](https://nova.app/)’s integrated terminal, I see the following error from `fnm env`:

```
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
* fish
* powershell
```

The weird part is that Nova’s terminal uses the standard system’s terminal, so it loads zsh and all my settings, and visibly seems to operate the same as any other terminal. `fnm env` is also the only command that seems to have an issue; every other path seems to work as expected (also note that `fnm` works just fine, but `fnm env` fails and as a result, there’s no `node` command only within Nova).

I see that fnm runs `ps -o ppid,comm` to infer the shell. And Nova prints out the same result as any other terminal:

```
PPID COMM
1586 -l
1722 -zsh
```

There might be some aliasing going on in the process that’s confusing fnm? I know that Nova isn’t a popular IDE, and I’d be happy to debug this further and submit a PR; just not really sure how to diagnose the issue further! Would be happy for any assistance.

**Comment by skilar** [comment]
Hey @drwpow! I had this issue back in #363, so you might have a look there if you haven't already resolved this.

**Comment by Schniz** [comment]
I’m really considering deprecating shell inference or showing a warning all the times. This is too error prone and gives so little

**Comment by drwpow** [comment]
> Hey @drwpow! I had this issue back in #363, so you might have a look there if you haven't already resolved this.

Ah thank you! Yes appending `--shell=zsh` fixed the error for me. I’ll close this issue.
