### ISSUE TITLE
Command not found for globally installed cli commands

### ISSUE THREAD

**Issue by theArianit** [Schniz/fnm#729]
I've installed fnm and with it the latest node version (18.0.0). I then installed a global npm package/cli. But when I want to initialize a project with the cli I am getting the "command not found" error.
How can I deal with this?

**Comment by Clemzd** [comment]
use npx jhipster

**Comment by VinceFanZ** [comment]
I have the same problem。NPM global packages can not be shared with different versions of node

**Comment by Schniz** [comment]
This is a feature, not a bug. This is expected due to how global npm packages are installed.
