### ISSUE TITLE
Feature requests / wishlist

### ISSUE THREAD

**Issue by zanettin** [Schniz/fnm#73]
thanks for the great version manager first of all!
just a list of features i'd like to have in an upcoming release 😄 

## features
- `fnm uninstall <version>`
- `fnm default <version>` to set a default version
- ~~auto select right node version if `.nvmrc` `.node-version` file exists~~ (sry it's already in progress https://github.com/Schniz/fnm/pull/68 👀 )

thanks again 😄

**Comment by Schniz** [comment]
Hey @zanettin! sorry for not being responsive, I was on vacation.

Very valid requests! I'd be happy to receive PRs for that - both should be good first issues.

`fnm default` is available using `fnm alias VERSION default`, but we can also have this as an alias to the `alias` command

**Comment by Schniz** [comment]
I'd accept PRs for that, shouldn't be hard to implement (actually reuse the whole executable/Alias module) 😄
