### ISSUE TITLE
on windows I can`t use fnm in git !

### ISSUE THREAD

**Issue by JohyC** [Schniz/fnm#732]
I created Microsoft.PowerShell_profile.ps1 and add
`[Environment]::SetEnvironmentVariable('FNM_DIR','C:\Application\Languages\fnm');
fnm env --use-on-cd | Out-String | Invoke-Expression`
In PowerShell working is good!
But i cant`t use in git !!!
![image](https://user-images.githubusercontent.com/38210128/166854667-b4d55bdb-ff05-4a13-aa1b-8d1e1d8c3c2f.png)

I need someone help me!😢😫😫

**Comment by citreae535** [comment]
You are using Git Bash, not PowerShell. Please see [how to set up fnm in bash](https://github.com/Schniz/fnm#bash)

**Comment by JohyC** [comment]
> You are using Git Bash, not PowerShell. Please see [how to set up fnm in bash](https://github.com/Schniz/fnm#bash)

oh! oh! my god! i`m so stupid. I got it.thanks man!!!

**Comment by JohyC** [comment]
> You are using Git Bash, not PowerShell. Please see [how to set up fnm in bash](https://github.com/Schniz/fnm#bash)

I still can't get fnm to work in git!
I need some help!
![image](https://user-images.githubusercontent.com/38210128/169201348-477a1a6e-9378-45e3-92a9-b2a101b8488b.png)

**Comment by JohyC** [comment]
I get a answer in #390
