### ISSUE TITLE
1.6 killed error

### ISSUE THREAD

**Issue by ashanren** [Schniz/fnm#74]
Hello. I'm Working on centos 6 atm. 1.5 works fine but when i upgraded to 1.6 or 1.6.1 i get a `Killed` Error when i try to use any command. 1.6.1 also works on my ubuntu setup at home so i'm guessing this is a centos specific issue.

**Comment by Schniz** [comment]
Hey, sorry for not being responsive, I was on vacation.
Can you give a screenshot that shows the actual error?

**Comment by ashanren** [comment]
Thats fine i was also busy all weekend. I've tried this as both a root user and a regular user and neither has worked. The screenshot is my attempt as a root user.

![fnm_error](https://user-images.githubusercontent.com/15707010/53751803-1bcf9800-3e7b-11e9-9b9b-62370ebf871d.png)

**Comment by Schniz** [comment]
It is very weird. I tried to reproduce it on Docker and it didn't work. [Heres a Asciinema screencast of this](https://asciinema.org/a/Y8lTDnYPsvkO4bUuKN6yBKVE2). This is Centos 7 (I guess) but I also tried `centos:6`. I'll try running Centos 6 in a VM so we'll be able to verify why is it happening. It is very weird indeed!

**Comment by ashanren** [comment]
I just finished installing a new instance of centos 6 and i still see the issue. I also tested on a fresh centos 7 instance and everything seems to work fine.

**Comment by Schniz** [comment]
Well, I have successfully installed CentOS 6, and it is still weird. I tried to run `strace fnm`, and this is the tail of the output:

```
syscall_318(0x7ffd45389de0, 0x28, 0, 0, 0, 0) = -1 (errno 38)
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1 RT_2], [], 8) = 0
tkill(18753, SIGKILL <unfinished ...>
+++ killed by SIGKILL +++
Killed
```

I suspect on `errno 38`!

I also tried to compile it on the VM, but it needs a newer glibc, which needs to be compiled by hand, which I'm not sure that will even work. It asked for `glibc >= 2.14`, so I compiled `2.14`. Now it wants `>2.15`. You can't satisfy the machine!

**Comment by Schniz** [comment]
It looks like a syscall that isn't implemented on CentOS 6. CentOS 6 EOL is 2020 - which is next year. Unfortunately I can't see how it can be fixed, and any of you which have servers running CentOS 6, I really hope you are planning to upgrade your kernel (so it'd add the syscall) or just upgrade to CentOS 7, where `fnm` works fine.

That being said, I'd accept PRs that fix this issue.
Sorry about that @ashanren! ❤️
