### ISSUE TITLE
arch confused on fnm use/install

### ISSUE THREAD

**Issue by fantasywind** [Schniz/fnm#742]
The fnm will install node binary in home folder .fnm, for each version with its name. But in M1 Mac, x64 node binary also work perfectly with rosetta 2.

With some library (like node-oracledb) only support x64 arch node binary. I need switch x64 and arm64 in same node version.

For now:
Node's binary arch based on installed --arch option or FNM_ARCH env, for example, my M1 mac install 18.2.0 in arm64 arch and 18.1.0 in x64 arch.

<img width="184" alt="Screen Shot 2022-05-27 at 00 58 56" src="https://user-images.githubusercontent.com/1902526/170537488-a0428b3a-3657-466f-94c7-6267416fd5d6.png">

If I install 18.1 in arm64 arch with --arch, fnm install said the version is installed with correct arch message, but it's not work correctly.

<img width="625" alt="Screen Shot 2022-05-27 at 01 03 54" src="https://user-images.githubusercontent.com/1902526/170538499-4b514b1f-2b4c-4864-a239-c6b9a0111d38.png">

Feature Request:

The fnm should install version to path with name including version and arch for arch switch 🥺

```shell
fnm install --arch x64 18.1
# Install to ~/.fnm/node-versions/x64/v18.1.0

fnm install --arch arm64 18.1
# Install to ~/.fnm/node-versions/arm64/v18.1.0
```

**Comment by jurajpiar** [comment]
Observed same behaviour with v14 and v16:
<img width="307" alt="Screenshot 2022-07-21 at 10 07 26 am" src="https://user-images.githubusercontent.com/36888576/180175917-3b996dd4-2e2e-4a06-b816-205e28b5b741.png">

**Comment by Schniz** [comment]
@jurajpiar this is not confusion, we install a rosetta version because Node.js does not provide a prebuilt ARM binaries for Mac for 14.x: https://nodejs.org/dist/v14.20.0/

**Comment by Schniz** [comment]
for the original thread: I don't understand why people will use x64 and run through Rosetta when they can install an ARM version?

**Comment by jurajpiar** [comment]
Ah right so much for LTS

**Comment by Schniz** [comment]
I'm closing this as this is a known issue. Sorry that this is how it resolves @jurajpiar, hope that we won't have any issues like this in the future :pray:
