### ISSUE TITLE
can't find .fnm folder

### ISSUE THREAD

**Issue by clark-cui** [Schniz/fnm#751]
My fnm worked well.But for some reasons, I have to do some changes in .fnm folder.But I can't find it in my  home directory.

It is M1 MacbookPro using macos monterey v12.4.

**Comment by Schniz** [comment]
It's not in `~/.fnm` anymore, although I miss it there too. The correct directory will always be present as the `$FNM_DIR` env var, so you can `cd "$FNM_DIR"` 😃 

please let me know if it works out for you 🙏
