### ISSUE TITLE
Download failed in Ubuntu 20.04

### ISSUE THREAD

**Issue by IMPranshu** [Schniz/fnm#772]
![image](https://user-images.githubusercontent.com/43396684/177704605-39241be8-3544-43e9-a074-98f6ee9795c3.png)
 I am getting the above error while following the installation instruction.

**Comment by Schniz** [comment]
can't reproduce

This is for M1 (arm64 docker image):

```sh-session
✡ docker run --rm -it ubuntu
root@15153b914a34:/# (apt-get update && apt-get install -y unzip curl) &> /dev/null
root@15153b914a34:/# curl -fsSL https://fnm.vercel.app/install | bash
Checking dependencies for the installation script...
Checking availability of curl... OK!
Checking availability of unzip... OK!
Downloading https://github.com/Schniz/fnm/releases/latest/download/fnm-arm64.zip...
######################################################################## 100.0%
Installing for Bash. Appending the following to /root/.bashrc:

  # fnm
  export PATH=/root/.fnm:$PATH
  eval "`fnm env`"

In order to apply the changes, open a new terminal or run the following command:

  source /root/.bashrc
```

This is for linux/amd64 docker image:

```sh-session
✡ docker run --rm -it --platform=linux/amd64 ubuntu
root@1e11e7fb6ba6:/# (apt-get update && apt-get install -y unzip curl) &> /dev/null
root@1e11e7fb6ba6:/# curl -fsSL https://fnm.vercel.app/install | bash
Checking dependencies for the installation script...
Checking availability of curl... OK!
Checking availability of unzip... OK!
Downloading https://github.com/Schniz/fnm/releases/latest/download/fnm-linux.zip...
######################################################################## 100.0%
Installing for Bash. Appending the following to /root/.bashrc:

  # fnm
  export PATH=/root/.fnm:$PATH
  eval "`fnm env`"

In order to apply the changes, open a new terminal or run the following command:

  source /root/.bashrc
root@1e11e7fb6ba6:/# source /root/.bashrc
root@1e11e7fb6ba6:/# fnm --version
fnm 1.31.1
```

**Comment by brianwachira** [comment]
![image](https://user-images.githubusercontent.com/28436092/197701685-b94f3f65-6246-4722-b839-3b7665b8ef6e.png)


> 

![image](https://user-images.githubusercontent.com/28436092/197701713-d26438a8-bb98-4705-a352-15271ef34226.png)
Getting the same error too. @Schniz please help

**Comment by Schniz** [comment]
I can't reproduce it. Please try to follow the installation script and running it line by line: it shouldn't be very hard. It downloads the latest zip and unzips it into a directory

**Comment by alexeyten** [comment]
@brianwachira try
```bash
curl -S -L -o /dev/null https://github.com/Schniz/fnm/releases/latest/download/fnm-linux.zip
```
and see if there is any errors.

**Comment by brianwachira** [comment]
> @brianwachira try
> 
> ```shell
> curl -S -L -o /dev/null https://github.com/Schniz/fnm/releases/latest/download/fnm-linux.zip
> ```
> 
> and see if there is any errors.

Thanks!
I am not getting errors, however how do I install fnm after running that command?

**Comment by fubd** [comment]
same question . download failed in ubuntu and debian.

**Comment by stsiarzhanau** [comment]
I've recently have encountered the same problem on fresh Ubuntu 22.04. Was solved by changing curl version and/or the way of installation.

According to the README we have to run `curl -fsSL https://fnm.vercel.app/install | bash` at first...

As curl was not installed initially I've checked it's version and installed v8.1.2 with snap as was suggested.

~$ curl --version
Command 'curl' not found, but can be installed with:
sudo snap install curl  # version 8.1.2, or
sudo apt  install curl  # version 7.81.0-1ubuntu1.13
See 'snap info curl' for additional versions.
~$ sudo snap install curl
curl 8.1.2 from Wouter van Bommel (woutervb) installed

When running automatic installation script the temp folder was created but was not populated with downloaded file for some reason:

```
    if ! curl --progress-bar --fail -L "$URL" -o "$DOWNLOAD_DIR/$FILENAME.zip"; then
      echo "Download failed.  Check that the release/filename are correct."
      exit 1
    fi

   # there's no file is in the DOWNLOAD_DIR on this step
    unzip -q "$DOWNLOAD_DIR/$FILENAME.zip" -d "$DOWNLOAD_DIR"
```

Then I removed curl by running `~$ sudo snap remove curl` and reinstalled it by running `~$ sudo apt  install curl`

With curl 7.81.0 (x86_64-pc-linux-gnu) I've successfully installed fnm.

**Comment by ben-xD** [comment]
> huh? curl does not come preinstalled on ubuntu anymore?

I just installed ubuntu 22.04.3 LTS on WSL2 on windows, and curl was already installed and up to date. I just needed to install unzip as documented, `sudo apt install -y unzip`.

**Comment by S4GU4R0** [comment]
> Then I removed curl by running `~$ sudo snap remove curl` and reinstalled it by running `~$ sudo apt install curl`

Thank you, this fixed it for me.
