### ISSUE TITLE
fnm_multishells Cache Folder

### ISSUE THREAD

**Issue by joepetrillo** [Schniz/fnm#774]
Hi, I am curious what the purpose of the `fnm_multishells` folder is and if it is safe for me to delete all of the aliases inside of it?

I really mind leaving them if necessary but I noticed I have A LOT of them. Is there a way to disable a new one being made each time I open my terminal? Sorry if this question does not make much sense, I was just poking around at how fnm worked.

Thanks!

**Comment by Schniz** [comment]
Good question and makes total sense. You can remove the multishells which are basically symlinks but keep in mind that it might make your currently running shells stop finding Node. That’s all good as you can restart the shell session or evaluate `fnm env` again. Nothing important is stored there. In fact, previously it was stored in the temp directory but on latest macOS versions the temp directory got cleaned on random times so we moved them to a different location. Hope that helps!
