### ISSUE TITLE
Could install on Multipass

### ISSUE THREAD

**Issue by behnammodi** [Schniz/fnm#787]
I'm using Multipass, due install `fnm` I got this error:

<img width="746" alt="Screenshot 2022-07-26 at 21 41 56" src="https://user-images.githubusercontent.com/1549069/181098024-d1d0ead9-bc1d-4449-9b8a-435ecdc8e3c1.png">

**Comment by Schniz** [comment]
but seems like this is a [rust issue](https://stackoverflow.com/questions/52445961/how-do-i-fix-the-rust-error-linker-cc-not-found-for-debian-on-windows-10)

You might need to install the build tools for Ubuntu if you want to build fnm locally
