### ISSUE TITLE
FNM use string appends to file when using Prettier to format files in NeoVim

### ISSUE THREAD

**Issue by henrychea** [Schniz/fnm#788]
I have `.nvmrc` file in my repo and every time I format a file with [Prettier-Vim](https://github.com/prettier/vim-prettier) I get the FNM use string appended to the top of my file.

Here's what happens:

https://user-images.githubusercontent.com/40254517/181575316-928ab666-e08f-4a95-a56d-873bb449c6a5.mov

My setup:
M1 Macbook Pro (monterey 12.4 (21F79))
Fish Shell v3.5.1 (No Tide plugin, as I have seen other users have issues with it)
NVIM v0.8.0-dev+493-ga0a815ec5
iTerm2 Build 3.4.16

FNM Config in `~/.config/fish/config.fish`
```
.....
# FNM 
fnm env --shell fish --use-on-cd | source
fnm completions --shell fish | source
.....
```

**Comment by Schniz** [comment]
can it be that `prettier-vim` is running an entire fish shell to execute prettier? I don't think you need to do that as it's slower than calling `npx prettier`.

For testing purposes, can you add `echo "test"` to your `~/.config/fish/config.fish` file?

if the "test" message is shown on your prettified files too, then it's an issue with prettier-vim. but it's a nice thing to check.

**Comment by henrychea** [comment]
Thanks for pointing that out! I can confirm that it's an issue with Vim-Prettier and not FNM

**Comment by thatanjan** [comment]
@Schniz I am also facing the same problem. If I uninstall fnm then I don't face the problem. I use `EslinFixAll` command from Eslint lsp to format the code.
How can I fix this?
