### ISSUE TITLE
add `fnm install --latest` to  Install latest version

### ISSUE THREAD

**Issue by lontten** [Schniz/fnm#797]

**Comment by Schniz** [comment]
I think this was asked before. so might be a duplicate.
anyway, in the meantime you can use `fnm install --lts`.

**Comment by ajitzero** [comment]
I think `--latest` (if added) shouldn't be same as `--lts`. Instead I suggest it should install the "current" version, i.e., the next "to-be-stable" version. Now, that would point to `18.8.0`

**Comment by satvikpendem** [comment]
Agreed, I want to install the latest version that's on the Nodejs website, not the latest LTS.

**Comment by ohana54** [comment]
@Schniz do you agree to the feature? I'd love to try and implement it

**Comment by bnb** [comment]
I would really like to see this @Schniz. Just got a friend onboarded and they were asking how to do this, and it's something I tried to do when I started as well.

**Comment by Schniz** [comment]
merged in #859, will be released soon! <picture data-single-emoji=":pray_parrot:" title=":pray_parrot:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..oglO8mo5T9Yg4S7e.bEzemEawvo79TxjDrqrRALHadGyFOyzMEebvjpCyBC_gm0YCC3RXSdaGBTxPvP3yB7HhVVobgjm6pVtefX6m7pfXvXJmEd9keNXuvm0SPaSayNoQsSowty1jlV0.2075YAOwPAUqPGKv0vIzuQ" alt=":pray_parrot:" align="absmiddle"></picture> 

Thanks @nzhl <picture data-single-emoji=":blob_thanks:" title=":blob_thanks:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..MVq-Ea4GKKKgEXz3.kBLA3XBz59UScW84ckfFNZejp9cbck6t7npRxVNfAEYSYBtmybGQqrOjw-pm54YNK3pgGFCyfIQaY4r0UZrLZRNz29fMnxxNkz5tqJhWV1us_Fvsm8Zxrn4-yiHy.iN3vt-IUsWTPShFIkbav_w" alt=":blob_thanks:" align="absmiddle"></picture>
