### ISSUE TITLE
What about a Logo?

### ISSUE THREAD

**Issue by wildcard** [Schniz/fnm#798]

**Comment by Schniz** [comment]
heeeeey Kobilicious

we have this (the stickers that I printed for Reason Conf 2019):

![:rocket:](https://user-images.githubusercontent.com/2054772/184814547-1f6deb29-6c2c-4d78-b678-984c4d0e0332.png)

if you have a better idea, let me know 😁

**Comment by MattIPv4** [comment]
👋 @Schniz sorry for posting on such an old issue -- would you have to have a vector (SVG) for that?

**Comment by Schniz** [comment]
Didn’t see it. Let me see in a few if I have the figma document!

**Comment by MattIPv4** [comment]
@Schniz just checking in to see if you'd managed to find the original?
