### ISSUE TITLE
yarn version is `3.2.2` although one installed in fnm_multishells is 1.22.19 on macOS

### ISSUE THREAD

**Issue by trivikr** [Schniz/fnm#799]
## Describe the bug
yarn version is `3.2.2` although one installed in fnm_multishells 1.22.19

This could be an issue with yarn. Creating one with fnm to start with

## Steps to reproduce
```console
$ fnm --version
zsh: command not found: fnm

$ brew install fnm
...

$ eval "$(fnm env --use-on-cd)"

$ fnm --version
fnm 1.31.1

$ yarn --version
3.2.2

$ which yarn | xargs ls -l
lrwxr-xr-x  1 trivikr  staff  36 Aug 15 15:26 /Users/trivikr/Library/Caches/fnm_multishells/55354_1660605158908/bin/yarn -> ../lib/node_modules/yarn/bin/yarn.js

$ jq '.version' /Users/trivikr/Library/Caches/fnm_multishells/55354_1660605158908/lib/node_modules/yarn/package.json 
"1.22.19"
```

#### Observed behavior
The `yarn --version` is displayed as `3.2.2`

#### Expected behavior
The `yarn --version` should be `1.22.19`

## Additional context
```console
$ sw_vers 
ProductName:	macOS
ProductVersion:	12.5
BuildVersion:	21G72
```

**Comment by trivikr** [comment]
This issue is also reproducible with nvm

```console
$ nvm --version
zsh: command not found: nvm

$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
...

$ export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

$ nvm --version
0.39.1

$ yarn --version
zsh: command not found: yarn

$ nvm install 16
...
Now using node v16.16.0 (npm v8.11.0)
Creating default alias: default -> 16 (-> v16.16.0)

$ npm install -g yarn

$ yarn --version
3.2.2

$ which yarn | xargs ls -l
lrwxr-xr-x  1 trivikr  staff  36 Aug 15 16:24 /Users/trivikr/.nvm/versions/node/v16.16.0/bin/yarn -> ../lib/node_modules/yarn/bin/yarn.js

$ jq '.version' /Users/trivikr/.nvm/versions/node/v16.16.0/lib/node_modules/yarn/package.json 
"1.22.19"
```

**Comment by alexeyten** [comment]
Where do you run these commands? Yarn is looking for it's binary in .yarn/ folder. 

https://yarnpkg.com/cli/set/version

**Comment by trivikr** [comment]
> Where do you run these commands?

I run these commands from home folder.

Ideally, I'm expecting yarn to set version 1.x and switch to higher versions only if they're explicitly defined in `packageManager` field or `.yarn` folder per repository.

**Comment by alexeyten** [comment]
Anyway, I think it's something that is configured by yarn and has nothing to do with fnm and nvm.

Check `~/.yarnrc` and `~/.yarnrc.yml` files.

**Comment by trivikr** [comment]
> Anyway, I think it's something that is configured by yarn and has nothing to do with fnm and nvm.

Yup, I'd created a bug report on yarn repo at https://github.com/yarnpkg/berry/issues/4752

Closing this issue.
