### ISSUE TITLE
Add support for .node-version files

### ISSUE THREAD

**Issue by jantimon** [Schniz/fnm#8]
Most version managers support the `.node-version` format:

Tool Name | Config File | Plattform | Notes
-- | -- | -- | --
[nvs](https://github.com/jasongin/nvs) | .node-version | Mac / Linux / Windows |  
[nvm](https://github.com/creationix/nvm) | .nvmrc | Mac / Linux |
[nodenv](https://github.com/nodenv/nodenv) | .node-version | Mac / Linux |  
[nodist](https://github.com/nullivex/nodist) | .node-version | Windows |  
[avn](https://github.com/wbyoung/avn) | .node-version | Mac / Linux |  
[n](https://github.com/tj/n) |   | Mac / Linux | Does not seem to have a config file option

Could you please also add support?

**Comment by ljharb** [comment]
I’d suggest not using it; it’s not actually a standard, and in fact it’s current use means that the Node Version Management Group will (when it only day creates a standard) be defining a different file name and format.

**Comment by ljharb** [comment]
Right - I’m saying that it’s better to be less compatible, so as to help make that format less commonly used, because it will one day be very harmful for the ecosystem to have that file as the commonly used one.

**Comment by jantimon** [comment]
So if I understand you correctly we should also drop support for `.nvmrc` to help the future eco system?

**Comment by ljharb** [comment]
If you like, but `.nvmrc` has "nvm" in the name, so it's clearly not a cross-ecosystem standard, nor will it ever be.

Whatever filename we go with will be something new that is not tied to any specific version manager.

**Comment by jantimon** [comment]
4 of 6 node version managers (which work for mac, windows and linux) support `.node-version` so for me that’s already a little bit like a standard and I can’t see the risk you try to describe.

would love to know what @schniz thinks about this

**Comment by ljharb** [comment]
The instant the node version management working group declares a standard format, it won't be ¯\\\_(ツ)_/¯ (and we won't be declaring ".node-version")

**Comment by Schniz** [comment]
I’m not familiar with `.node-version` as I have only used nvm. How popular is it? I’m pretty sure it’s not hard to implement, but every file type (or file name) will make it slower. Maybe it’s for the best though

**Comment by jantimon** [comment]
Cool :)

There are already [45.000 Github repositories using a `.node-version` file](https://github.com/search?q=filename%3A%22.node-version%22)

The content is very simple but in the early days there were two formats:

 - v0.0.0
 - 0.0.0

Nowadays all version managers seem to skip the `v` in front of the version but I guess it would be nice not to bail if one exists.

[nodenv has a nice description how it picks up the version and also notes how they handle `.node-version`](https://github.com/nodenv/nodenv#choosing-the-node-version)

[nvs just says that the `.node-version` file is looked up recursively in the file structure](https://github.com/jasongin/nvs#automatic-switching-per-directory)

[nodist uses a similar description like nvs](https://github.com/nullivex/nodist#scope-precedence)

[avn also notes that the `.node-version` is using the semver format](https://github.com/wbyoung/avn#install)

**Comment by Schniz** [comment]
This is exactly how I implemented the `.nvmrc` file (I add the `v` prefix when there isn't one). I'd accept PRs that implement that - it's a good first issue in my opinion 😸 

This can be by changing the `Nvmrc` module to a module with a new name that checks for every known file we support (and that'll be two files for now 😄)

If someone needs any help with implementing it, [reach me out with a DM](https://twitter.com/galstar) or an Email or something. I'd love to help!

The only thing worth noting is that we'll need to have some kind of priority.

**Comment by brandom** [comment]
@Schniz Just dropping in to say thanks and great work! A new tab in Hyper went from ..... to . as soon as I installed fnm and switched off nvm.

My two cents on the above discussion is that it appears [the WG](https://github.com/nodejs/version-management) hasn't met in two years and the [initial proposal](https://github.com/nodejs/version-management/blob/master/initial_proposal.md), IMHO, doesn't make a compelling argument for creating what amounts to yet-another-version-manager with an *official* stamp.

Adding support for a de facto standard cross-vm config like `.node-version` is "the right thing" to do, just as you currently support the config file for the de facto standard version manager.

I would love to show my gratitude with a PR but I am short on time at the moment, I will check back this weekend to see if this or another GFI is open.
