### ISSUE TITLE
`fnm env` output not evaluated at Zsh startup automatically but can be evaluated manually

### ISSUE THREAD

**Issue by paanvaannd** [Schniz/fnm#803]
# System information

* Hardware: M1 Mac Studio, 32 GB RAM
* OS: macOS Monterey (12.5.1)
* Shell: Zsh (5.8.1)
* Installation method: Homebrew (3.5.10)
* Program version: FNM 1.31.1

# Issue

After installation (re-installation did not resolve) via `brew update && brew install fnm`, upon every launch of `zsh`, the following message is shown:

> /Users/paanvaannd/.zshrc:131: command not found: fnm

The line in question within my `.zshrc` is: `eval "$(fnm env --use-on-cd)"`

I looked at #640 already which seems similar, but relocating the line in question within `.zshrc` did not resolve the issue. The issue in #640 was likely, as mentioned there, due to the alias that may have overwritten a built-in keyword. My `.zshrc` does not have any aliases specified, so it wouldn't be that. Furthermore, other `eval` statements (e.g., `eval "$(pyenv init -)"`) work well.

Most of my `.zshrc` is commented out anyways, so I've pasted only the relevant lines below (just an FYI, since that means the line numbers in the IRL file don't match the line numbers here necessarily):

```zsh
# PL10K
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Zsh & OMZ
export ZSH="$HOME/.oh-my-zsh"
export PROMPT_EOL_MARK=''
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(zsh-autosuggestions F-Sy-H) # consider adding "git"
source $ZSH/oh-my-zsh.sh

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# FNM
eval "$(fnm env --use-on-cd)"

# Homebrew
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
```

After Zsh prints the aforementioned message and readies the prompt, I can interact with `fnm` naturally (i.e., it is in my PATH):

```zsh
$ whence fnm
/opt/homebrew/bin/fnm

$ fnm --version
fnm 1.31.1

$ fnm env
export PATH="/Users/pavan/Library/Caches/fnm_multishells/4708_1661392577309/bin":$PATH
export FNM_MULTISHELL_PATH="/Users/pavan/Library/Caches/fnm_multishells/4708_1661392577309"
export FNM_VERSION_FILE_STRATEGY="local"
export FNM_DIR="/Users/pavan/Library/Application Support/fnm"
export FNM_LOGLEVEL="info"
export FNM_NODE_DIST_MIRROR="https://nodejs.org/dist"
export FNM_ARCH="arm64"
rehash

$ fnm use
error: We can't find the necessary environment variables to replace the Node version.
You should setup your shell profile to evaluate `fnm env`, see https://github.com/Schniz/fnm#shell-setup on how to do this
Check out our documentation for more information: https://fnm.vercel.app
```

# Summary

So `fnm env` will output data properly when manually called, it just doesn't get evaluated upon first run. After manually running `$ eval "$(fnm env --use-on-cd)"`, everything works perfectly (so far as I can tell)!

**Comment by paanvaannd** [comment]
Darn! I had a Brain Blast™ but—alas! 'Twas for naught.

Thought this may have been due to Powerlevel10k's "instant prompt" feature but after reconfiguring the prompt to turn the feature off, this issue persists.

Please let me know if there is any more information you need!

**Comment by jridgewell** [comment]
If you're installing via `brew`, you need to have the homebrew's bin directory in your path before you try to eval:

```diff
-# FNM
-eval "$(fnm env --use-on-cd)"

# Homebrew
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"

+# FNM
+val "$(fnm env --use-on-cd)"
```

**Comment by Schniz** [comment]
What @jridgewell  said! Since fnm was installed using homebrew, the binary will be in homebrew’s installed binaries directory. This should fix your issue 🙏

**Comment by paanvaannd** [comment]
Thank you both! That makes sense, and it did fix the issue.
