### ISSUE TITLE
Can't infer shell for mac m1

### ISSUE THREAD

**Issue by TickHeart** [Schniz/fnm#809]
It's strange that it can be used normally before.
But I can't provide more information for it. I'm sorry.

**Comment by Schniz** [comment]
to help out, I'm gonna need to know your shell brand and version, maybe `echo $SHELL`, fnm version, & the error message with `RUST_LOG=fnm=debug fnm env`

if you can't provide more information, I can't really help--and you can fix it by explicitly setting your shell type: `fnm env --shell=zsh`
