### ISSUE TITLE
'fnm use system' does not work

### ISSUE THREAD

**Issue by AyushRawal** [Schniz/fnm#847]
On running `fnm use system` the `FNM_MULTISHELL_PATH` points to `/dev/null/installation` which leads to a broken symlink.

![image](https://user-images.githubusercontent.com/32910415/201664073-4bf342bd-8556-4e36-b7a8-53a3e5112bdd.png)

I think the issue is in this file: https://github.com/Schniz/fnm/blob/b54be01d10d645ae2d2d8a0444cd9aacdddf2de8/src/system_version.rs. I maybe wrong though.

**Comment by Schniz** [comment]
`fnm use system` links `FNM_MUTLISHELL_PATH` to `/dev/null/installation` on purpose. This allows your shell to "skip" resolving with fnm.

It's an ugly trick, but one that works. The symlinks are an implementation detail of fnm.

```
✡ realpath $FNM_MULTISHELL_PATH; realpath $(which node)
/Users/schniz/Library/Application Support/fnm/node-versions/v16.15.1/installation
/Users/schniz/Library/Application Support/fnm/node-versions/v16.15.1/installation/bin/node
✡ fnm use system
Bypassing fnm: using system node
✡ realpath $FNM_MULTISHELL_PATH; realpath $(which node)
realpath: /Users/schniz/Library/Caches/fnm_multishells/66035_1668429372699: Not a directory
/opt/homebrew/Cellar/node/18.11.0/bin/node
```

Can you explain further what is the problem? Are you sure you have a system node?

**Comment by AyushRawal** [comment]
Well it's not working now in zsh now, neither in bash.

![image](https://user-images.githubusercontent.com/32910415/201665806-ff1c7ffd-fa18-4617-b735-3d38248c4ee0.png)

![image](https://user-images.githubusercontent.com/32910415/201666111-ce688b9e-856a-40ff-8711-7e49a9197792.png)

**Comment by Schniz** [comment]
Can it be that your zsh example is having fnm set up twice? something like `bash[with fnm] -> zsh[with fnm]`? this would explain why you are getting the default version when using `fnm use system`. You can see that with `echo $PATH`--if you don't have two fnm initializations, you should see a single `fnm_multishells` path there

**Comment by AyushRawal** [comment]
Yup, that seems to be the case here.

![image](https://user-images.githubusercontent.com/32910415/201669799-a0acb1a4-6965-492c-bb8c-35ac9e74faaf.png)

But, I am not initializing it twice, I think. I have ```eval "`fnm env`"``` once in my `.zshrc`. And I don't have any `.bashrc`.

**Comment by Schniz** [comment]
are you using tmux or anything that might run zsh twice?
or maybe (trying to think about an arch setup), your login shell is zsh and your terminal emulator in the desktop environment is creating the second zsh? <picture data-single-emoji=":eyebrow-man:" title=":eyebrow-man:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..7kYyhQapGnl2dLDo.LVIYskZ6mllOgroRyfnPBwR1Nxb6ohdZnm0P1NrDCZRRSlQ8htaKkTWB1G-FOD4S7qCl-QEzIUO7-_hLSzzP97xt9ZAlzdMWXweaYyjpPoLJAR71fji-rhkCu_a71A.I2m4AY9FGXcj4VfMV81-5A" alt=":eyebrow-man:" align="absmiddle"></picture>

**Comment by AyushRawal** [comment]
Yup, that is indeed the case, I am using zsh as my login shell also.

**Comment by Schniz** [comment]
So one fix might be to re-introduce /usr/bin after the fnm env, like:

```diff
 # ... previous code ...
+export PATH=/usr/bin:$PATH
 eval "$(fnm env)"
```

so you will always "fall back" to /usr/bin

but in that sense, "fnm use system" works because it falls back to the "parent" fnm

**Comment by Schniz** [comment]
another fix if you always use tmux (like me) is to have it like

```sh
if [ -z "$TMUX" ]; then
  eval "$(fnm env)"
fi
```

**Comment by AyushRawal** [comment]
Or, I could move `eval "$(fnm env)"` to `.zshenv`, then it won't be initialized again and again.

**Comment by Schniz** [comment]
yeah totally. however, one of fnm's core features is the ability to have multiple shell instances with different Node.js versions. So each tmux pane might have their own Node.js version, hence the "MUTLISHELL" paths 😁 The idea that fnm is initialized again and again is to create the new symlink per-shell-session

so by using `.zshenv` you will disable this feature and will use a "global" node version

**Comment by Schniz** [comment]
anyway closing this issue 🙏 
thanks for the fruitful discussion

**Comment by AyushRawal** [comment]
> A PR to add a small FAQ with this question/answer as the first FAQ would be appreciated <img alt=":pray_parrot:" width="20" height="auto" src="https://camo.githubusercontent.com/166c9646b9c0cd019d58c82cab64e7699635153db5f4d55106e53913f3f98a2d/68747470733a2f2f73696e676c652d656d6f6a692e76657263656c2e6170702f6170692f656d6f6a692f65794a68624763694f694a6b615849694c434a6c626d4d694f694a424d6a553252304e4e496e302e2e537662714d35386336584d62437542332e785377714552513344504f474a593672596b4173734f4671432d31766264574a747677796745584d6f6555647047386b366a644649636d7a47345471776f346a4369334c2d48507a625844782d6a41793538726e7869412d4b4242684152797075774f335f45646b664f614932695853656e3166633363575a69342e714f64676b732d584e7358394836596d354334664b67">

I will be glad to help 😁.
