### ISSUE TITLE
Add `latest` alias when using `fnm install --latest`

### ISSUE THREAD

**Issue by latipun7** [Schniz/fnm#880]
With this amazing https://github.com/Schniz/fnm/pull/859 PR by @nzhl merged, `fnm` now has this awaited feature. Thank you 🎉

But I noticed that when I install latest node, it doesn't automatically add or change `latest` alias to the installed node version, while `fnm install --lts` will automatically add or change `lts-latest` alias to the installed version.
![image](https://user-images.githubusercontent.com/20012970/206828148-6435f357-a3b3-4258-93df-0078847725bd.png)

**Comment by Schniz** [comment]
let's do it
