### ISSUE TITLE
Add `--lts` flag for `ls-remote`

### ISSUE THREAD

**Issue by chesskuo** [Schniz/fnm#886]
While I list all remote version, I prefer to show LTS version only.

I thought this is more convenient to list what user's want.

Thank you.

**Comment by halshar** [comment]
ahh, I thought the `ls-remote` had `--lts` flag but found nothing in documentation, so came looking here but it's been 1.5 years and no update for this PR :(

**Comment by sdavids** [comment]
[PR](https://github.com/Schniz/fnm/pull/1063) has been merged … so this issue can be closed?

**Comment by chesskuo** [comment]
oh, thank you for your inform.
i would close this issue now.
