### ISSUE TITLE
Install is failing on unzip

### ISSUE THREAD

**Issue by wildcard** [Schniz/fnm#89]
```sh
curl https://raw.githubusercontent.com/Schniz/fnm/master/.ci/install.sh | bash

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3649  100  3649    0     0   6747      0 --:--:-- --:--:-- --:--:--  6757
Checking dependencies for the installation script...
Checking availablity of curl... OK!
Checking availablity of unzip... OK!
Downloading https://github.com/Schniz/fnm/releases/download//fnm-macos.zip...
######################################################################## 100.0%
[/var/folders/4w/6430rhmd1td4p_c564bzpjxmlhrhc3/T/tmp.ATFeAgaY/fnm-macos.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/4w/6430rhmd1td4p_c564bzpjxmlhrhc3/T/tmp.ATFeAgaY/fnm-macos.zip or
        /var/folders/4w/6430rhmd1td4p_c564bzpjxmlhrhc3/T/tmp.ATFeAgaY/fnm-macos.zip.zip, and cannot find /var/folders/4w/6430rhmd1td4p_c564bzpjxmlhrhc3/T/tmp.ATFeAgaY/fnm-macos.zip.ZIP, period.
```

![image](https://user-images.githubusercontent.com/2939405/55090597-13ecc780-50b8-11e9-8103-b6259cb05e6a.png)

**Comment by Schniz** [comment]
Hi and sorry about that. The installation script fails without notifying when GitHub returns an error from their API. It is mostly because of "too many requests" from an API.

That means we should:

* Add a check to the installation script that verifies that the latest version we got from GitHub isn't empty.
* Maybe add a way to install a specific version?
* Publish a Homebrew tap!

**Comment by tchock** [comment]
I also got this message. Is this still an issue currently or is this caused by something else?
Any manual steps I could do to install this (without cloning the repo?)

**Comment by Schniz** [comment]
I should've read [GitHub releases docs](https://help.github.com/en/articles/linking-to-releases). I made a PR that fixes that. Sorry for the inconvenience

**Comment by tchock** [comment]
Works now. Big thanks 👍

**Comment by ashutoshpw** [comment]
The script still fails if `unzip` is not installed in the system. 

Should we install unzip if it is not there? or maybe atleast prompt user that please install `unzip` to continue. 
This happened with me several times the solution is to look into the Source code.
