### ISSUE TITLE
Please add documentation

### ISSUE THREAD

**Issue by whyboris** [Schniz/fnm#9]
Besides reading the code, how can I figure out how to use this tool? 

Please share.

**Comment by rafalolszewski94** [comment]
Animated SVG in readme says a bit, but I agree, it's still not a documentation.

Haven't tried it yet, but I assume (it is CLI package) it has `--help` option.

**Comment by Schniz** [comment]
You’re totally right. I’m AFK right now but would be super happy to get a PR that even just includes the `—help` output in the README
