### ISSUE TITLE
cargo package out-of-date version ???

### ISSUE THREAD

**Issue by huyhoang160593** [Schniz/fnm#907]
like the title said, I mostly update my package though cargo, but when I check the version in cargo https://crates.io/crates/fnm, they are several versions behind :((((

**Comment by Schniz** [comment]
Sorry
I am a bad maintainer
I will publish first thing tomorrow :(

**Comment by huyhoang160593** [comment]
It has been 2 weeks pass, any new from this :(

**Comment by Schniz** [comment]
done
