### ISSUE TITLE
node: Bad CPU type in executable

### ISSUE THREAD

**Issue by matthew-dean** [Schniz/fnm#915]
I'm on a new M1 Mac. Installing Node via `fnm use` (the `.nvmrc` file has "14") seems to install okay, but running any commands results in:

```
env: node: Bad CPU type in executable
```

I couldn't see any issue flagging this yet?

**Comment by Schniz** [comment]
Try to enable Rosetta. There are no prebuilt M1 binaries for nodejs 14

**Comment by Schniz** [comment]
Closing for now. Please report if that don’t work out.

**Comment by conorzhong** [comment]
Enabling Rosetta solved my problem

```sh
/usr/sbin/softwareupdate --install-rosetta --agree-to-license
```
