### ISSUE TITLE
I want you to look at the engine in package.json.

### ISSUE THREAD

**Issue by shossk** [Schniz/fnm#916]
I'm tired of creating .node-version, .nvmrc, etc. depending on the environment...can't we just look at the engine in package.json?

**Comment by Schniz** [comment]
1. @amitdahan had some work on it, but I don't have time to land this: https://github.com/Schniz/fnm/pull/839
2. This is why we switched to `node_semver` from `semver`
3. A nicer attitude will be appreciated next time 🙏
