### ISSUE TITLE
Getting random "Can't infer shell!" on M1 with fish shell

### ISSUE THREAD

**Issue by chamini2** [Schniz/fnm#920]
I come back to my terminal session with random errors while not using it

```
❯ error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
```

Did fish support get dropped?

**Comment by Schniz** [comment]
Nope, probably just a wrong error message!
Try running it with `RUST_LOG=fnm=debug` env var. can you tell me the output?

**Comment by Schniz** [comment]
So, we do support fish. Btw I’d recommend using `—shell=fish` and avoiding the inference as it is slower to load.

**Comment by Schniz** [comment]
Maybe I need to update the setup scripts.

**Comment by chamini2** [comment]
The thing is that `fnm` seems to work fine, but my terminal will get these random errors every once in a while. With the computer not being used, even.

**Comment by dalisoft** [comment]
@chamini2 Set your login command or Run command in Terminal this value: `login -fpql YOUR_USERNAME /opt/homebrew/bin/fish` (note, this works if you installed via Homebrew)

**Comment by chamini2** [comment]
and what should that do? @dalisoft

**Comment by Schniz** [comment]
Without the debug env var we can’t help. Please either attach the debug output or use `--shell=fish` which also performs faster as no inference needed.

**Comment by chamini2** [comment]
got the debug on:

```
❯ [2023-02-02T12:45:37Z DEBUG fnm::shell::infer] binary is not a supported shell: "fnm"
[2023-02-02T12:45:37Z DEBUG fnm::shell::infer] binary is not a supported shell: "fnm"
[2023-02-02T12:45:37Z DEBUG fnm::shell::infer] binary is not a supported shell: "launchd"
[2023-02-02T12:45:37Z DEBUG fnm::shell::infer::unix] Can't read process info: entity not found
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* bash
* zsh
```

I don't know where to set `--shell=fish`

**Comment by chamini2** [comment]
changed it to
```
❯ cat ~/.config/fish/conf.d/fnm.fish
fnm env --use-on-cd --shell=fish | source
```

But not really sure if it's here. I will reopen if it does not get fixed.
