### ISSUE TITLE
Fish shell still uses brew installed `node` version

### ISSUE THREAD

**Issue by nikivdev** [Schniz/fnm#956]
<img width="410" alt="image" src="https://user-images.githubusercontent.com/6391776/236446643-af85a5d5-75e3-4fdc-b00d-fdab5f205157.png">

I don't know why, I think it should be working

**Comment by nikitavoloboev** [comment]
I did this step too:

https://github.com/Schniz/fnm#fish-shell

**Comment by nikitavoloboev** [comment]
ok seems `~/.config/fish/conf.d/fnm.fish` is no longer being read on my version of fish, maybe something changed.

<img width="396" alt="image" src="https://user-images.githubusercontent.com/6391776/236447612-fb19ebe4-3fd1-4c96-8935-66f01687e829.png">

If I manually do above, it works

**Comment by nikitavoloboev** [comment]
Ok was my issue, in my fish config i had this line: `set -gx PATH /Users/nikiv/Library/pnpm $PATH` which overwrote the path.

My fish config now looks like this:

```
# pnpm
set -gx PATH /Users/nikiv/Library/pnpm $PATH

# node
fnm env --use-on-cd | source # https://github.com/Schniz/fnm#fish-shell setup
```

And things wokr.
