### ISSUE TITLE
How to uninstall or remove a installed version?

### ISSUE THREAD

**Issue by tranwalle** [Schniz/fnm#96]
Can I uninstall a version which was installed?

**Comment by Schniz** [comment]
Currently, via `rm -rf ~/.fnm/node-versions/<VERSION>`. We should add a `fnm uninstall` that encapsulates that though.

**Comment by jakeklassen** [comment]
I created an [npm package](https://github.com/jakeklassen/fnm-uninstall) to address this for myself for now. Still needs a little work to support custom install directories, but has been ok for my use case.

**Comment by Schniz** [comment]
Hey, let's try to make it into fnm! shouldn't be too hard 😄 If you want to try, we can do that together over chat on Discord or something 😄

**Comment by jakeklassen** [comment]
I would love to, I just need to pickup Reason haha.

**Comment by Schniz** [comment]
We can always try the naive implementation (exec a `rm -r`), and fix that along the way. I think it's a good way to start 😄

**Comment by Schniz** [comment]
Also, for re-install, we can add a `--reinstall{-if-exists}` option to `fnm install`

**Comment by tatchi** [comment]
@jakeklassen Are you planning to work on this? If not, I would be happy to make a PR :)

**Comment by jakeklassen** [comment]
@tatchi Not at the moment, by all means go ahead :+1:

**Comment by WolfCodeBind** [comment]
Can someone pls tell me how to delete fnm completely from the machine?

**Comment by Sujit-Ingenio** [comment]
> Can someone pls tell me how to delete fnm completely from the machine?

Delete the `.fnm` folder in Home directory.

For Windows - 
Delete the `.fnm` directory from user directory `C:\Users\<Your-User>\AppData\Roaming`.
And remove the Environment config of fnm as well.

**Comment by Divyansh-04** [comment]
I am unable to remove fnm from my windows machine, I delete the C:\Users\<Your-User>\AppData\Roaming\fnm directory, and 
C:\Users\<Your-User>\AppData\Local\fnm_multishells, but the files keep coming back.

**Comment by crvargasm** [comment]
I found searching with the command `fnm env` the path `C:\Users\<YOUR_USER>\AppData\Local\Microsoft\WinGet\Packages` because I install the package with WinGet. I hope it works for any people, greetings.

![image](https://github.com/user-attachments/assets/4d371184-1250-49be-804f-940f1c291bf7)

**Comment by hyunbinseo** [comment]
For macOS users who used Homebrew to install fnm, the location is:

```
/Users/username/Library/Application Support/fnm/node-versions
```

Open it in Finder using:

```shell
cd ~/Library/Application\ Support/fnm/node-versions
open .
```

**Comment by beechow** [comment]
on windows i did this:

get these info:

PS C:\Users\USER> fnm env
$env:PATH = "C:\Users\USER\AppData\Local\fnm_multishells\21664_1742747387708;E:\appcp\adoptium-eclipse-temurin\jdk-17.0.14.7-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Users\USER\AppData\Local\Microsoft\WindowsApps;C:\Users\USER\AppData\Local\Programs\cursor\resources\app\bin;C:\Users\USER\AppData\Local\Microsoft\WinGet\Packages\Schniz.fnm_Microsoft.Winget.Source_8wekyb3d8bbwe;"
$env:FNM_MULTISHELL_PATH = "C:\Users\USER\AppData\Local\fnm_multishells\21664_1742747387708"
$env:FNM_VERSION_FILE_STRATEGY = "local"
$env:FNM_DIR = "C:\Users\USER\AppData\Roaming\fnm"
$env:FNM_LOGLEVEL = "info"
$env:FNM_NODE_DIST_MIRROR = "https://nodejs.org/dist"
$env:FNM_COREPACK_ENABLED = "false"
$env:FNM_RESOLVE_ENGINES = "true"
$env:FNM_ARCH = "x64"

in powershell, run: 
	> winget uninstall Schniz.fnm
	(it removes the installed fnm package from C:\Users\USER\AppData\Local\Microsoft\WinGet\Packages)

manual remove the appended path for both system environment and user environment:
	(e.g. C:\Users\USER\AppData\Local\Microsoft\WinGet\Packages\Schniz.fnm_Microsoft.Winget.Source_8wekyb3d8bbwe)

manual delete fnm installed node files:  e.g. C:\Users\USER\AppData\Local\fnm_multishells

manual delete fnm files:
	$env:FNM_MULTISHELL_PATH = "C:\Users\USER\AppData\Local\fnm_multishells\21664_1742747387708"
	$env:FNM_DIR = "C:\Users\USER\AppData\Roaming\fnm"

**Comment by toyess-37** [comment]
How to fix the issue in windows:

```
fnm : The term 'fnm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
```

I tried installing using `winget install Schniz.fnm`.
