### ISSUE TITLE
Window PowerShell profile setting not working

### ISSUE THREAD

**Issue by jasmine-my** [Schniz/fnm#970]
Hi
I follw the manual installation, but it is not working.

1. I installed fnm through this command.
````powershell
scoop install fnm
````
2. Then, set the powershell profile like this.
````powershell
fnm env --use-on-cd --shell powershell | Out-String | Invoke-Expression
````
![image](https://github.com/Schniz/fnm/assets/83268528/3a956c6b-8f8e-4560-8000-678ec7b245cf)

3. This setting was not working.
![image](https://github.com/Schniz/fnm/assets/83268528/5750438c-b679-4fef-91f8-000c24fb2565)

I'm using
- Window 11
- PowerShell 5.1

**Comment by Schniz** [comment]
Looks like issue with scoop, as the binary isn’t found. I’m closing but lmk what you find.
