### ISSUE TITLE
Running under WSL but executable is on windows.

### ISSUE THREAD

**Issue by erenerturk1** [Schniz/fnm#975]
So to do this I added this to my ```.bash_aliases```
```bash
alias fnm='fnm.exe '
```
But after adding the linux setup line to my ```.bashrc```, it gave this error:
```
error: Can't infer shell!
fnm can't infer your shell based on the process tree.
Maybe it is unsupported? we support the following shells:
* cmd
* powershell
* bash
* zsh
* fish
```
I am using fnm version 1.33.1 and bash 5.0.17. Adding ```--shell bash``` just causes a error while actually using it.
This is an intentional duplicate of #758, to get it more attention (although I do actually happen to experience this problem).

**Comment by Schniz** [comment]
1. Why having the executable on windows?
2. Can you share what you get from the following command: `RUST_LOG=fnm=debug fnm env`?
3. What’s the error you’re getting when setting the explicit shell option?

**Comment by erenerturk1** [comment]
1. Simplicity due to less things to manage
2. I fixed it by using an alternative, ```n``` so I can't do that right now.
3. It was an error about not having set the correct environment variables, if I remember correctly.
I'll close this now.
